"""Evidence-labelled Energy subsector classification."""
from __future__ import annotations
from typing import Any
COHORTS={"OIL_GAS_UPSTREAM":{"ONGC","OIL"},"OIL_GAS_REFINING":{"MRPL","CHENNPETRO"},"OIL_GAS_MARKETING":{"IOC","BPCL","HINDPETRO"},"OIL_GAS_INTEGRATED":{"RELIANCE"},"POWER_GENERATION":{"NTPC","TORNTPOWER","CESC"},"POWER_TRANSMISSION":{"POWERGRID","INDIGRID"},"POWER_DISTRIBUTION":{"TATAPOWER","ADANIENSOL"},"RENEWABLE_POWER":{"ADANIGREEN","JSWENERGY","KPIGREEN"},"SOLAR":{"WAAREEENER","BORORENEW","WEBELSOLAR"},"WIND":{"SUZLON","INOXWIND"},"HYDRO_POWER":{"NHPC","SJVN"},"NUCLEAR_SUPPLY_CHAIN":{"BHEL","LT","MTARTECH"},"COAL":{"COALINDIA","NLCINDIA"},"GAS_UTILITIES":{"GAIL","GSPL"},"CITY_GAS_DISTRIBUTION":{"IGL","MGL","GUJGASLTD","ATGL"},"OILFIELD_SERVICES":{"ABAN","JINDRILL","DEEPINDS"},"MINING_SERVICES":{"POWERMECH","DBL"},"WATER_UTILITIES":{"WABAG","EMSLIMITED"},"WASTE_MANAGEMENT":{"ANTONY","ECORECO"},"ENERGY_STORAGE_BATTERIES":{"EXIDEIND","AMARAJABAT","HBLENGINE"}}
ALIASES={"UPSTREAM":"OIL_GAS_UPSTREAM","REFINING":"OIL_GAS_REFINING","MARKETING":"OIL_GAS_MARKETING","INTEGRATED_ENERGY":"OIL_GAS_INTEGRATED","POWER":"POWER_GENERATION","TRANSMISSION":"POWER_TRANSMISSION","DISTRIBUTION":"POWER_DISTRIBUTION","RENEWABLE":"RENEWABLE_POWER","HYDRO":"HYDRO_POWER","NUCLEAR":"NUCLEAR_SUPPLY_CHAIN","CGD":"CITY_GAS_DISTRIBUTION","BATTERIES":"ENERGY_STORAGE_BATTERIES"}
def classify_energy(company:dict[str,Any])->dict[str,Any]:
 symbol=str(company.get("symbol") or company.get("company_id") or "").upper(); explicit=str(company.get("energy_subsector") or company.get("subsector") or "").upper().replace(" ","_").replace("&","AND"); explicit=ALIASES.get(explicit,explicit)
 if explicit in COHORTS:return {"status":"CLASSIFIED","parent_sector":"ENERGY_UTILITIES_NATURAL_RESOURCES","subsector":explicit,"model_family":explicit,"source":"company_master.energy_subsector","confidence":.98,"effective_date":company.get("classification_effective_date")}
 matches=[family for family,symbols in COHORTS.items() if symbol in symbols]
 if len(matches)==1:return {"status":"CLASSIFIED","parent_sector":"ENERGY_UTILITIES_NATURAL_RESOURCES","subsector":matches[0],"model_family":matches[0],"source":"phase_5_reviewed_cohort_registry","confidence":.90,"effective_date":"2026-08-16"}
 if len(matches)>1:return {"status":"DIVERSIFIED","parent_sector":"ENERGY_UTILITIES_NATURAL_RESOURCES","candidate_subsectors":matches,"requires_sotp":True,"source":"phase_5_reviewed_cohort_registry","confidence":.75}
 segments=company.get("segments") if isinstance(company.get("segments"),list) else []; material=[row for row in segments if str(row.get("energy_subsector") or "").upper() in COHORTS and float(row.get("revenue_share") or 0)>=.1]
 if len(material)>1:return {"status":"DIVERSIFIED","parent_sector":"ENERGY_UTILITIES_NATURAL_RESOURCES","segments":material,"requires_sotp":True,"source":"company_segment_disclosure","confidence":.85}
 return {"status":"CLASSIFICATION_UNAVAILABLE","parent_sector":"ENERGY_UTILITIES_NATURAL_RESOURCES","symbol":symbol,"confidence":0.0}
