"""Authoritative Phase 5 sector curricula."""
from __future__ import annotations
from financials_valuation.schema import KPIKnowledge,SectorValuationModel,ValuationMethodRule
VERSION="energy-valuation-v5.0.0"; PARENT_SECTOR="ENERGY_UTILITIES_NATURAL_RESOURCES"
def k(key,name,why,chain):return KPIKnowledge(key,name,why,"reported or AFE-calculated from cited inputs","context_specific","Quarterly/Annual",("Audited filing","NSE/BSE","Official results","Regulatory filing"),why,(chain,),"Changes normalized FCF, returns and valuation.","Scope, asset state and cycle require reconciliation.",( "VALIDATED","TRUSTED"))
def m(method,tier,reason):return ValuationMethodRule(method,tier,reason,(),(reason,),("Requires normalized PIT inputs.",),("Missing/stale inputs","Peak-cycle denominator","Wrong asset state"))
COMMON=(k("capacity","Capacity","Potential output; not generation or revenue.","capacity -> availability -> output"),k("utilization","Utilization","Links demand to available assets.","demand / available capacity -> utilization"),k("volume","Volume","Physical production, generation or throughput.","volume x price -> revenue"),k("realization","Realization","Price or tariff actually earned.","realization - unit cost -> spread"),k("ebitda","EBITDA","Operating output before capital burden.","spread x volume -> EBITDA"),k("capex","Capex","Separates maintenance and expansion investment.","capex -> capacity -> returns"),k("fcf","Free Cash Flow","Tests cash after reinvestment.","EBITDA - capex - working capital -> FCF"),k("net_debt","Net Debt","Measures financing burden and equity risk.","debt service -> equity FCF"),k("roic","ROIC","Tests growth versus value creation.","normalized return / invested capital"),k("asset_life","Asset Life","Bounds cash-flow duration.","asset life -> terminal economics"))
RESOURCE=(k("reserves","Economically Recoverable Reserves","Only economic reserves support NAV.","reserves / production -> reserve life"),k("reserve_life","Reserve Life","Measures depletion horizon.","reserves / production"),k("cash_cost","Cash Cost","Defines commodity spread.","price - cash cost -> margin"))
POWER=(k("generation","Generation","Actual electrical output.","MW x availability x hours -> generation"),k("plf","PLF / Capacity Factor","Measures utilized generation potential.","generation / theoretical output"),k("tariff","Tariff","Contractual or regulated realization.","generation x tariff -> revenue"),k("debt_per_mw","Debt per MW","Project financing intensity.","debt / MW -> debt service"))
REG=(k("regulated_asset_base","Regulated Asset Base","Base on which allowed return is earned.","RAB x allowed return -> revenue"),k("allowed_return","Allowed Return","Regulatory return, distinct from accounting ROE.","allowed return -> tariff requirement"),k("collection_efficiency","Collection Efficiency","Separates billing from cash.","billing x collection -> cash"))
CFG={
"OIL_GAS_UPSTREAM":("Oil & Gas — Upstream",RESOURCE,("Crude/gas price","Production","Lifting cost","Reserve replacement"),("NAV","GORDON_DCF","EV_EBITDA","ENERGY_EV_PER_RESERVE")),
"OIL_GAS_REFINING":("Oil & Gas — Refining",(k("throughput","Refinery Throughput","Converts capacity into saleable products.","crude throughput x yield"),k("grm","Gross Refining Margin","Cycle-normalized refining spread.","product value - crude/energy cost")),("Throughput","GRM","Product yield","Energy cost"),("EV_EBITDA","GORDON_DCF","NAV")),
"OIL_GAS_MARKETING":("Oil & Gas — Marketing",(k("outlets","Retail Outlets","Distribution reach, not throughput alone.","outlets x volume/outlet"),k("marketing_margin","Marketing Margin","Unit margin after regulated pricing effects.","volume x marketing margin")),("Volumes","Outlet productivity","Marketing margin","Subsidy"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF")),
"OIL_GAS_INTEGRATED":("Oil & Gas — Integrated",RESOURCE+(k("segment_economics","Segment Economics","Prevents one segment masking another.","segment FCF -> SOTP"),),("Upstream","Refining","Marketing","Petrochemicals","Renewables"),("SOTP_3_SEGMENT","NAV","GORDON_DCF","EV_EBITDA")),
"POWER_GENERATION":("Power Generation",POWER,("Demand","PLF","Tariff","Fuel cost"),("GORDON_DCF","EV_EBITDA","ENERGY_EV_PER_MW","NAV")),
"POWER_TRANSMISSION":("Power Transmission",POWER+REG,("Asset base","Availability","Allowed return","Capex"),("GORDON_DCF","NAV","EV_EBITDA")),
"POWER_DISTRIBUTION":("Power Distribution",POWER+REG+(k("atc_losses","AT&C Losses","Revenue growth can coexist with economic leakage.","supply - billed/collected units"),),("Demand","Tariff-cost gap","AT&C losses","Subsidy receivable"),("GORDON_DCF","NAV","EV_EBITDA")),
"RENEWABLE_POWER":("Renewable Power",POWER+(k("ppa_duration","PPA Duration","Bounds contracted tariff visibility.","PPA term -> contracted FCF"),),("MW additions","Capacity factor","Tariff","Counterparty"),("GORDON_DCF","ENERGY_EV_PER_MW","NAV")),
"SOLAR":("Solar",POWER+(k("business_mode","Solar Business Mode","Separates manufacturing, EPC and generation.","mode -> economics/valuation"),),("Module spread","EPC execution","Generation/PPA"),("GORDON_DCF","EV_EBITDA","ENERGY_EV_PER_MW","SOTP_3_SEGMENT")),
"WIND":("Wind",POWER+(k("turbine_availability","Turbine Availability","Conditions wind-resource conversion.","wind resource x availability -> generation"),),("Wind resource","Availability","Tariff","Maintenance"),("GORDON_DCF","ENERGY_EV_PER_MW","NAV")),
"HYDRO_POWER":("Hydro Power",POWER+(k("hydrology","Hydrology","Prevents extrapolating one water year.","water availability -> generation"),),("Hydrology","Reservoir","Tariff","Project life"),("GORDON_DCF","NAV","ENERGY_EV_PER_MW")),
"NUCLEAR_SUPPLY_CHAIN":("Nuclear / Nuclear Supply Chain",POWER+(k("project_duration","Project Duration","Long construction periods drive financing risk.","delay -> capex/interest -> returns"),),("Reactor capacity","Availability","Construction cost","Fuel"),("GORDON_DCF","NAV","EV_EBITDA")),
"COAL":("Coal",RESOURCE+(k("stripping_ratio","Stripping Ratio","Changes mine unit cost.","overburden / coal -> cash cost"),),("Production","Realization","Cash cost","Royalties"),("NAV","GORDON_DCF","EV_EBITDA")),
"GAS_UTILITIES":("Gas Utilities",REG+(k("gas_volume","Gas Volume","Contracted throughput base.","volume x tariff -> revenue"),),("Volumes","Gas sourcing","Tariff","Contracts"),("GORDON_DCF","EV_EBITDA","NAV")),
"CITY_GAS_DISTRIBUTION":("City Gas Distribution",(k("cng_volume","CNG Volume","Mobility conversion and station usage.","vehicle conversion -> CNG volume"),k("png_volume","PNG Volume","Household/industrial network demand.","connections x usage"),k("stations","Stations","Network reach and capital intensity.","stations -> volume")),("CNG/PNG volumes","Gas cost","Unit margin","Network capex"),("PRICE_TO_EARNINGS","EV_EBITDA","GORDON_DCF")),
"OILFIELD_SERVICES":("Oilfield Services",(k("rig_utilization","Rig Utilization","Exploration capex transmission.","oil price -> E&P capex -> rig demand"),k("day_rate","Day Rate","Price earned per active rig day.","utilization x day rate"),k("backlog","Backlog","Conditional contracted revenue.","contract -> service revenue")),("E&P capex","Utilization","Day rates","Fleet age"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF")),
"MINING_SERVICES":("Mining Services",(k("contract_volume","Contract Volume","Executable service demand.","contract volume x price"),k("equipment_utilization","Equipment Utilization","Fixed-cost absorption.","fleet utilization -> margin")),("Contract volumes","Fleet utilization","Fuel","Labour"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF")),
"WATER_UTILITIES":("Water Utilities",REG+(k("treatment_capacity","Treatment Capacity","Serviceable physical capacity.","capacity x utilization x tariff"),),("Demand","Treatment utilization","Tariff","Collection"),("GORDON_DCF","NAV","EV_EBITDA")),
"WASTE_MANAGEMENT":("Waste Management",(k("waste_volume","Waste Volume","Physical service base.","tonnes x tipping fee"),k("tipping_fee","Tipping Fee","Contractual realization per tonne.","volume x fee -> revenue"),k("concession_life","Concession Life","Bounds project cash flows.","concession term -> FCF duration")),("Waste volumes","Tipping fees","Treatment","Recycling"),("GORDON_DCF","EV_EBITDA","NAV")),
"ENERGY_STORAGE_BATTERIES":("Energy Storage / Batteries",(k("gwh_capacity","GWh Capacity","Manufacturing or project capacity, not sales.","GWh x utilization"),k("battery_price_kwh","Battery Price/kWh","Unit realization.","price - input cost -> spread"),k("cycle_life","Cycle Life","Service durability and replacement economics.","cycles/degradation -> asset value")),("Battery demand","Utilization","Price/kWh","Materials","Degradation"),("EV_SALES","EV_EBITDA","GORDON_DCF","NAV")),
}
REASONS={"NAV":"Asset, reserve or project-level value.","GORDON_DCF":"Explicit project and asset cash flows.","EV_EBITDA":"Normalized operating comparison.","PRICE_TO_EARNINGS":"Normalized profitable equity earnings.","SOTP_3_SEGMENT":"Distinct segment economics.","ENERGY_EV_PER_RESERVE":"Reserve cross-check only.","ENERGY_EV_PER_MW":"Capacity cross-check only.","EV_SALES":"Early-stage capacity with credible margin path only."}
def build(f,c):
 name,kpis,drivers,methods=c
 return SectorValuationModel(f"ENERGY.{f}",name,f,(name,),"Demand transmits through capacity, physical output, price/tariff, unit cost, capital and financing into normalized equity FCF.",drivers,("Fuel/input cost","Operating cost","Maintenance","Financing"),"Asset intensity, maintenance/expansion capex and project versus corporate debt are central.",( "Tariff","Environment","Safety","Land","Resource/contract approvals"),COMMON+kpis,tuple(m(x,"PRIMARY" if i==0 else "CROSS_CHECK",REASONS[x]) for i,x in enumerate(methods)),drivers,("Commodity/cycle","Regulation","Project delay","Debt","Counterparty"),("volume","utilization","price/tariff","unit cost","capex"),tuple(item.name for item in kpis)+("FCF","Debt","Asset life"),("Installed capacity is not output","Resources are not economic reserves","Peak earnings are not normalized earnings","Reported return is not allowed regulated return"),("Audited filings","Regulatory orders","NSE/BSE","Official operating disclosures"),"2026-08-16",.80,"IMPLEMENTED_NOT_RESEARCH_VALIDATED",VERSION)
MODELS={family:build(family,cfg) for family,cfg in CFG.items()}
CAUSAL={family:(("demand","volume","utilization","price_or_tariff","unit_cost","ebitda","capex","fcf","debt","equity_value"),("capacity_addition","supply","utilization","price","margin","roic"),("commodity_price","producer_margin","capex","future_supply","future_price")) for family in MODELS}
