import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {request,when} from './api';
export default function EnergyIntelligence(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[search,setSearch]=useState(''),[sector,setSector]=useState('all'),[busy,setBusy]=useState(false);
 async function load(){setBusy(true);setError('');try{setData(await request('/energy'));}catch(e){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{load();},[]);
 const fmt=v=>v==null?'—':Number(v).toLocaleString('en-IN',{maximumFractionDigits:2});
 return <section><div className="gi-section-title"><h2>Indian energy · prices & news</h2><button disabled={busy} onClick={load}>{busy?'Checking…':'Refresh energy data'}</button></div>
 <p className="gi-note">20 listed companies. Upstox snapshots are cached for five minutes, not streamed live. News covers the provider’s past seven days, up to 100 articles per batch. Research themes below are hypotheses, not confirmed facility exposure or trading signals.</p>
 {error&&<p role="alert" className="gi-error">{error}</p>}
 {data&&<><p>Batch retrieved {when(data.generatedAt)} · Prices in INR. Check each last-trade time; closed-market prices can be from the previous session.</p>{data.quoteError&&<p role="alert">{data.quoteError}</p>}{data.newsError&&<p role="alert">{data.newsError}</p>}{data.newsTruncated&&<p className="gi-note">More articles exist at the provider. This panel shows the first 100 returned articles across the watchlist.</p>}
 <div className="gi-filter"><input aria-label="Search energy companies" placeholder="Company or symbol…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Energy sector" value={sector} onChange={e=>setSector(e.target.value)}><option value="all">All energy sectors</option>{[...new Set(data.companies.map(c=>c.sector))].map(s=><option key={s}>{s}</option>)}</select></div>
 <div className="gi-assets">{data.companies.filter(c=>(sector==='all'||sector===c.sector)&&`${c.symbol} ${c.name}`.toLowerCase().includes(search.toLowerCase())).map(c=><article key={c.symbol}><span className="gi-kicker">{c.symbol} · {c.sector}</span><h3>{c.name}</h3><h2>₹{fmt(c.quote?.price)} <small>{c.quote?.changePercent==null?'':`${fmt(c.quote.changePercent)}%`}</small></h2><p>Open {fmt(c.quote?.open)} · High {fmt(c.quote?.high)} · Low {fmt(c.quote?.low)}<br/>Previous close {fmt(c.quote?.previousClose)} · Volume {fmt(c.quote?.volume)}</p><small>Last trade: {when(c.quote?.lastTradeTime)}<br/>Quote timestamp: {when(c.quote?.quoteTime)}</small>{!c.quote&&<p>Quote unavailable.</p>}<h4>What to investigate</h4><p>{c.exposure}</p><h4>Company news · Upstox</h4>{c.news.length?c.news.slice(0,5).map(n=><div key={n.url+n.publishedAt}><a href={n.url} target="_blank" rel="noopener noreferrer">{n.heading} ↗</a><p><small>{when(n.publishedAt)}</small></p><p>{n.summary}</p></div>):<p>{data.newsError?'News could not be retrieved.':'No articles returned for this company in this batch.'}</p>}{c.news.length>5&&<details><summary>{c.news.length-5} more articles</summary>{c.news.slice(5).map(n=><p key={n.url+n.publishedAt}><a href={n.url} target="_blank" rel="noopener noreferrer">{n.heading} ↗</a> · {when(n.publishedAt)}</p>)}</details>}{['RELIANCE','IOC','NTPC'].includes(c.symbol)&&<Link to={`/intelligence/companies/${c.symbol}`}>View documented company areas →</Link>}</article>)}</div></>}
 </section>;
}
