import React, { Suspense, lazy, useEffect, useMemo, useRef, useState } from 'react';
import { Link, useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { request, when } from './api';
import './intelligence.css';
const Globe=lazy(()=>import('./IntelligenceGlobe'));
const SOURCE_NAMES={usgs:'USGS earthquakes',eonet:'NASA EONET'};
const ROADMAP=[['God’s Eye View','Reference for globe interactions; its data feeds are not connected.','https://github.com/bilawalsidhu/gods-eye-view'],['World Monitor','Under evaluation; AGPL obligations / commercial terms need review.','https://github.com/koala73/worldmonitor'],['OpenBB','Planned market-data adapter; underlying provider permissions required.','https://github.com/OpenBB-finance/OpenBB'],['changedetection.io','Planned monitoring of company operational notices.','https://github.com/dgtlmoon/changedetection.io'],['Open-Meteo','Planned weather context; commercial hosted access is not configured.','https://github.com/open-meteo/open-meteo'],['earthaccess','Planned NASA dataset discovery and authentication.','https://github.com/nsidc/earthaccess'],['sentinelhub-py','Planned satellite-image workflow; service access is not configured.','https://github.com/sentinel-hub/sentinelhub-py'],['Kepler.gl','Planned analyst map exploration.','https://github.com/keplergl/kepler.gl'],['EdgarTools','Planned US company filing evidence.','https://github.com/dgunning/edgartools']];
function External({url,children}){return <a href={url} target="_blank" rel="noopener noreferrer">{children} ↗</a>;}
function Review({event}) {return event.review?.status==='published'?<section className="gi-review"><span className="gi-kicker">Analyst assessment · {when(event.review.reviewed_at)}</span><h3>What to investigate</h3><p>{event.review.assessment}</p><h4>Uncertainty</h4><p>{event.review.uncertainty}</p><h4>Next evidence to check</h4><p>{event.review.next_check}</p><External url={event.review.evidence_url}>Assessment evidence</External></section>:<p className="gi-note">No current analyst assessment is published for this event. Geographic proximity alone does not establish operational or financial impact.</p>;}
export default function GlobalIntelligencePage(){
  const {user}=useAuth(),navigate=useNavigate(),location=useLocation();
  const identity=useRef(user?.id);identity.current=user?.id;
  const parts=location.pathname.split('/').filter(Boolean),view=parts[1]||'overview',selectedId=parts[2]?decodeURIComponent(parts[2]):null;
  const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[source,setSource]=useState('all'),[category,setCategory]=useState('all'),[matched,setMatched]=useState(false),[days,setDays]=useState('30');
  const [companySearch,setCompanySearch]=useState(''),[sector,setSector]=useState('all');
  const [watch,setWatch]=useState([]),[watchReady,setWatchReady]=useState(false),[saving,setSaving]=useState(false),[notice,setNotice]=useState(''),[visibleCount,setVisibleCount]=useState(30);
  async function reload(){setLoading(true);setError('');try{setData(await request('/snapshot'));}catch(e){setError(e.message);}finally{setLoading(false);}}
  useEffect(()=>{reload();},[]);
  useEffect(()=>{let ignore=false;setWatch([]);setWatchReady(false);if(user)request('/watchlist',{},true).then(d=>{if(!ignore){setWatch(d.symbols);setWatchReady(true);}}).catch(e=>{if(!ignore)setNotice(e.message);});return()=>{ignore=true;};},[user?.id]);
  async function toggle(symbol){if(!user){setNotice('Sign in to save companies to your private watchlist.');return;}const actor=user.id;setSaving(true);setNotice('');try{const next=watch.includes(symbol)?watch.filter(x=>x!==symbol):[...watch,symbol];const d=await request('/watchlist',{method:'POST',body:JSON.stringify({symbols:next})},true);if(identity.current===actor)setWatch(d.symbols);}catch(e){if(identity.current===actor)setNotice(e.message);}finally{setSaving(false);}}
  const companies=useMemo(()=>[...new Set(data?.assets.map(a=>a.symbol)||[])].map(symbol=>({symbol,company:data.assets.find(a=>a.symbol===symbol).company,assets:data.assets.filter(a=>a.symbol===symbol)})),[data]);
  const sectors=useMemo(()=>[...new Set(companies.flatMap(c=>c.assets.map(a=>a.sector)))].sort(),[companies]);
  const filteredCompanies=useMemo(()=>companies.filter(c=>(sector==='all'||c.assets.some(a=>a.sector===sector))&&`${c.symbol} ${c.company} ${c.assets.map(a=>`${a.name} ${a.sector}`).join(' ')}`.toLowerCase().includes(companySearch.trim().toLowerCase())),[companies,sector,companySearch]);
  const events=useMemo(()=>data?.events.filter(e=>(source==='all'||e.provider===source)&&(category==='all'||e.category===category)&&(!matched||e.matches.length>0)&&new Date(e.observed_at).getTime()>=Date.now()-Number(days)*86400000&&`${e.title} ${e.category} ${e.matches.map(m=>m.company).join(' ')}`.toLowerCase().includes(search.toLowerCase()))||[],[data,source,category,matched,days,search]);
  useEffect(()=>{setVisibleCount(30);},[search,source,category,matched,days,view]);
  const event=data?.events.find(e=>e.id===selectedId),company=companies.find(c=>c.symbol===selectedId);
  function card(e){return <Link className="gi-event" key={e.id} to={`/intelligence/events/${encodeURIComponent(e.id)}`}><div className="gi-event-meta"><span>{e.category}</span><span>{SOURCE_NAMES[e.provider]}</span></div><h3>{e.title}</h3><time>{when(e.observed_at)}</time><div className="gi-event-bottom"><span>{e.matches.length?`${e.matches.length} nearby mapped ${e.matches.length===1?'asset':'assets'}`:'No mapped asset within 100 km'}</span><span>{e.review?.status==='published'?'Assessment published':'Source observation'} →</span></div></Link>;}
  function companyCard(c){return <article className="gi-company" key={c.symbol}><div><span className="gi-kicker">{c.symbol}</span><h3><Link to={`/intelligence/companies/${c.symbol}`}>{c.company} ↗</Link></h3><p>{c.assets.length} mapped areas · {c.assets[0].sector}</p></div><button disabled={saving||(!!user&&!watchReady)} onClick={()=>toggle(c.symbol)}>{watch.includes(c.symbol)?'✓ Watching':'+ Watch'}</button></article>;}
  return <main className="gi-shell"><header className="gi-header"><Link className="gi-brand" to="/">AGI <span>GLOBAL INTELLIGENCE</span></Link><div><Link to="/">Research home ↗</Link>{!user&&<Link to="/login">Sign in</Link>}</div></header>
    <nav className="gi-nav" aria-label="Global Intelligence">{[['overview','Overview'],['map','World map'],['companies','Companies'],['watchlist','My watchlist'],['sources','Sources & coverage']].map(([key,label])=><Link key={key} className={view===key?'active':''} to={key==='overview'?'/intelligence':`/intelligence/${key}`}>{label}</Link>)}</nav>
    <div className="gi-body"><div className="gi-heading"><div><span className="gi-kicker">AGI RESEARCH / WORLD EVENTS</span><h1>{view==='map'?'The world in context.':view==='companies'?(company?.company||'Company exposure directory.'):view==='watchlist'?'Your companies. Your evidence.':view==='sources'?'Know what you’re looking at.':view==='events'?'Event evidence.':'Events worth investigating.'}</h1><p>Reported events, company locations and sourced analyst assessments in one research workspace.</p></div><button onClick={reload} disabled={loading}>{loading?'Loading…':'Refresh feed ↻'}</button></div>
    {error&&<p role="alert" className="gi-error">{error} {data&&'Showing the last loaded snapshot.'}</p>}{notice&&<p role="status" className="gi-note">{notice}</p>}
    {data&&<><div className="gi-metrics"><div><strong>{data.events.length}</strong><span>reported events · last 30 days</span></div><div><strong>{companies.length} / {data.assets.length}</strong><span>pilot companies / mapped areas</span></div><div><strong>{data.events.filter(e=>e.review?.status==='published').length}</strong><span>current published assessments</span></div><div><strong>{data.sources.filter(s=>s.last_success_at&&Date.now()-new Date(s.last_success_at)<2*3600000&&s.status==='ok').length} / {data.sources.length}</strong><span>feeds checked within two hours</span></div></div>
    <p className="gi-source-strip">{data.sources.map(s=><span key={s.id}>{s.name}: {s.status==='error'?'refresh failed · ':''}last successful check {when(s.last_success_at)}</span>)} <Link to="/intelligence/sources">Coverage →</Link></p>
    {['overview','map'].includes(view)&&<><div className="gi-filter"><input aria-label="Search events" placeholder="Search events, companies or categories…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Source" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{data.sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select aria-label="Event category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All event types</option>{[...new Set(data.events.map(e=>e.category))].sort().map(c=><option key={c}>{c}</option>)}</select><select aria-label="Period" value={days} onChange={e=>setDays(e.target.value)}><option value="30">Last 30 days</option><option value="7">Last 7 days</option></select><label><input type="checkbox" checked={matched} onChange={e=>setMatched(e.target.checked)}/> Near mapped assets</label></div>
    {view==='map'&&<Suspense fallback={<p>Loading interactive globe…</p>}><Globe events={events} assets={data.assets} onEvent={id=>navigate(`/intelligence/events/${encodeURIComponent(id)}`)} onCompany={s=>navigate(`/intelligence/companies/${s}`)}/></Suspense>}
    <div className="gi-columns"><section><div className="gi-section-title"><h2>Source observations</h2><span>{events.length} events</span></div>{events.length?events.slice(0,visibleCount).map(card):<div className="gi-empty">No events match these filters. Try all event types or turn off the proximity filter.</div>}{events.length>visibleCount&&<button onClick={()=>setVisibleCount(n=>n+30)}>Show more events</button>}</section><aside><h2>Research, with context.</h2><p>A reported event becomes useful when it can be connected to an operating asset and supported by company evidence.</p><ol><li>Read the original source.</li><li>Inspect the geographic match.</li><li>Check current company disclosures.</li><li>Assess the financial significance.</li></ol><div className="gi-note">The 100 km radius is a search aid. It is not a hazard boundary or a buy/sell signal.</div><h3>Companies in the pilot</h3>{companies.map(c=><Link className="gi-aside-link" key={c.symbol} to={`/intelligence/companies/${c.symbol}`}>{c.company}<span>→</span></Link>)}</aside></div></>}
    {view==='events'&&(event?<><Link to="/intelligence">← All events</Link><div className="gi-detail"><section><span className="gi-kicker">{SOURCE_NAMES[event.provider]} / {event.category}</span><h2>{event.title}</h2><dl><dt>Event observed</dt><dd>{when(event.observed_at)}</dd><dt>First captured by AGI</dt><dd>{when(event.first_seen_at)}</dd><dt>Last seen in source feed</dt><dd>{when(event.last_seen_at)}</dd><dt>Source updated</dt><dd>{when(event.source_updated_at)}</dd><dt>Source publication time</dt><dd>{when(event.published_at)}</dd><dt>Status at source</dt><dd>{event.source_status}</dd></dl><External url={event.source_url}>Read original source</External><Review event={event}/></section><aside><h3>Nearby company areas</h3><p>100 km radius from the reported point. Storm tracks, fire perimeters and asset boundaries are not represented.</p>{event.matches.length?event.matches.map(m=><div key={m.asset_id} className="gi-match"><Link to={`/intelligence/companies/${m.symbol}`}>{m.company} →</Link><p>{m.name} · {m.distance_km} km</p><small>{m.location_precision}</small></div>):<p>No mapped company assets within the search radius. The pilot does not cover all listed companies.</p>}</aside></div></>:<p className="gi-empty">Event not found in the current 30-day feed.</p>)}
    {view==='companies'&&(selectedId?(company?<><Link to="/intelligence/companies">← Company directory</Link>{companyCard(company)}<h2>Documented operating footprint</h2><div className="gi-assets">{company.assets.map(a=><article key={a.id}><span className="gi-kicker">{a.confidence} relationship</span><h3>{a.name}</h3><p>{a.relationship}</p><p>{a.evidence_note}</p><small>{a.location_precision} · {a.latitude}, {a.longitude}<br/>Record reviewed {when(a.verified_at)}</small><p><External url={a.source_url}>Company evidence</External></p></article>)}</div><h2>Events near these mapped areas</h2>{data.events.filter(e=>e.matches.some(m=>m.symbol===company.symbol)).length?data.events.filter(e=>e.matches.some(m=>m.symbol===company.symbol)).map(card):<p className="gi-empty">No current feed observations within 100 km of these mapped areas. This does not establish an absence of risk.</p>}</>:<p>Company not in the pilot directory.</p>):<><p className="gi-note">Current coverage: {companies.length} listed companies and {data.assets.length} approximate asset areas. Relationships come from company documents; these records are not a complete portfolio exposure model.</p><div className="gi-filter"><input aria-label="Search companies or asset areas" placeholder="Company, symbol or asset area…" value={companySearch} onChange={e=>setCompanySearch(e.target.value)}/><select aria-label="Company sector" value={sector} onChange={e=>setSector(e.target.value)}><option value="all">All sectors</option>{sectors.map(s=><option key={s}>{s}</option>)}</select>{(companySearch||sector!=='all')&&<button onClick={()=>{setCompanySearch('');setSector('all');}}>Clear filters</button>}</div><p role="status">{filteredCompanies.length} of {companies.length} companies</p><div className="gi-company-grid">{filteredCompanies.map(companyCard)}</div>{!filteredCompanies.length&&<p className="gi-empty">No companies match these filters. Try a different company, asset area or sector.</p>}</>)}
    {view==='watchlist'&&<>{!user?<div className="gi-empty"><h2>A private list for your account.</h2><p>Sign in, then choose companies from the directory.</p><Link to="/login">Sign in →</Link></div>:<><div className="gi-company-grid">{companies.filter(c=>watch.includes(c.symbol)).map(companyCard)}</div>{!watch.length&&<p className="gi-empty">Your watchlist is empty. <Link to="/intelligence/companies">Choose companies →</Link></p>}<h2>Nearby observations for watched companies</h2>{data.events.filter(e=>e.matches.some(m=>watch.includes(m.symbol))).map(card)}{watch.length>0&&!data.events.some(e=>e.matches.some(m=>watch.includes(m.symbol)))&&<p>No matching observations in the current feed.</p>}</>}</>}
    {view==='sources'&&<><h2>Connected public feeds</h2><div className="gi-assets">{data.sources.map(s=><article key={s.id}><span className="gi-kicker">{s.status==='ok'?'Connected · polling every 30 minutes':s.status==='checking'?'Checking source':s.last_success_at?'Last refresh failed':'Awaiting successful collection'}</span><h3>{s.name}</h3><p>{s.id==='usgs'?'Magnitude 4.5+ earthquakes from the past seven days. Preliminary reports may change.':'Natural events from a 30-day query, up to 100 results. Only the latest point is displayed, not a complete event footprint.'}</p><p>Last success: {when(s.last_success_at)}<br/>Last attempt: {when(s.last_attempt_at)}<br/>Last batch: {s.last_count??'—'} events</p>{s.status==='error'&&<p className="gi-error">The source refresh failed. Previously captured records remain visible.</p>}<External url={s.id==='usgs'?'https://earthquake.usgs.gov/earthquakes/feed/v1.0/geojson.php':'https://eonet.gsfc.nasa.gov/docs/v3'}>Provider documentation</External></article>)}</div><h2>Planned integrations · not connected</h2><div className="gi-assets">{ROADMAP.map(([name,description,url])=><article key={name}><h3>{name}</h3><p>{description}</p><External url={url}>Repository</External></article>)}</div><p>Map renderer: <External url="https://github.com/vasturiano/globe.gl">globe.gl (MIT)</External>. Country shapes: <External url="https://github.com/topojson/world-atlas">World Atlas / Natural Earth</External>. Third-party data permissions are separate from software licences.</p></>}
    <footer className="gi-footer"><p>{data.coverage}</p><p>Snapshot loaded {when(data.generated_at)}. No automatic trading or return forecasts.</p></footer></>}
    </div></main>;
}
