import React,{useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {request,when} from './api';

export function DocumentMonitor({symbol,admin=false}){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 async function load(){setError('');try{setData(await request(admin?'/admin/documents':'/documents',{},admin));}catch(e){setError(e.message);}}
 useEffect(()=>{let ignore=false;request(admin?'/admin/documents':'/documents',{},admin).then(d=>{if(!ignore)setData(d);}).catch(e=>{if(!ignore)setError(e.message);});return()=>{ignore=true;};},[admin]);
 async function collect(){setBusy(true);setError('');try{const d=await request('/admin/documents/collect',{method:'POST'},true);setNotice(d.message);await load();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const monitors=data?.monitors.filter(m=>!symbol||m.symbol===symbol)||[];
 return <section className="gi-workflow"><div className="gi-section-title"><h2>Official page monitor</h2><div className="gi-admin-actions"><button onClick={load}>Refresh status</button>{admin&&<button disabled={busy} onClick={collect}>{busy?'Requesting…':'Check official pages'}</button>}</div></div><p>Daily checks of selected company evidence pages. A page edit needs review before any business-impact conclusion.</p>{error&&<p role="alert" className="gi-error">{error}</p>}{notice&&<p role="status" className="gi-note">{notice}</p>}{!data&&!error&&<p>Loading document coverage…</p>}<div className="gi-assets">{monitors.map(m=><article key={m.id}><span className="gi-kicker">{m.symbol} · {m.status==='ok'?'Checked':m.status==='error'?'Check failed':m.status==='checking'?'Checking':'Awaiting baseline'}</span><h3><a href={m.url} target="_blank" rel="noopener noreferrer">{m.title} ↗</a></h3><p>Last successful check: {when(m.last_success_at)}<br/>Last detected edit: {m.last_changed_at?when(m.last_changed_at):'None recorded'}<br/>{m.revision_count} captured {m.revision_count===1?'version':'versions'}</p>{m.status==='error'&&<p className="gi-error">Latest check failed; previous captures are retained.{admin&&` ${m.last_error||''}`}</p>}<details><summary>Capture history</summary>{data.versions.filter(v=>v.monitor_id===m.id).map(v=><div className="gi-version" key={v.id}><strong>{v.baseline?'Initial baseline':'Text changed'} · {when(v.captured_at)}</strong>{!v.baseline&&<p>{v.added_lines} text blocks added / {v.removed_lines} removed</p>}{admin&&!v.baseline&&<><p>Added extract: {v.added_excerpt||'None'}</p><p>Removed extract: {v.removed_excerpt||'None'}</p></>}</div>)}</details></article>)}</div>{data&&!monitors.length&&<p className="gi-empty">No official page has been configured for this company yet.</p>}{data&&<p className="gi-note">{data.coverage}</p>}</section>;
}

export function EventRevisionHistory({id}){
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let ignore=false;setData(null);setError('');request(`/events/${encodeURIComponent(id)}/history`).then(d=>{if(!ignore)setData(d);}).catch(e=>{if(!ignore)setError(e.message);});return()=>{ignore=true;};},[id]);
 return <section className="gi-workflow"><h3>Saved source revisions</h3>{error&&<p role="alert">{error}</p>}{!data&&!error&&<p>Loading captured revisions…</p>}{data&&<><p>{data.coverage}</p><div className="gi-revisions">{data.versions.map((v,i)=><details key={v.id}><summary>{i===0?'Latest capture':`Earlier capture`} · {when(v.captured_at)}{v.baseline?' · archive baseline':''}</summary><p>{v.facts.title}</p><dl><dt>Event observed</dt><dd>{when(v.facts.observed_at)}</dd><dt>Source status</dt><dd>{v.facts.source_status}</dd><dt>Coordinates</dt><dd>{v.facts.latitude}, {v.facts.longitude}</dd>{v.facts.magnitude!=null&&<><dt>Magnitude</dt><dd>{v.facts.magnitude}</dd></>}</dl></details>)}</div></>}</section>;
}

export function AlertInbox({user,watch}){
 const [data,setData]=useState(null),[draft,setDraft]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const [refresh,setRefresh]=useState(0);
 useEffect(()=>{let ignore=false;setData(null);setDraft(null);setError('');setNotice('');if(user)request('/alerts',{},true).then(d=>{if(!ignore){setData({...d,owner:user.id});setDraft(d.preferences);}}).catch(e=>{if(!ignore)setError(e.message);});return()=>{ignore=true;};},[user?.id,refresh,watch.join(',')]);
 // Changing identity unmounts this component in the parent; late writes cannot show another user's inbox.
 async function save(){setBusy(true);setError('');try{await request('/alerts',{method:'POST',body:JSON.stringify(draft)},true);setRefresh(x=>x+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 async function markRead(){setBusy(true);try{await request('/alerts/read',{method:'POST',body:JSON.stringify({through:data.loaded_at})},true);setRefresh(x=>x+1);}catch(e){setError(e.message);}finally{setBusy(false);}}
 if(!user)return null;
 return <section className="gi-workflow"><div className="gi-section-title"><h2>Your alert inbox</h2><button disabled={busy} onClick={()=>setRefresh(x=>x+1)}>Refresh inbox</button></div><p>Private, in-app updates for your current watchlist. No email or push messages are sent.</p>{error&&<p className="gi-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{draft&&data?.owner===user.id&&<><fieldset className="gi-alert-options"><legend>Choose updates</legend>{[['enabled','Enable my inbox'],['assessments','Published company-linked assessments'],['documents','Official page changes'],['observations','Nearby observations (impact unconfirmed)']].map(([key,label])=><label key={key}><input type="checkbox" checked={draft[key]} disabled={busy} onChange={e=>setDraft({...draft,[key]:e.target.checked})}/>{label}</label>)}<button disabled={busy} onClick={save}>Save preferences</button></fieldset><p className="gi-note">Updates begin when you enable the inbox. Up to 100 matching items from the last 30 days are shown; feed and document coverage limits apply. Re-enabling starts a new alert window. Your current watchlist determines which items appear.</p>{data.preferences.enabled?<><div className="gi-section-title"><h3>{data.items.filter(i=>i.unread).length} unread</h3><button disabled={busy||!data.items.some(i=>i.unread)} onClick={markRead}>Mark displayed updates read</button></div>{data.items.length?data.items.map(i=><Link className="gi-event" key={i.id} to={i.href}><span className="gi-kicker">{i.unread?'● New · ':''}{i.kind}</span><h3>{i.title}</h3><p>{i.detail}</p><time>{when(i.at)}</time></Link>):<p className="gi-empty">No matching updates since you enabled the inbox. Add companies to your watchlist and return after new evidence arrives.</p>}</>:<p>Your alert inbox is off.</p>}</>}{!data&&!error&&<p>Loading your preferences…</p>}</section>;
}

export function ArchivedEvent({id}){
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{let ignore=false;setData(null);setError('');request(`/events/${encodeURIComponent(id)}/history`).then(d=>{if(!ignore)setData(d);}).catch(e=>{if(!ignore)setError(e.message);});return()=>{ignore=true;};},[id]);
 if(error)return <p className="gi-error" role="alert">{error}</p>;
 if(!data)return <p>Looking up the saved observation…</p>;
 const e=data.event;
 return <><Link to="/intelligence/archive">← Saved observations</Link><h2>{e.title}</h2><p>Observed {when(e.observed_at)} · First captured {when(e.first_seen_at)}</p><a href={e.source_url} target="_blank" rel="noopener noreferrer">Original source ↗</a><p className="gi-note">Archived observation outside the current feed. It is not a current operational-status report.</p>{e.review&&<section className="gi-review"><h3>Published assessment</h3><p>{e.review.assessment}</p><p>Uncertainty: {e.review.uncertainty}</p><p>Next evidence: {e.review.next_check}</p><a href={e.review.evidence_url} target="_blank" rel="noopener noreferrer">Assessment evidence ↗</a></section>}<EventRevisionHistory id={id}/></>;
}
export function EventArchive(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(1),[query,setQuery]=useState(''),[search,setSearch]=useState('');
 useEffect(()=>{let ignore=false;setError('');setData(null);request(`/archive?page=${page}&search=${encodeURIComponent(search)}`).then(d=>{if(!ignore)setData(d);}).catch(e=>{if(!ignore)setError(e.message);});return()=>{ignore=true;};},[page,search]);
 return <section><h2>Saved observations</h2><p>Captured records remain available after leaving the rolling source feed. This archive starts with AGI collection; it is not a historical backfill.</p><form className="gi-filter" onSubmit={e=>{e.preventDefault();setPage(1);setSearch(query);}}><input aria-label="Search saved observations" value={query} onChange={e=>setQuery(e.target.value)} maxLength={100} placeholder="Search titles…"/><button type="submit">Search archive</button></form>{error&&<p className="gi-error" role="alert">{error}</p>}{!data&&!error&&<p>Loading archive…</p>}{data&&<><p>{data.total} saved observations · Page {data.page}</p>{data.events.map(e=><Link className="gi-event" key={e.id} to={`/intelligence/events/${encodeURIComponent(e.id)}`}><span className="gi-kicker">{e.provider} · {e.category}</span><h3>{e.title}</h3><time>{when(e.observed_at)}</time></Link>)}{!data.events.length&&<p>No matching saved observations.</p>}<div className="gi-admin-actions"><button disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={page>=100||page*data.page_size>=data.total} onClick={()=>setPage(p=>p+1)}>Next page</button></div></>}</section>;
}
