import { useEffect,useState } from 'react';
import * as XLSX from 'xlsx';
import { AlertTriangle,CheckCircle2,Database,FileSpreadsheet,RefreshCw,UploadCloud } from 'lucide-react';
import { pmAdminApprove,pmAdminOverview,pmAdminPreview,pmAdminReview } from '@/lib/privateMarketsAdminApi';
async function parse(file){const bytes=await file.arrayBuffer();const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('');const book=XLSX.read(bytes,{type:'array',cellDates:true});return{filename:file.name,fileHash:hash,sheets:book.SheetNames.map(name=>{const matrix=XLSX.utils.sheet_to_json(book.Sheets[name],{header:1,defval:null,raw:false}),header=name==='Equity Deal Book'?3:7,keys=(matrix[header]||[]).map(String);return{name,rows:matrix.slice(header+1).map((values,i)=>({sourceRow:header+i+2,values:Object.fromEntries(keys.map((key,j)=>[key,values[j]??null]))})).filter(row=>Object.values(row.values).some(v=>v!==null&&v!==''))}})}}
export default function PrivateMarketsDataAdmin(){
 const[state,setState]=useState(null),[payload,setPayload]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(''),[error,setError]=useState('');
 const load=()=>pmAdminOverview().then(setState).catch(e=>setError(e.message));useEffect(load,[]);
 const choose=async e=>{const file=e.target.files?.[0];if(!file)return;setBusy('Reading workbook');setError('');try{const body=await parse(file);setPayload(body);setPreview(await pmAdminPreview(body))}catch(x){setError(x.message)}finally{setBusy('')}};
 const approve=async()=>{setBusy('Importing');try{setPreview(await pmAdminApprove(payload));await load()}catch(x){setError(x.message)}finally{setBusy('')}};
 return <div className="min-h-screen bg-slate-100"><header className="bg-[#102d25] px-8 py-8 text-white"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-emerald-300">AGI Private Markets</p><h1 className="mt-2 font-serif text-4xl">Data Administration</h1><p className="mt-2 text-sm text-emerald-100/70">Preview and approve incremental licensed-workbook updates.</p></header><main className="mx-auto grid max-w-[1500px] gap-6 p-6 lg:grid-cols-[1fr_350px]"><div className="space-y-6"><section className="bg-white p-6"><h2 className="font-serif text-2xl">Upload workbook</h2><p className="text-sm text-slate-500">India Deal Book XLSX or Global PE XLS/XLSX</p><label className="mt-5 flex cursor-pointer justify-center gap-3 border-2 border-dashed p-10"><UploadCloud/><b>{busy||'Choose workbook'}</b><input type="file" accept=".xls,.xlsx" hidden onChange={choose}/></label>{error&&<p className="mt-4 flex gap-2 bg-red-50 p-3 text-red-700"><AlertTriangle/>{error}</p>}</section>
 {preview&&<section className="bg-white p-6"><div className="flex justify-between"><h2 className="font-serif text-2xl">Change preview</h2><b className={preview.valid?'text-emerald-700':'text-red-700'}>{preview.valid?'READY':'BLOCKED'}</b></div><div className="mt-5 grid grid-cols-5 gap-2">{['inserted','updated','unchanged','rejected','total'].map(k=><div className="border p-3" key={k}><small className="uppercase text-slate-400">{k}</small><strong className="block text-2xl">{preview.counts?.[k]||0}</strong></div>)}</div>{preview.errors?.map((x,i)=><p className="text-xs text-amber-700" key={i}>Row {x.sourceRow||'—'}: {x.reason}</p>)}<button disabled={!preview.valid||busy} onClick={approve} className="mt-5 bg-[#102d25] px-5 py-3 font-bold text-white disabled:opacity-40">{busy||'Approve import'}</button></section>}
 <section className="bg-white"><header className="flex justify-between border-b p-5"><h2 className="font-serif text-xl">Import history</h2><button onClick={load}><RefreshCw/></button></header><div className="overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-3">File</th><th>Domain</th><th>Status</th><th>Accepted</th><th>Rejected</th></tr></thead><tbody>{state?.history?.map(r=><tr className="border-t" key={r.id}><td className="p-3 font-semibold">{r.source_file}</td><td>{r.dataset_domain}</td><td>{r.status}</td><td>{r.records_accepted}</td><td>{r.records_rejected}</td></tr>)}</tbody></table></div></section></div>
 <aside className="space-y-6"><section className="bg-[#102d25] p-5 text-white"><Database/><h2 className="mt-3 font-serif text-xl">Live dataset</h2><div className="mt-4 grid grid-cols-2 gap-3">{Object.entries(state?.counts||{}).map(([k,v])=><div key={k}><small className="uppercase text-emerald-200/60">{k}</small><strong className="block text-2xl">{v}</strong></div>)}</div></section><section className="bg-white p-5"><h2 className="font-serif text-xl">Entity review</h2>{state?.reviews?.length?state.reviews.map(r=><article className="mt-3 border p-3" key={r.id}><b>{r.source_name}</b><p className="text-xs">Confidence {Math.round(r.confidence*100)}%</p><button className="mr-2 mt-2 bg-emerald-700 px-2 py-1 text-xs text-white" onClick={()=>pmAdminReview(r.id,'approved').then(load)}>Approve</button><button className="border px-2 py-1 text-xs" onClick={()=>pmAdminReview(r.id,'rejected').then(load)}>Reject</button></article>):<p className="mt-3 flex gap-2 text-sm text-slate-500"><CheckCircle2/>No uncertain matches.</p>}</section></aside></main></div>
}
