"""Versioned allow-list for deterministic AFE calculations."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Callable


@dataclass(frozen=True)
class CalculationSpec:
    calculation_id: str
    name: str
    category: str
    formula: str
    required_inputs: tuple[str, ...]
    output_unit: str
    function: Callable[[dict[str, float]], float]
    version: str = "1.0.0"
    methodology: str = "AGI deterministic methodology"
    allow_mixed_units: bool = False
    allow_mixed_periods: bool = False

    def public(self) -> dict:
        row = asdict(self)
        row.pop("function", None)
        return row


def _div(a: float, b: float) -> float:
    if b == 0:
        raise ZeroDivisionError
    return a / b


def _growth(i: dict[str, float], begin: str, end: str) -> float:
    return (_div(i[end], i[begin]) - 1.0) * 100.0


def _avg(i: dict[str, float], opening: str, closing: str) -> float:
    return (i[opening] + i[closing]) / 2.0


SPECS = (
    CalculationSpec("PERCENT_CHANGE", "Percentage Change", "basic", "(end / beginning - 1) * 100", ("beginning", "end"), "percent", lambda i: _growth(i, "beginning", "end")),
    CalculationSpec("CAGR", "Compound Annual Growth Rate", "returns", "(end / beginning)^(1 / years) - 1", ("beginning", "end", "years"), "percent", lambda i: ((_div(i["end"], i["beginning"]) ** (1.0 / i["years"])) - 1.0) * 100.0),
    CalculationSpec("PRESENT_VALUE", "Present Value", "time_value", "future_value / (1 + rate)^periods", ("future_value", "rate", "periods"), "currency", lambda i: _div(i["future_value"], (1.0 + i["rate"]) ** i["periods"])),
    CalculationSpec("FUTURE_VALUE", "Future Value", "time_value", "present_value * (1 + rate)^periods", ("present_value", "rate", "periods"), "currency", lambda i: i["present_value"] * (1.0 + i["rate"]) ** i["periods"]),
    CalculationSpec("ROE", "Return on Equity", "profitability", "PAT / average equity * 100", ("pat", "opening_equity", "closing_equity"), "percent", lambda i: _div(i["pat"], _avg(i, "opening_equity", "closing_equity")) * 100.0, methodology="PAT divided by average opening and closing equity"),
    CalculationSpec("ROA", "Return on Assets", "profitability", "PAT / average assets * 100", ("pat", "opening_assets", "closing_assets"), "percent", lambda i: _div(i["pat"], _avg(i, "opening_assets", "closing_assets")) * 100.0),
    CalculationSpec("LOAN_GROWTH", "Loan Growth", "banking", "(closing loans / opening loans - 1) * 100", ("opening_loans", "closing_loans"), "percent", lambda i: _growth(i, "opening_loans", "closing_loans")),
    CalculationSpec("DEPOSIT_GROWTH", "Deposit Growth", "banking", "(closing deposits / opening deposits - 1) * 100", ("opening_deposits", "closing_deposits"), "percent", lambda i: _growth(i, "opening_deposits", "closing_deposits")),
    CalculationSpec("CASA_RATIO", "CASA Ratio", "banking", "CASA deposits / total deposits * 100", ("casa_deposits", "total_deposits"), "percent", lambda i: _div(i["casa_deposits"], i["total_deposits"]) * 100.0),
    CalculationSpec("CREDIT_DEPOSIT_RATIO", "Credit-Deposit Ratio", "banking", "gross loans / deposits * 100", ("gross_loans", "deposits"), "percent", lambda i: _div(i["gross_loans"], i["deposits"]) * 100.0),
    CalculationSpec("GNPA_RATIO", "Gross NPA Ratio", "banking", "gross NPA / gross advances * 100", ("gross_npa", "gross_advances"), "percent", lambda i: _div(i["gross_npa"], i["gross_advances"]) * 100.0),
    CalculationSpec("NNPA_RATIO", "Net NPA Ratio", "banking", "net NPA / net advances * 100", ("net_npa", "net_advances"), "percent", lambda i: _div(i["net_npa"], i["net_advances"]) * 100.0),
    CalculationSpec("PCR", "Provision Coverage Ratio", "banking", "accumulated provisions / relevant NPA base * 100", ("accumulated_provisions", "npa_base"), "percent", lambda i: _div(i["accumulated_provisions"], i["npa_base"]) * 100.0),
    CalculationSpec("NIM", "Net Interest Margin", "banking", "net interest income / average interest-earning assets * 100", ("net_interest_income", "opening_interest_earning_assets", "closing_interest_earning_assets"), "percent", lambda i: _div(i["net_interest_income"], _avg(i, "opening_interest_earning_assets", "closing_interest_earning_assets")) * 100.0),
    CalculationSpec("CREDIT_COST", "Credit Cost", "banking", "provisions / average loans * 100", ("provisions", "opening_loans", "closing_loans"), "percent", lambda i: _div(i["provisions"], _avg(i, "opening_loans", "closing_loans")) * 100.0),
    CalculationSpec("CET1_RATIO", "CET1 Ratio", "banking", "CET1 capital / risk-weighted assets * 100", ("cet1_capital", "risk_weighted_assets"), "percent", lambda i: _div(i["cet1_capital"], i["risk_weighted_assets"]) * 100.0),
    CalculationSpec("CRAR", "Capital Adequacy Ratio", "banking", "eligible regulatory capital / risk-weighted assets * 100", ("regulatory_capital", "risk_weighted_assets"), "percent", lambda i: _div(i["regulatory_capital"], i["risk_weighted_assets"]) * 100.0),
    CalculationSpec("COST_TO_INCOME", "Cost-to-Income Ratio", "banking", "operating expenses / operating income * 100", ("operating_expenses", "operating_income"), "percent", lambda i: _div(i["operating_expenses"], i["operating_income"]) * 100.0),
    CalculationSpec("PRICE_TO_BOOK", "Price to Book", "valuation", "market price per share / book value per share", ("market_price", "book_value_per_share"), "multiple", lambda i: _div(i["market_price"], i["book_value_per_share"])),
    CalculationSpec("PRICE_TO_EARNINGS", "Price to Earnings", "valuation", "market price per share / normalized earnings per share", ("market_price", "normalized_eps"), "multiple", lambda i: _div(i["market_price"], i["normalized_eps"])),
    CalculationSpec("BANK_PRICE_TO_BOOK", "Bank Price to Book", "bank_valuation", "point-in-time market price per share / latest available book value per share", ("market_price", "book_value_per_share"), "multiple", lambda i: _div(i["market_price"], i["book_value_per_share"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("BANK_PRICE_TO_EARNINGS", "Bank Price to Earnings", "bank_valuation", "point-in-time market price per share / latest available normalized earnings per share", ("market_price", "normalized_eps"), "multiple", lambda i: _div(i["market_price"], i["normalized_eps"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("FINANCIAL_PRICE_TO_BOOK", "Financial Institution Price to Book", "financials_valuation", "point-in-time market price per share / latest available book value per share", ("market_price", "book_value_per_share"), "multiple", lambda i: _div(i["market_price"], i["book_value_per_share"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("FINANCIAL_PRICE_TO_EARNINGS", "Financial Institution Price to Earnings", "financials_valuation", "point-in-time market price per share / latest available normalized earnings per share", ("market_price", "normalized_eps"), "multiple", lambda i: _div(i["market_price"], i["normalized_eps"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("JUSTIFIED_PB", "Justified Price to Book", "bank_valuation", "(ROE - growth) / (cost of equity - growth)", ("roe", "growth", "cost_of_equity"), "multiple", lambda i: _div(i["roe"] - i["growth"], i["cost_of_equity"] - i["growth"])),
    CalculationSpec("PRICE_TO_TANGIBLE_BOOK", "Price to Tangible Book", "bank_valuation", "market price / tangible book value per share", ("market_price", "tangible_book_value_per_share"), "multiple", lambda i: _div(i["market_price"], i["tangible_book_value_per_share"])),
    CalculationSpec("BANK_RESIDUAL_INCOME", "Bank Residual Income Value", "bank_valuation", "book value + book value * (ROE - cost of equity) / (cost of equity - growth)", ("book_value", "roe", "cost_of_equity", "growth"), "currency", lambda i: i["book_value"] + _div(i["book_value"] * (i["roe"] - i["cost_of_equity"]), i["cost_of_equity"] - i["growth"]), allow_mixed_units=True),
    CalculationSpec("BANK_DDM", "Bank Gordon Growth DDM", "bank_valuation", "next dividend / (cost of equity - growth)", ("next_dividend", "cost_of_equity", "growth"), "currency", lambda i: _div(i["next_dividend"], i["cost_of_equity"] - i["growth"]), allow_mixed_units=True),
    CalculationSpec("BANK_IMPLIED_ROE", "Market-Implied Bank ROE", "bank_reverse_valuation", "P/B * (cost of equity - growth) + growth", ("price_to_book", "cost_of_equity", "growth"), "decimal", lambda i: i["price_to_book"] * (i["cost_of_equity"] - i["growth"]) + i["growth"], allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("BANK_IMPLIED_GROWTH", "Market-Implied Bank Growth", "bank_reverse_valuation", "(ROE - P/B * cost of equity) / (1 - P/B)", ("roe", "price_to_book", "cost_of_equity"), "decimal", lambda i: _div(i["roe"] - i["price_to_book"] * i["cost_of_equity"], 1.0 - i["price_to_book"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("PRICE_TO_EMBEDDED_VALUE", "Price to Embedded Value", "insurance_valuation", "market price / embedded value per share", ("market_price", "embedded_value_per_share"), "multiple", lambda i: _div(i["market_price"], i["embedded_value_per_share"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("EV_EBITDA", "Enterprise Value to EBITDA", "operating_financial_valuation", "enterprise value / EBITDA", ("enterprise_value", "ebitda"), "multiple", lambda i: _div(i["enterprise_value"], i["ebitda"])),
    CalculationSpec("EV_SALES", "Enterprise Value to Sales", "fintech_valuation", "enterprise value / revenue", ("enterprise_value", "revenue"), "multiple", lambda i: _div(i["enterprise_value"], i["revenue"])),
    CalculationSpec("EV_GROSS_PROFIT", "Enterprise Value to Gross Profit", "fintech_valuation", "enterprise value / gross profit", ("enterprise_value", "gross_profit"), "multiple", lambda i: _div(i["enterprise_value"], i["gross_profit"])),
    CalculationSpec("GORDON_DCF", "Gordon Growth Equity Value", "cash_flow_valuation", "next period FCF / (discount rate - terminal growth)", ("next_fcf", "discount_rate", "terminal_growth"), "currency", lambda i: _div(i["next_fcf"], i["discount_rate"] - i["terminal_growth"]), allow_mixed_units=True),
    CalculationSpec("FCF_YIELD", "Free Cash Flow Yield", "valuation", "FCF per share / market price", ("fcf_per_share", "market_price"), "decimal", lambda i: _div(i["fcf_per_share"], i["market_price"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("VNB_MARGIN", "Value of New Business Margin", "insurance", "VNB / APE", ("vnb", "ape"), "decimal", lambda i: _div(i["vnb"], i["ape"])),
    CalculationSpec("COMBINED_RATIO", "Combined Ratio", "insurance", "claims ratio + expense ratio", ("claims_ratio", "expense_ratio"), "decimal", lambda i: i["claims_ratio"] + i["expense_ratio"], allow_mixed_units=True),
    CalculationSpec("FEE_YIELD", "Asset Management Fee Yield", "asset_management", "revenue / average AUM", ("revenue", "average_aum"), "decimal", lambda i: _div(i["revenue"], i["average_aum"])),
    CalculationSpec("TAKE_RATE", "Payments Take Rate", "fintech", "revenue / TPV", ("revenue", "tpv"), "decimal", lambda i: _div(i["revenue"], i["tpv"])),
    CalculationSpec("CONTRIBUTION_MARGIN", "Contribution Margin", "fintech", "contribution profit / revenue", ("contribution_profit", "revenue"), "decimal", lambda i: _div(i["contribution_profit"], i["revenue"])),
    CalculationSpec("IMPLIED_GROWTH_FROM_PE", "Market-Implied Growth from P/E", "reverse_valuation", "cost of equity - payout ratio / P/E", ("cost_of_equity", "payout_ratio", "price_to_earnings"), "decimal", lambda i: i["cost_of_equity"] - _div(i["payout_ratio"], i["price_to_earnings"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("IMPLIED_GROWTH_FROM_MULTIPLE", "Market-Implied Growth from Multiple", "reverse_valuation", "(current multiple / terminal multiple)^(1 / horizon years) - 1", ("current_multiple", "terminal_multiple", "horizon_years"), "decimal", lambda i: (_div(i["current_multiple"], i["terminal_multiple"]) ** _div(1.0, i["horizon_years"])) - 1.0, allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("IMPLIED_HOLDCO_DISCOUNT", "Market-Implied Holding Company Discount", "reverse_valuation", "1 - market capitalization / gross SOTP equity value", ("market_cap","segment_1_value","segment_2_value","segment_3_value","net_debt"), "decimal", lambda i: 1.0 - _div(i["market_cap"], i["segment_1_value"] + i["segment_2_value"] + i["segment_3_value"] - i["net_debt"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("SOTP_3_SEGMENT", "Three-Segment Sum of the Parts", "diversified_valuation", "(segment 1 + segment 2 + segment 3 - net debt) * (1 - holdco discount)", ("segment_1_value", "segment_2_value", "segment_3_value", "net_debt", "holdco_discount"), "currency", lambda i: (i["segment_1_value"] + i["segment_2_value"] + i["segment_3_value"] - i["net_debt"]) * (1.0 - i["holdco_discount"]), allow_mixed_units=True),
    CalculationSpec("MARGIN_OF_SAFETY", "Margin of Safety", "valuation", "(intrinsic value - market price) / intrinsic value * 100", ("intrinsic_value", "market_price"), "percent", lambda i: _div(i["intrinsic_value"] - i["market_price"], i["intrinsic_value"]) * 100.0),
    CalculationSpec("TELECOM_REVENUE_IMPACT", "Telecom ARPU Revenue Impact", "telecom", "ARPU * tariff change * subscribers * realization", ("arpu", "tariff_change", "subscribers", "realization"), "currency", lambda i: i["arpu"] * i["tariff_change"] * i["subscribers"] * i["realization"], methodology="Scenario output; tariff_change and realization are decimal assumptions"),
    CalculationSpec("TELECOM_SUBSCRIBER_GROWTH", "Telecom Subscriber Growth", "telecom", "closing subscribers / opening subscribers - 1", ("opening_subscribers","closing_subscribers"), "decimal", lambda i: _div(i["closing_subscribers"],i["opening_subscribers"]) - 1.0),
    CalculationSpec("TELECOM_ANNUAL_SERVICE_REVENUE", "Telecom Annualized Service Revenue", "telecom", "average subscribers * monthly ARPU * 12", ("opening_subscribers","closing_subscribers","monthly_arpu"), "currency", lambda i: _avg(i,"opening_subscribers","closing_subscribers")*i["monthly_arpu"]*12.0, allow_mixed_units=True, methodology="Subscriber/ARPU bridge, not reported consolidated revenue"),
    CalculationSpec("TELECOM_EV_PER_SUBSCRIBER", "Telecom EV per Subscriber", "telecom_valuation", "enterprise value / subscribers", ("enterprise_value","subscribers"), "currency_per_subscriber", lambda i: _div(i["enterprise_value"],i["subscribers"]), allow_mixed_units=True),
    CalculationSpec("TELECOM_CAPEX_INTENSITY", "Telecom Capex Intensity", "telecom", "capex / revenue", ("capex","revenue"), "decimal", lambda i: _div(i["capex"],i["revenue"])),
    CalculationSpec("TELECOM_EBITDA_MARGIN", "Telecom EBITDA Margin", "telecom", "EBITDA / revenue", ("ebitda","revenue"), "decimal", lambda i: _div(i["ebitda"],i["revenue"])),
    CalculationSpec("TELECOM_NET_DEBT_EBITDA", "Telecom Net Debt to EBITDA", "telecom", "net debt plus spectrum liabilities / EBITDA", ("net_debt","spectrum_liabilities","ebitda"), "multiple", lambda i: _div(i["net_debt"]+i["spectrum_liabilities"],i["ebitda"]), allow_mixed_units=True),
    CalculationSpec("TELECOM_INTEREST_COVERAGE", "Telecom Interest Coverage", "telecom", "EBITDA / interest expense", ("ebitda","interest_expense"), "multiple", lambda i: _div(i["ebitda"],i["interest_expense"])),
    CalculationSpec("TELECOM_ENTERPRISE_MIX", "Telecom Enterprise Revenue Mix", "telecom", "enterprise revenue / total revenue", ("enterprise_revenue","revenue"), "decimal", lambda i: _div(i["enterprise_revenue"],i["revenue"])),
    CalculationSpec("TELECOM_SCENARIO_EQUITY", "Telecom Tariff Scenario Equity Value", "technology_scenario", "(EBITDA + ARPU * tariff change * subscribers * 12 * realization * incremental margin) * target EV/EBITDA - net debt - spectrum liabilities", ("ebitda","arpu","tariff_change","subscribers","realization","incremental_margin","target_ev_ebitda","net_debt","spectrum_liabilities"), "currency", lambda i: (i["ebitda"]+i["arpu"]*i["tariff_change"]*i["subscribers"]*12.0*i["realization"]*i["incremental_margin"])*i["target_ev_ebitda"]-i["net_debt"]-i["spectrum_liabilities"], allow_mixed_units=True, methodology="Explicit tariff scenario; assumptions are not facts"),
    CalculationSpec("TOWER_TENANCY_RATIO", "Tower Tenancy Ratio", "telecom_infrastructure", "tenants / revenue-generating sites", ("tenants","sites"), "tenants_per_site", lambda i: _div(i["tenants"],i["sites"]), allow_mixed_units=True),
    CalculationSpec("TOWER_REVENUE_PER_TENANT", "Tower Revenue per Tenant", "telecom_infrastructure", "rental revenue / tenants", ("rental_revenue","tenants"), "currency_per_tenant", lambda i: _div(i["rental_revenue"],i["tenants"]), allow_mixed_units=True),
    CalculationSpec("TOWER_EV_PER_SITE", "Tower EV per Site", "telecom_infrastructure_valuation", "enterprise value / revenue-generating sites", ("enterprise_value","sites"), "currency_per_site", lambda i: _div(i["enterprise_value"],i["sites"]), allow_mixed_units=True),
    CalculationSpec("TOWER_ENERGY_PASS_THROUGH", "Tower Energy Pass-through Coverage", "telecom_infrastructure", "energy reimbursements / energy costs", ("energy_reimbursements","energy_costs"), "multiple", lambda i: _div(i["energy_reimbursements"],i["energy_costs"])),
    CalculationSpec("TOWER_NET_DEBT_EBITDA", "Tower Net Debt to EBITDA", "telecom_infrastructure", "net debt / EBITDA", ("net_debt","ebitda"), "multiple", lambda i: _div(i["net_debt"],i["ebitda"]), allow_mixed_units=True),
    CalculationSpec("TOWER_SCENARIO_EQUITY", "Tower Scenario Equity Value", "technology_scenario", "sites * tenancy ratio * annual rent per tenant * EBITDA margin * target EV/EBITDA - net debt", ("sites","tenancy_ratio","annual_rent_per_tenant","ebitda_margin","target_ev_ebitda","net_debt"), "currency", lambda i: i["sites"]*i["tenancy_ratio"]*i["annual_rent_per_tenant"]*i["ebitda_margin"]*i["target_ev_ebitda"]-i["net_debt"], allow_mixed_units=True, methodology="Explicit contracted-infrastructure scenario; assumptions are not facts"),
    CalculationSpec("TECH_SPECIALIZED_RATIO", "Specialized Technology Ratio", "technology", "numerator / denominator", ("numerator","denominator"), "ratio", lambda i: _div(i["numerator"],i["denominator"]), allow_mixed_units=True),
    CalculationSpec("TECH_SPECIALIZED_GROWTH", "Specialized Technology Growth", "technology", "closing / opening - 1", ("opening","closing"), "decimal", lambda i: _div(i["closing"],i["opening"])-1.0, allow_mixed_units=True),
    CalculationSpec("TECH_SPECIALIZED_SCENARIO_EQUITY", "Specialized Technology Scenario Equity Value", "technology_scenario", "revenue * (1 + revenue growth) * EBITDA margin * target EV/EBITDA - net debt", ("revenue","revenue_growth","ebitda_margin","target_ev_ebitda","net_debt"), "currency", lambda i: i["revenue"]*(1.0+i["revenue_growth"])*i["ebitda_margin"]*i["target_ev_ebitda"]-i["net_debt"], allow_mixed_units=True, methodology="Explicit one-period scenario; assumptions are not facts"),
    CalculationSpec("TECH_PRICE_TO_EARNINGS", "Technology Price to Earnings", "technology_valuation", "point-in-time market price per share / normalized earnings per share", ("market_price", "normalized_eps"), "multiple", lambda i: _div(i["market_price"], i["normalized_eps"]), allow_mixed_units=True, allow_mixed_periods=True),
    CalculationSpec("REVENUE_PER_EMPLOYEE", "Revenue per Employee", "it_services", "revenue / average headcount", ("revenue", "opening_headcount", "closing_headcount"), "currency_per_employee", lambda i: _div(i["revenue"], _avg(i, "opening_headcount", "closing_headcount")), allow_mixed_units=True),
    CalculationSpec("BOOK_TO_BILL", "Book to Bill", "it_services", "total contract value / revenue", ("total_contract_value", "revenue"), "multiple", lambda i: _div(i["total_contract_value"], i["revenue"])),
    CalculationSpec("EBIT_MARGIN", "EBIT Margin", "profitability", "EBIT / revenue", ("ebit", "revenue"), "decimal", lambda i: _div(i["ebit"], i["revenue"])),
    CalculationSpec("GROSS_MARGIN", "Gross Margin", "profitability", "gross profit / revenue", ("gross_profit", "revenue"), "decimal", lambda i: _div(i["gross_profit"], i["revenue"])),
    CalculationSpec("FCF_MARGIN", "Free Cash Flow Margin", "cash_flow", "free cash flow / revenue", ("fcf", "revenue"), "decimal", lambda i: _div(i["fcf"], i["revenue"])),
    CalculationSpec("UTILIZATION_REVENUE_CAPACITY", "IT Services Utilization Revenue Capacity", "it_services", "average headcount * utilization * billing rate * billable periods", ("opening_headcount", "closing_headcount", "utilization", "billing_rate", "billable_periods"), "currency", lambda i: _avg(i, "opening_headcount", "closing_headcount") * i["utilization"] * i["billing_rate"] * i["billable_periods"], allow_mixed_units=True, methodology="Capacity bridge, not reported revenue; utilization is a decimal assumption or disclosed KPI"),
    CalculationSpec("IT_SERVICES_SCENARIO_PRICE", "IT Services Scenario Equity Value per Share", "technology_scenario", "revenue * (1 + revenue growth) * EBIT margin * (1 - tax rate) / shares outstanding * target P/E", ("revenue", "revenue_growth", "ebit_margin", "tax_rate", "shares_outstanding", "target_pe"), "currency_per_share", lambda i: _div(i["revenue"] * (1.0 + i["revenue_growth"]) * i["ebit_margin"] * (1.0 - i["tax_rate"]), i["shares_outstanding"]) * i["target_pe"], allow_mixed_units=True, methodology="Explicit one-period scenario; assumptions are not facts"),
    CalculationSpec("ARR_GROWTH", "Annual Recurring Revenue Growth", "saas", "closing ARR / opening ARR - 1", ("opening_arr", "closing_arr"), "decimal", lambda i: _div(i["closing_arr"], i["opening_arr"]) - 1.0),
    CalculationSpec("NET_REVENUE_RETENTION", "Net Revenue Retention", "saas", "(opening ARR - churned ARR - contraction ARR + expansion ARR) / opening ARR", ("opening_arr", "churned_arr", "contraction_arr", "expansion_arr"), "decimal", lambda i: _div(i["opening_arr"] - i["churned_arr"] - i["contraction_arr"] + i["expansion_arr"], i["opening_arr"])),
    CalculationSpec("GROSS_REVENUE_RETENTION", "Gross Revenue Retention", "saas", "(opening ARR - churned ARR - contraction ARR) / opening ARR", ("opening_arr", "churned_arr", "contraction_arr"), "decimal", lambda i: _div(i["opening_arr"] - i["churned_arr"] - i["contraction_arr"], i["opening_arr"])),
    CalculationSpec("CAC_PAYBACK_MONTHS", "CAC Payback", "saas", "customer acquisition cost / monthly gross profit from new customer", ("customer_acquisition_cost", "monthly_revenue_per_new_customer", "gross_margin"), "months", lambda i: _div(i["customer_acquisition_cost"], i["monthly_revenue_per_new_customer"] * i["gross_margin"]), allow_mixed_units=True),
    CalculationSpec("CUSTOMER_LTV", "Customer Lifetime Value", "saas", "annual revenue per customer * gross margin / annual logo churn", ("annual_revenue_per_customer", "gross_margin", "annual_logo_churn"), "currency_per_customer", lambda i: _div(i["annual_revenue_per_customer"] * i["gross_margin"], i["annual_logo_churn"]), allow_mixed_units=True),
    CalculationSpec("LTV_CAC", "Lifetime Value to CAC", "saas", "customer lifetime value / customer acquisition cost", ("customer_lifetime_value", "customer_acquisition_cost"), "multiple", lambda i: _div(i["customer_lifetime_value"], i["customer_acquisition_cost"]), allow_mixed_units=True),
    CalculationSpec("RULE_OF_40", "Rule of 40", "saas", "ARR growth + free cash flow margin", ("arr_growth", "fcf_margin"), "decimal", lambda i: i["arr_growth"] + i["fcf_margin"], allow_mixed_units=True),
    CalculationSpec("EV_ARR", "Enterprise Value to ARR", "saas_valuation", "enterprise value / annual recurring revenue", ("enterprise_value", "arr"), "multiple", lambda i: _div(i["enterprise_value"], i["arr"])),
    CalculationSpec("SAAS_SCENARIO_EV", "SaaS Scenario Enterprise Value", "technology_scenario", "ARR * (1 + ARR growth) * target EV/ARR", ("arr", "arr_growth", "target_ev_arr"), "currency", lambda i: i["arr"] * (1.0 + i["arr_growth"]) * i["target_ev_arr"], allow_mixed_units=True, methodology="Explicit one-period scenario; assumptions are not facts"),
    CalculationSpec("PLATFORM_TAKE_RATE", "Platform Take Rate", "marketplace", "platform revenue / gross merchandise value", ("revenue", "gmv"), "decimal", lambda i: _div(i["revenue"], i["gmv"])),
    CalculationSpec("PLATFORM_GMV_GROWTH", "Platform GMV Growth", "marketplace", "closing GMV / opening GMV - 1", ("opening_gmv", "closing_gmv"), "decimal", lambda i: _div(i["closing_gmv"], i["opening_gmv"]) - 1.0),
    CalculationSpec("PLATFORM_ORDER_FREQUENCY", "Platform Order Frequency", "marketplace", "orders / active buyers", ("orders", "active_buyers"), "orders_per_buyer", lambda i: _div(i["orders"], i["active_buyers"]), allow_mixed_units=True),
    CalculationSpec("PLATFORM_CONTRIBUTION_MARGIN", "Platform Contribution Margin", "marketplace", "contribution profit / revenue", ("contribution_profit", "revenue"), "decimal", lambda i: _div(i["contribution_profit"], i["revenue"])),
    CalculationSpec("PLATFORM_CUSTOMER_ACQUISITION_COST", "Platform Customer Acquisition Cost", "marketplace", "sales and marketing spend / new customers", ("sales_marketing_spend", "new_customers"), "currency_per_customer", lambda i: _div(i["sales_marketing_spend"], i["new_customers"]), allow_mixed_units=True),
    CalculationSpec("EV_GMV", "Enterprise Value to GMV", "marketplace_valuation", "enterprise value / gross merchandise value", ("enterprise_value", "gmv"), "multiple", lambda i: _div(i["enterprise_value"], i["gmv"])),
    CalculationSpec("PLATFORM_SCENARIO_EV", "Platform Scenario Enterprise Value", "technology_scenario", "GMV * (1 + GMV growth) * take rate * target EV/revenue", ("gmv", "gmv_growth", "take_rate", "target_ev_revenue"), "currency", lambda i: i["gmv"] * (1.0 + i["gmv_growth"]) * i["take_rate"] * i["target_ev_revenue"], allow_mixed_units=True, methodology="Explicit one-period scenario; assumptions are not facts"),
    CalculationSpec("DIGITAL_NET_REVENUE_GROWTH", "Digital Commerce Net Revenue Growth", "digital_commerce", "closing net revenue / opening net revenue - 1", ("opening_net_revenue", "closing_net_revenue"), "decimal", lambda i: _div(i["closing_net_revenue"], i["opening_net_revenue"]) - 1.0),
    CalculationSpec("DIGITAL_AVERAGE_ORDER_VALUE", "Digital Commerce Average Order Value", "digital_commerce", "net sales / net orders", ("net_sales", "net_orders"), "currency_per_order", lambda i: _div(i["net_sales"], i["net_orders"]), allow_mixed_units=True),
    CalculationSpec("DIGITAL_GROSS_MARGIN", "Digital Commerce Gross Margin", "digital_commerce", "gross profit / net revenue", ("gross_profit", "net_revenue"), "decimal", lambda i: _div(i["gross_profit"], i["net_revenue"])),
    CalculationSpec("DIGITAL_INVENTORY_TURNS", "Digital Commerce Inventory Turns", "digital_commerce", "cost of goods sold / average inventory", ("cogs", "opening_inventory", "closing_inventory"), "multiple", lambda i: _div(i["cogs"], _avg(i,"opening_inventory","closing_inventory")), allow_mixed_units=True),
    CalculationSpec("DIGITAL_RETURN_RATE", "Digital Commerce Return Rate", "digital_commerce", "returned orders / gross orders", ("returned_orders", "gross_orders"), "decimal", lambda i: _div(i["returned_orders"], i["gross_orders"]), allow_mixed_units=True),
    CalculationSpec("DIGITAL_AD_ARPU", "Consumer Internet Advertising ARPU", "consumer_internet", "advertising revenue / monetizable users", ("advertising_revenue", "monetizable_users"), "currency_per_user", lambda i: _div(i["advertising_revenue"], i["monetizable_users"]), allow_mixed_units=True),
    CalculationSpec("DIGITAL_SCENARIO_EV", "Consumer Internet Scenario Enterprise Value", "technology_scenario", "net revenue * (1 + growth) * target EV/revenue", ("net_revenue", "revenue_growth", "target_ev_revenue"), "currency", lambda i: i["net_revenue"] * (1.0 + i["revenue_growth"]) * i["target_ev_revenue"], allow_mixed_units=True, methodology="Explicit one-period scenario; assumptions are not facts"),
    CalculationSpec("SEMI_REVENUE_GROWTH", "Semiconductor Revenue Growth", "semiconductor", "closing revenue / opening revenue - 1", ("opening_revenue","closing_revenue"), "decimal", lambda i: _div(i["closing_revenue"],i["opening_revenue"]) - 1.0),
    CalculationSpec("SEMI_CAPACITY_REVENUE", "Semiconductor Capacity Revenue", "semiconductor", "capacity * utilization * yield * average selling price", ("capacity","utilization","yield_rate","average_selling_price"), "currency", lambda i: i["capacity"]*i["utilization"]*i["yield_rate"]*i["average_selling_price"], allow_mixed_units=True, methodology="Capacity bridge, not reported revenue"),
    CalculationSpec("SEMI_RND_INTENSITY", "Semiconductor R&D Intensity", "semiconductor", "research and development expense / revenue", ("rnd_expense","revenue"), "decimal", lambda i: _div(i["rnd_expense"],i["revenue"])),
    CalculationSpec("SEMI_CAPEX_INTENSITY", "Semiconductor Capex Intensity", "semiconductor", "capital expenditure / revenue", ("capex","revenue"), "decimal", lambda i: _div(i["capex"],i["revenue"])),
    CalculationSpec("SEMI_SCENARIO_EV", "Semiconductor Scenario Enterprise Value", "technology_scenario", "revenue * (1 + growth) * EBITDA margin * target EV/EBITDA", ("revenue","revenue_growth","ebitda_margin","target_ev_ebitda"), "currency", lambda i: i["revenue"]*(1.0+i["revenue_growth"])*i["ebitda_margin"]*i["target_ev_ebitda"], allow_mixed_units=True, methodology="Explicit one-period scenario; assumptions are not facts"),
    CalculationSpec("CONSUMER_PRICE_VOLUME_MIX_GROWTH", "Consumer Price-Volume-Mix Growth", "consumer", "(1 + volume growth) * (1 + price/mix growth) - 1", ("volume_growth","price_mix_growth"), "decimal", lambda i: (1.0+i["volume_growth"])*(1.0+i["price_mix_growth"])-1.0, allow_mixed_units=True, methodology="Deterministic decomposition; acquisitions and currency require separate bridges"),
    CalculationSpec("CONSUMER_SALES_PER_STORE", "Consumer Sales per Store", "consumer_unit_economics", "revenue / average stores", ("revenue","opening_stores","closing_stores"), "currency_per_store", lambda i: _div(i["revenue"],_avg(i,"opening_stores","closing_stores")), allow_mixed_units=True),
    CalculationSpec("CONSUMER_SALES_DENSITY", "Retail Sales Density", "consumer_unit_economics", "revenue / average retail area", ("revenue","opening_retail_area","closing_retail_area"), "currency_per_area", lambda i: _div(i["revenue"],_avg(i,"opening_retail_area","closing_retail_area")), allow_mixed_units=True),
    CalculationSpec("CONSUMER_INVENTORY_TURNS", "Consumer Inventory Turns", "consumer_quality", "cost of goods sold / average inventory", ("cogs","opening_inventory","closing_inventory"), "multiple", lambda i: _div(i["cogs"],_avg(i,"opening_inventory","closing_inventory")), allow_mixed_units=True),
    CalculationSpec("CONSUMER_REVPAR", "Hotel Revenue per Available Room", "hotels", "average daily rate * occupancy", ("adr","occupancy"), "currency_per_room_night", lambda i: i["adr"]*i["occupancy"], allow_mixed_units=True),
    CalculationSpec("CONSUMER_ROOM_REVENUE", "Hotel Room Revenue Bridge", "hotels", "rooms * available days * occupancy * average daily rate", ("rooms","available_days","occupancy","adr"), "currency", lambda i: i["rooms"]*i["available_days"]*i["occupancy"]*i["adr"], allow_mixed_units=True, methodology="Room-revenue bridge; excludes food, events and other revenue"),
    CalculationSpec("CONSUMER_REVENUE_PER_PAIR", "Footwear Revenue per Pair", "footwear", "footwear revenue / pairs sold", ("revenue","pairs_sold"), "currency_per_pair", lambda i: _div(i["revenue"],i["pairs_sold"]), allow_mixed_units=True),
    CalculationSpec("CONSUMER_LEASE_ADJUSTED_LEVERAGE", "Lease-adjusted Net Debt to EBITDA", "consumer_risk", "(net debt + lease liabilities) / EBITDA", ("net_debt","lease_liabilities","ebitda"), "multiple", lambda i: _div(i["net_debt"]+i["lease_liabilities"],i["ebitda"]), allow_mixed_units=True),
    CalculationSpec("CONSUMER_EV_PER_KEY", "Hotel Enterprise Value per Key", "hotel_valuation", "enterprise value / rooms", ("enterprise_value","rooms"), "currency_per_room", lambda i: _div(i["enterprise_value"],i["rooms"]), allow_mixed_units=True),
    CalculationSpec("INDUSTRIAL_BOOK_TO_BILL", "Industrial Book to Bill", "industrial_orders", "order inflow / revenue", ("order_inflow","revenue"), "multiple", lambda i:_div(i["order_inflow"],i["revenue"])),
    CalculationSpec("INDUSTRIAL_ORDER_BOOK_REVENUE", "Order Book to Revenue", "industrial_orders", "order book / revenue", ("order_book","revenue"), "multiple", lambda i:_div(i["order_book"],i["revenue"])),
    CalculationSpec("INDUSTRIAL_ORDER_CONVERSION", "Order Conversion", "industrial_orders", "executed order value / opening order book", ("executed_order_value","opening_order_book"), "decimal", lambda i:_div(i["executed_order_value"],i["opening_order_book"])),
    CalculationSpec("INDUSTRIAL_CAPACITY_UTILIZATION", "Capacity Utilization", "industrial_capacity", "production / available capacity", ("production","capacity"), "decimal", lambda i:_div(i["production"],i["capacity"])),
    CalculationSpec("INDUSTRIAL_REVENUE_PER_CAPACITY", "Revenue per Capacity", "industrial_capacity", "revenue / average capacity", ("revenue","opening_capacity","closing_capacity"), "currency_per_capacity", lambda i:_div(i["revenue"],_avg(i,"opening_capacity","closing_capacity")), allow_mixed_units=True),
    CalculationSpec("INDUSTRIAL_COMMODITY_SPREAD", "Commodity Spread", "commodity_cycle", "realization per unit - cash input cost per unit", ("realization_per_unit","input_cost_per_unit"), "currency_per_unit", lambda i:i["realization_per_unit"]-i["input_cost_per_unit"], allow_mixed_units=True),
    CalculationSpec("INDUSTRIAL_EBITDA_PER_UNIT", "EBITDA per Unit", "industrial_unit_economics", "EBITDA / sales volume", ("ebitda","sales_volume"), "currency_per_unit", lambda i:_div(i["ebitda"],i["sales_volume"]), allow_mixed_units=True),
    CalculationSpec("INDUSTRIAL_EV_PER_CAPACITY", "Enterprise Value per Capacity", "industrial_valuation", "enterprise value / capacity", ("enterprise_value","capacity"), "currency_per_capacity", lambda i:_div(i["enterprise_value"],i["capacity"]), allow_mixed_units=True),
    CalculationSpec("INDUSTRIAL_NORMALIZED_EBITDA", "Cycle-normalized EBITDA", "commodity_cycle", "sales volume * normalized spread", ("sales_volume","normalized_spread"), "currency", lambda i:i["sales_volume"]*i["normalized_spread"], allow_mixed_units=True, methodology="Explicit normalized-cycle assumption; never a reported fact"),
    CalculationSpec("INDUSTRIAL_CASH_CONVERSION_CYCLE", "Industrial Cash Conversion Cycle", "working_capital", "receivable days + inventory days - payable days", ("receivable_days","inventory_days","payable_days"), "days", lambda i:i["receivable_days"]+i["inventory_days"]-i["payable_days"], allow_mixed_units=True),
    CalculationSpec("INDUSTRIAL_CAPEX_INTENSITY", "Industrial Capex Intensity", "industrial_capex", "capex / revenue", ("capex","revenue"), "decimal", lambda i:_div(i["capex"],i["revenue"])),
    CalculationSpec("INDUSTRIAL_INCREMENTAL_ROIC", "Incremental ROIC", "industrial_capex", "incremental NOPAT / expansion capital", ("incremental_nopat","expansion_capex"), "decimal", lambda i:_div(i["incremental_nopat"],i["expansion_capex"])),
    CalculationSpec("ENERGY_CAPACITY_UTILIZATION", "Energy Capacity Utilization", "energy_capacity", "production / available capacity", ("production","available_capacity"), "decimal", lambda i:_div(i["production"],i["available_capacity"])),
    CalculationSpec("ENERGY_PLANT_LOAD_FACTOR", "Plant Load Factor", "power_generation", "generation / (installed MW * available hours)", ("generation","installed_capacity_mw","available_hours"), "decimal", lambda i:_div(i["generation"],i["installed_capacity_mw"]*i["available_hours"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_CAPACITY_FACTOR", "Energy Capacity Factor", "renewable_generation", "generation / (installed MW * available hours)", ("generation","installed_capacity_mw","available_hours"), "decimal", lambda i:_div(i["generation"],i["installed_capacity_mw"]*i["available_hours"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_GENERATION_PER_MW", "Generation per MW", "power_generation", "generation / installed MW", ("generation","installed_capacity_mw"), "generation_per_mw", lambda i:_div(i["generation"],i["installed_capacity_mw"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_REVENUE_PER_MW", "Revenue per MW", "energy_unit_economics", "revenue / installed MW", ("revenue","installed_capacity_mw"), "currency_per_mw", lambda i:_div(i["revenue"],i["installed_capacity_mw"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_EBITDA_PER_MW", "EBITDA per MW", "energy_unit_economics", "EBITDA / installed MW", ("ebitda","installed_capacity_mw"), "currency_per_mw", lambda i:_div(i["ebitda"],i["installed_capacity_mw"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_CAPEX_PER_MW", "Capex per MW", "energy_project", "capex / added MW", ("capex","capacity_added_mw"), "currency_per_mw", lambda i:_div(i["capex"],i["capacity_added_mw"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_DEBT_PER_MW", "Net Debt per MW", "energy_risk", "net debt / installed MW", ("net_debt","installed_capacity_mw"), "currency_per_mw", lambda i:_div(i["net_debt"],i["installed_capacity_mw"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_FCF_PER_MW", "FCF per MW", "energy_cash_flow", "FCF / installed MW", ("fcf","installed_capacity_mw"), "currency_per_mw", lambda i:_div(i["fcf"],i["installed_capacity_mw"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_UNIT_SPREAD", "Energy Unit Spread", "energy_commodity", "realization per unit - cash cost per unit", ("realization_per_unit","cash_cost_per_unit"), "currency_per_unit", lambda i:i["realization_per_unit"]-i["cash_cost_per_unit"], allow_mixed_units=True),
    CalculationSpec("ENERGY_EBITDA_PER_UNIT", "Energy EBITDA per Unit", "energy_unit_economics", "EBITDA / production volume", ("ebitda","production_volume"), "currency_per_unit", lambda i:_div(i["ebitda"],i["production_volume"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_NORMALIZED_EBITDA", "Energy Normalized EBITDA", "energy_commodity", "production volume * normalized spread", ("production_volume","normalized_spread"), "currency", lambda i:i["production_volume"]*i["normalized_spread"], allow_mixed_units=True, methodology="Explicit normalized-cycle assumption; never a reported fact"),
    CalculationSpec("ENERGY_RESERVE_LIFE", "Reserve Life", "resource_economics", "economically recoverable reserves / annual production", ("reserves","annual_production"), "years", lambda i:_div(i["reserves"],i["annual_production"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_RESERVE_REPLACEMENT", "Reserve Replacement Ratio", "resource_economics", "reserve additions / depletion", ("reserve_additions","depletion"), "multiple", lambda i:_div(i["reserve_additions"],i["depletion"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_REGULATED_RETURN", "Regulated Return", "regulated_utility", "regulated asset base * allowed return", ("regulated_asset_base","allowed_return"), "currency", lambda i:i["regulated_asset_base"]*i["allowed_return"], allow_mixed_units=True),
    CalculationSpec("ENERGY_REGULATED_REVENUE", "Regulated Revenue Requirement", "regulated_utility", "allowed return + operating cost + depreciation", ("regulated_return","operating_cost","depreciation"), "currency", lambda i:i["regulated_return"]+i["operating_cost"]+i["depreciation"], allow_mixed_units=True),
    CalculationSpec("ENERGY_PROJECT_NPV", "Energy Project NPV", "energy_project", "annual FCF annuity - initial capex", ("initial_capex","annual_fcf","discount_rate","operating_life"), "currency", lambda i:i["annual_fcf"]*_div(1.0-(1.0+i["discount_rate"])**(-i["operating_life"]),i["discount_rate"])-i["initial_capex"], allow_mixed_units=True, methodology="Level annual FCF project cross-check; explicit detailed cash-flow model preferred"),
    CalculationSpec("ENERGY_EV_PER_MW", "Energy EV per MW", "energy_valuation", "enterprise value / installed MW", ("enterprise_value","installed_capacity_mw"), "currency_per_mw", lambda i:_div(i["enterprise_value"],i["installed_capacity_mw"]), allow_mixed_units=True),
    CalculationSpec("ENERGY_EV_PER_RESERVE", "Energy EV per Reserve", "resource_valuation", "enterprise value / economically recoverable reserves", ("enterprise_value","reserves"), "currency_per_reserve", lambda i:_div(i["enterprise_value"],i["reserves"]), allow_mixed_units=True),
)

REGISTRY = {spec.calculation_id: spec for spec in SPECS}


def get_spec(calculation_id: str) -> CalculationSpec | None:
    return REGISTRY.get(str(calculation_id or "").strip().upper())


def list_specs() -> list[dict]:
    return [spec.public() for spec in sorted(SPECS, key=lambda row: row.calculation_id)]
