import { useEffect, useState } from 'react';
import { Check, Loader2, RefreshCw, ShieldCheck, X } from 'lucide-react';
import { getInstitutionalResearchAdmin, refreshInstitutionalResearchLayer, reviewInstitutionalBrief } from '@/lib/institutionalHoldingsApi';

export default function InstitutionalResearchLayerAdmin() {
  const [data, setData] = useState(null); const [working, setWorking] = useState(''); const [message, setMessage] = useState('');
  const load = () => getInstitutionalResearchAdmin().then(setData).catch((error) => setMessage(error.message));
  useEffect(load, []);
  const review = async (id, status) => { setWorking(id); try { await reviewInstitutionalBrief(id, { status }); await load(); } catch (error) { setMessage(error.message); } finally { setWorking(''); } };
  return <section className="mt-7 rounded-2xl border border-cyan-400/20 bg-[#07151d] p-6 text-slate-100 shadow-xl"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.24em] text-cyan-300"><ShieldCheck className="h-4 w-4" /> Institutional Intelligence V3</div><h2 className="mt-2 text-2xl font-semibold">Research layer and analyst review</h2><p className="mt-2 text-sm text-slate-400">Refresh source evidence, then approve only the briefs suitable for clients.</p></div><button type="button" onClick={async () => { setWorking('refresh'); setMessage(''); try { const result = await refreshInstitutionalResearchLayer(); setMessage(`Refresh complete: ${result.classifications} classifications, ${result.external_filings} ownership/insider filings and ${result.briefs_created_or_refreshed} briefs.`); await load(); } catch (error) { setMessage(error.message); } finally { setWorking(''); } }} disabled={working === 'refresh'} className="inline-flex items-center justify-center gap-2 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950 disabled:opacity-40">{working === 'refresh' ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} Refresh research layer</button></div>
    {message ? <div className="mt-4 rounded-xl border border-white/10 bg-white/5 px-4 py-3 text-sm text-slate-300">{message}</div> : null}<div className="mt-5 grid gap-3 sm:grid-cols-3">{[['Classifications', data?.coverage?.classifications], ['Adjusted price rows', data?.coverage?.price_rows], ['13D/G + Form 4', data?.coverage?.external_filings]].map(([label, value]) => <div key={label} className="rounded-xl bg-white/5 p-4"><div className="text-[10px] uppercase tracking-wider text-slate-500">{label}</div><div className="mt-1 text-xl font-semibold">{value || 0}</div></div>)}</div>
    <div className="mt-6 space-y-3">{data?.briefs?.map((brief) => <article key={brief.id} className="rounded-xl border border-white/10 bg-white/[0.035] p-4"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-start"><div className="max-w-4xl"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-300">{brief.institutional_managers?.display_name} · {brief.institutional_filings?.report_date} · {brief.status.replace('_', ' ')}</div><h3 className="mt-2 font-semibold">{brief.headline}</h3><p className="mt-2 text-sm leading-6 text-slate-400">{brief.summary}</p></div><div className="flex gap-2"><button onClick={() => review(brief.id, 'approved')} disabled={working === brief.id} className="inline-flex items-center gap-1 rounded-lg bg-emerald-300/10 px-3 py-2 text-xs font-bold text-emerald-300"><Check className="h-4 w-4" /> Approve</button><button onClick={() => review(brief.id, 'rejected')} disabled={working === brief.id} className="inline-flex items-center gap-1 rounded-lg bg-rose-300/10 px-3 py-2 text-xs font-bold text-rose-300"><X className="h-4 w-4" /> Reject</button></div></div></article>)}</div></section>;
}

