import {getNseEquityMaster} from '../nseScreenerService.js';
import {resolveUpstoxAccessToken} from '../../providers/upstox.js';
export const ENERGY = [
 ['RELIANCE','Reliance Industries','Refining'],['ONGC','ONGC','Oil production'],['OIL','Oil India','Oil production'],['IOC','Indian Oil','Refining'],['BPCL','Bharat Petroleum','Refining'],['HINDPETRO','Hindustan Petroleum','Refining'],['GAIL','GAIL','Gas and LNG'],['PETRONET','Petronet LNG','Gas and LNG'],['NTPC','NTPC','Power'],['TATAPOWER','Tata Power','Power'],['JSWENERGY','JSW Energy','Power'],['ADANIPOWER','Adani Power','Power'],['TORNTPOWER','Torrent Power','Power'],['ADANIGREEN','Adani Green Energy','Renewables'],['NTPCGREEN','NTPC Green Energy','Renewables'],['SUZLON','Suzlon Energy','Renewables'],['NHPC','NHPC','Hydropower'],['SJVN','SJVN','Hydropower'],['POWERGRID','Power Grid','Transmission'],['COALINDIA','Coal India','Coal']
].map(([symbol,name,sector])=>({symbol,name,sector}));
export const EXPOSURES={'Refining':'Refinery incidents, cyclones and port disruptions','Oil production':'Offshore storms, flooding and geopolitical disruptions','Gas and LNG':'Terminal weather, shipping and pipeline incidents',Power:'Heatwaves, water shortages, fuel supply and outages',Renewables:'Wind, sunlight and extreme weather; manufacturer and operator exposures differ',Hydropower:'Rainfall, reservoirs and floods',Transmission:'Storms, fires and grid outages',Coal:'Mine flooding and transport disruption'};
const number=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))?Number(v):null;
const timestamp=v=>{if(v==null||v==='')return null;const d=new Date(/^\d+$/.test(String(v))?Number(v):v);return Number.isFinite(d.getTime())?d.toISOString():null;};
export function normalizeEnergyQuote(raw){if(!raw)return null;const price=number(raw.last_price),previous=number(raw.prev_close_price);return {price,changePercent:price!==null&&previous>0?(price/previous-1)*100:null,volume:number(raw.volume),open:number(raw.ohlc?.open),high:number(raw.ohlc?.high),low:number(raw.ohlc?.low),previousClose:previous,quoteTime:timestamp(raw.timestamp),lastTradeTime:timestamp(raw.last_trade_time)};}
export function normalizeEnergyNews(rows){return (Array.isArray(rows)?rows:[]).filter(x=>typeof x.article_link==='string'&&/^https:\/\//i.test(x.article_link)&&Number.isFinite(new Date(Number(x.published_time)).getTime())).map(x=>({heading:String(x.heading||'').slice(0,500),summary:String(x.summary||'').slice(0,2000),url:x.article_link,publishedAt:new Date(Number(x.published_time)).toISOString()})).filter(x=>x.heading).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));}
export function createEnergyReader({master=getNseEquityMaster,token=()=>String(process.env.UPSTOX_ANALYTICS_TOKEN||'').trim()||resolveUpstoxAccessToken().token,fetcher=fetch,now=Date.now}={}){
 let cache=null,expires=0,pending=null;
 return async()=>{if(cache&&now()<expires)return cache;if(pending)return pending;
 pending=(async()=>{const generatedAt=new Date(now()).toISOString();const base=ENERGY.map(c=>({...c,exposure:EXPOSURES[c.sector],quote:null,news:[]}));const credential=token();if(!credential)return {companies:base,generatedAt,quoteError:'Upstox token is not configured.',newsError:'Upstox token is not configured.'};
 const {items}=await master();const mapped=base.map(c=>({...c,key:items.find(i=>i.symbol===c.symbol)?.instrumentKey}));const keys=mapped.map(c=>c.key).filter(Boolean).join(',');if(!keys)throw new Error('Energy instruments unavailable');
 async function get(path){const r=await fetcher('https://api.upstox.com'+path,{headers:{Accept:'application/json',Authorization:`Bearer ${credential}`},redirect:'error',signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error(`Provider HTTP ${r.status}`);const body=await r.json();if(body.status!=='success'||!body.data)throw new Error('Invalid provider response');return body;}
 const [quotes,news]=await Promise.allSettled([get('/v3/market-quote/quotes?instrument_key='+encodeURIComponent(keys)),get('/v2/news?category=instrument_keys&instrument_keys='+encodeURIComponent(keys)+'&page_size=100&page_number=1')]);
 return {generatedAt,quoteError:quotes.status==='rejected'?'Quotes are temporarily unavailable.':null,newsError:news.status==='rejected'?'News is temporarily unavailable.':null,newsTruncated:news.status==='fulfilled'&&Number(news.value.metadata?.page?.total_pages)>1,companies:mapped.map(({key,...c})=>({...c,mapped:!!key,quote:quotes.status==='fulfilled'?normalizeEnergyQuote(quotes.value.data['NSE_EQ:'+c.symbol]||quotes.value.data[key]):null,news:news.status==='fulfilled'?normalizeEnergyNews(news.value.data[key]):[]}))};
 })();try{cache=await pending;expires=now()+((cache.quoteError||cache.newsError)?60000:300000);return cache;}finally{pending=null;}};
}
export const readEnergy=createEnergyReader();
