import { useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Database, Globe2, Search, ShieldCheck, X } from 'lucide-react';
import AskAgiBar from '@/components/Home/AskAgiBar';
import NewsletterSection from '@/components/Home/NewsletterSection';
import { usePeOverview } from '@/hooks/usePeIntelligence';
import { InvestorIntelligence, OpportunityIntelligence } from './PePhaseTwo';
import PePhaseThree from './PePhaseThree';
import './peEditorial.css';

const SCOPES=[['core','Core Private Markets'],['all','All Observed Transactions'],['public','Public Market Transactions']];
const TYPES=[['overview','Overview'],['deals','Deal Activity'],['opportunities','Opportunities'],['investors','Investors'],['intelligence','Intelligence'],['explorer','Data Explorer']];
const money=(v)=>{const n=Number(v);if(!Number.isFinite(n))return'Not disclosed';return n>=1000?'₹'+(n/1000).toFixed(1)+'B':'₹'+n.toLocaleString('en-IN')+'M'};
const date=(v)=>v?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'Date unavailable';
function Empty(){return <div className="pm-empty"><Database/><b>Dataset awaiting import</b><p>No traceable records match these filters. AGI does not substitute placeholder data.</p></div>}
function Table({rows=[],open,compact}){if(!rows.length)return <Empty/>;return <div className="pm-table-wrap"><table className="pm-table"><thead><tr><th>Date</th><th>Company</th><th>Transaction</th><th>Value</th><th>Stake</th><th>Location</th><th>Evidence</th></tr></thead><tbody>{rows.slice(0,compact?8:100).map(r=><tr key={r.id} onClick={()=>open(r)}><td>{date(r.dealDate)}</td><td><b>{r.company}</b><small>{r.businessDescription||'Description unavailable'}</small></td><td><span className={'pm-type '+r.marketDomain}>{r.transactionType}</span></td><td>{money(r.dealSizeInrMn)}</td><td>{r.stakePercent==null?'—':r.stakePercent+'%'}</td><td>{r.location||'—'}</td><td className="pm-link">View record</td></tr>)}</tbody></table></div>}
function Bars({rows=[]}){const max=Math.max(...rows.map(x=>x.count),1);if(!rows.length)return <Empty/>;return <div className="pm-bars">{rows.map(x=><div key={x.label}><p><span>{x.label}</span><b>{x.count}</b></p><i><em style={{width:(x.count/max*100)+'%'}}/></i><small>{money(x.valueInrMn)}</small></div>)}</div>}
function Opps({data={}}){return <div className="pm-opps">{[['Sale / divestment',data.saleDivestment],['LBO candidates',data.lbo],['Distressed situations',data.distressed]].map(([k,v])=><article key={k}><Globe2/><small>Global Opportunity Intelligence</small><strong>{v??'—'}</strong><h3>{k}</h3><p>Observed records in a separate global research universe.</p></article>)}</div>}
function Drawer({deal,close}){if(!deal)return null;return <div className="pm-backdrop" onMouseDown={close}><aside className="pm-drawer" onMouseDown={e=>e.stopPropagation()}><button onClick={close}><X/></button><label>Transaction record</label><h2>{deal.company}</h2><p>{deal.businessDescription||'No description supplied.'}</p><dl>{[['Deal date',date(deal.dealDate)],['Deal value',money(deal.dealSizeInrMn)],['Transaction',deal.transactionType],['Stake',deal.stakePercent==null?'Not disclosed':deal.stakePercent+'%'],['Pre-money',money(deal.preMoneyValuationInrMn)],['Post-money',money(deal.postMoneyValuationInrMn)],['Location',deal.location||'Not supplied'],['Universe',deal.marketDomain==='core'?'Core Private Markets':'Public Market Transaction']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><section><ShieldCheck/><p><b>Traceable evidence</b><br/>{deal.sourceFile||'Source file'} · {deal.sourceSheet||'Source sheet'} · row {deal.sourceRow||'—'}</p></section><small>Blank fields are not estimated.</small></aside></div>}
export default function PeEditorialHome(){
 const[scope,setScope]=useState('core'),[tab,setTab]=useState('overview'),[search,setSearch]=useState(''),[deal,setDeal]=useState(null);
 const{data,loading,error}=usePeOverview({scope,search,limit:500});const m=data?.metrics||{};
 const heading=<header className="pm-section-head"><div><label>India Deal Market</label><h2>Deal Activity</h2></div><span>{m.dealCount||0} records</span></header>;
 return <div className="pe-editorial"><Helmet><title>Private Markets Intelligence | Agarwal Global Investments</title></Helmet><header className="pm-hero"><div><label>AGI Private Markets</label><h1>Private capital,<br/>made legible.</h1><p>India deal intelligence and global opportunity research, separated by universe and anchored to source evidence.</p></div><aside><small>Dataset status</small><b>{data?.provenance?.effectiveDate?'Through '+date(data.provenance.effectiveDate):'Awaiting verified records'}</b><p>{data?.provenance?.recordCount||0} traceable transactions · {data?.provenance?.sourceCount||0} sources</p></aside><section><AskAgiBar placeholder="Ask about observed deals, values or disclosed valuations..."/></section></header>
 <main className="pe-editorial-inner"><nav className="pm-tabs">{TYPES.map(([id,k])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{k}</button>)}</nav><div className="pm-filters"><div>{SCOPES.map(([id,k])=><button className={scope===id?'active':''} onClick={()=>setScope(id)} key={id}>{k}</button>)}</div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company, location or type"/></label></div><p className="pm-note"><ShieldCheck/> Metrics recalculate inside the selected universe. India deals and global opportunities are never combined.</p>
 {error&&<div className="pm-error">{error}</div>}{loading?<div className="pm-loading">Loading traceable records...</div>:<>{tab==='overview'&&<><section className="pm-kpis">{[['Observed transaction value',money(m.totalValueInrMn),(m.valueCoverage||0)+'% value coverage'],['Transactions',m.dealCount||0,(m.companies||0)+' companies'],['Median disclosed value',money(m.medianValueInrMn),'Disclosed values only'],['Stake disclosure',(m.stakeCoverage||0)+'%',(m.stakeDisclosed||0)+' records']].map(([k,v,d],i)=><article className={i===0?'accent':''} key={k}><small>{k}</small><strong>{v}</strong><p>{d}</p></article>)}</section><section className="pm-split"><article className="pm-panel"><header><label>India Deal Market</label><h2>Activity by transaction type</h2></header><Bars rows={data?.breakdown}/></article><article className="pm-view"><label>AGI View</label><h2>{data?.view?.headline}</h2><p>{data?.view?.interpretation}</p><small><ShieldCheck/> Based on {m.dealCount||0} observed records</small></article></section><section className="pm-section">{heading}<Table rows={data?.deals} open={setDeal} compact/></section><section className="pm-section"><header className="pm-section-head"><div><label>Separate universe</label><h2>Global Opportunity Intelligence</h2></div></header><Opps data={data?.opportunitySummary}/></section></>}{tab==='deals'&&<section className="pm-section">{heading}<Table rows={data?.deals} open={setDeal}/></section>}{tab==='opportunities'&&<section className="pm-section"><header className="pm-section-head"><div><label>Global universe</label><h2>Opportunity Intelligence</h2></div></header><OpportunityIntelligence/></section>}{tab==='investors'&&<section className="pm-section"><InvestorIntelligence/></section>}{tab==='intelligence'&&<section className="pm-section"><PePhaseThree/></section>}{tab==='explorer'&&<section className="pm-section">{heading}<Table rows={data?.deals} open={setDeal}/><p className="pm-notice"><Database/> Every record retains source file, sheet, row and ingestion run.</p></section>}</>}</main><NewsletterSection variant="minimal" initialSelected="agi_macro"/><Drawer deal={deal} close={()=>setDeal(null)}/></div>
}
