import { useEffect,useMemo,useState } from 'react';
import { Helmet } from 'react-helmet-async';
import { Activity,ArrowLeft,Building2,Database,FileSearch,Globe2,MapPin,Search,ShieldCheck,TrendingUp,X } from 'lucide-react';
import AskAgiBar from '@/components/Home/AskAgiBar';
import NewsletterSection from '@/components/Home/NewsletterSection';
import { usePeOverview } from '@/hooks/usePeIntelligence';
import API_ORIGIN from '@/config';
import './peHybrid.css';
const BASE=API_ORIGIN||'';
const get=async path=>{const r=await fetch(BASE+path);if(!r.ok)throw Error('API '+r.status);return r.json()};
const money=v=>v==null?'Not disclosed':Number(v)>=1000?'₹'+(Number(v)/1000).toFixed(1)+'B':'₹'+Number(v).toLocaleString('en-IN')+'M';
const date=v=>v?new Intl.DateTimeFormat('en-IN',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(v)):'—';
const show=v=>v==null||v===''||v==='-'?'Not disclosed':String(v);
const TABS=[['pulse','Today'],['deals','Deal Tape'],['opportunities','Opportunities'],['investors','Investor Network'],['valuations','Valuations'],['explorer','Data Explorer']];

function EvidenceDrawer({record,close}){
 if(!record)return null;const facts=record.kind==='deal'?[['Deal date',date(record.dealDate)],['Deal value',money(record.dealSizeInrMn)],['Stake',record.stakePercent==null?'Not disclosed':record.stakePercent+'%'],['Transaction',record.transactionType],['Pre-money',money(record.preMoneyValuationInrMn)],['Post-money',money(record.postMoneyValuationInrMn)],['Location',record.location||'Not supplied'],['Universe',record.marketDomain==='core'?'Core Private Markets':'Public transaction']]:Object.entries(record.observedMetrics||{});
 return <div className="ph-backdrop" onMouseDown={close}><aside className="ph-drawer" onMouseDown={e=>e.stopPropagation()}><button onClick={close}><X/></button><label>Evidence dossier</label><h2>{record.company||record.companyName}</h2><p>{record.businessDescription||'Structured evidence from the licensed source workbook.'}</p><dl>{facts.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{show(v)}</dd></div>)}</dl><section><ShieldCheck/><div><b>Traceable source</b><p>{record.sourceFile||'Private Markets workbook'} · {record.sourceSheet||'Canonical opportunity record'} · row {record.sourceRow||'linked'}</p></div></section><small>Observed values are shown as supplied or deterministically normalized. Missing values are never estimated.</small></aside></div>
}
function DealMap({rows,open}){
 const values=rows.map(r=>Number(r.dealSizeInrMn)).filter(Number.isFinite),max=Math.max(...values,1),minDate=Math.min(...rows.map(r=>new Date(r.dealDate).getTime()).filter(Number.isFinite)),maxDate=Math.max(...rows.map(r=>new Date(r.dealDate).getTime()).filter(Number.isFinite));
 return <div className="ph-map"><div className="ph-map-y"><span>Large</span><span>Deal value</span><span>Small</span></div><div className="ph-map-plot">{rows.filter(r=>r.dealSizeInrMn!=null).map((r,i)=>{const time=new Date(r.dealDate).getTime(),x=maxDate===minDate?50:((time-minDate)/(maxDate-minDate))*92+4,y=94-Math.sqrt(Number(r.dealSizeInrMn)/max)*88,size=Math.max(9,Math.min(34,8+Number(r.stakePercent||5)/3));return <button key={r.id} title={r.company} onClick={()=>open(r)} className={'ph-dot '+r.marketDomain} style={{left:x+'%',top:y+'%',width:size,height:size}}><span>{r.company}</span></button>})}<div className="ph-map-grid"/><footer><span>{date(minDate)}</span><b>Transaction date</b><span>{date(maxDate)}</span></footer></div></div>
}
function DealTape({rows,open,full=false}){
 if(!rows.length)return <div className="ph-empty"><Database/><b>No records in this universe</b></div>;
 return <div className="ph-tape">{rows.slice(0,full?100:12).map(r=><button key={r.id} onClick={()=>open(r)}><time>{date(r.dealDate)}</time><span className={'ph-deal-type '+r.marketDomain}>{r.transactionType}</span><div><strong>{r.company}</strong><small>{r.businessDescription||r.location||'No description supplied'}</small></div><b>{money(r.dealSizeInrMn)}</b><em>{r.stakePercent==null?'Stake undisclosed':r.stakePercent+'% stake'}</em></button>)}</div>
}
function Opportunities({open}){
 const[type,setType]=useState('lbo'),[rows,setRows]=useState([]),[search,setSearch]=useState('');
 useEffect(()=>{get('/api/pe/opportunities?type='+type+'&search='+encodeURIComponent(search)).then(d=>setRows(d.opportunities||[]))},[type,search]);
 const fields={lbo:[['Debt / EBITDA','Total Debt/EBITDA [LTM]'],['Debt / Capital','Total Debt/Capital % [Latest Annual]'],['EBITDA growth','[EBITDA Growth >5%, 5Y] Left Side']],distressed:[['Debt / EBITDA','Total Debt/EBITDA [LTM]'],['Interest coverage','(EBITDA-CAPEX) / Interest Exp. [LTM]'],['Credit rating','S&P Entity Credit Rating - Issuer Credit Rating - Local Currency LT [Latest] (Rating)']],sale_divestment:[['Industry','Primary Industry'],['Recent development','Key Developments by Type -  [Last 3 Months]'],['Current investors','Current and Pending Investors']]}[type];
 return <div><div className="ph-workbench-head"><div>{[['lbo','LBO Underwriting'],['distressed','Credit Monitor'],['sale_divestment','Origination Pipeline']].map(([id,label])=><button className={type===id?'active':''} onClick={()=>setType(id)} key={id}>{label}</button>)}</div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search situations"/></label></div><div className="ph-opportunity-summary"><strong>{rows.length}</strong><span>observed situations</span><p><ShieldCheck/>Rule-based evidence, not an AGI recommendation.</p></div><div className="ph-opportunity-table"><header><span>Company</span>{fields.map(([label])=><span key={label}>{label}</span>)}<span>Coverage</span></header>{rows.map(r=><button key={r.id} onClick={()=>open({...r,kind:'opportunity'})}><strong>{r.companyName}</strong>{fields.map(([,key])=><span key={key}>{show(r.observedMetrics?.[key])}</span>)}<em className={r.coverage>=.7?'good':''}>{Math.round(r.coverage*100)}%</em></button>)}</div></div>
}
function Investors(){
 const[rows,setRows]=useState([]),[search,setSearch]=useState(''),[selected,setSelected]=useState(null);
 useEffect(()=>{get('/api/pe/investors?search='+encodeURIComponent(search)).then(d=>setRows(d.investors||[]))},[search]);
 if(selected)return <div className="ph-investor-profile"><button onClick={()=>setSelected(null)}><ArrowLeft/>Network</button><header><div><label>Observed investor</label><h2>{selected.name}</h2><p><MapPin/>{show(selected.geography)}</p></div><strong>{selected.transactions?.length||0}<small>historical transactions</small></strong></header><div className="ph-history">{selected.transactions?.map(t=><article key={t.id}><time>{date(t.observedDate)}</time><i/><div><b>{t.companyName}</b><p>{t.transactionDescription}</p></div></article>)}</div><p className="ph-caveat"><ShieldCheck/>Historical activity does not imply current investor interest.</p></div>;
 return <div><div className="ph-network-head"><div><label>Global Investor Network</label><h2>{rows.length} financial buyers</h2></div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search investor or geography"/></label></div><div className="ph-network"><div className="ph-network-axis">Observed investor activity</div>{rows.map((r,i)=><button key={r.id} style={{'--activity':Math.min(100,20+r.recentTransactionCount*12)+'%'}} onClick={()=>get('/api/pe/investors/'+r.id).then(setSelected)}><span><Building2/><b>{r.name}</b><small>{show(r.geography)}</small></span><i/><strong>{r.recentTransactionCount}<small>recent</small></strong></button>)}</div></div>
}
function Valuations(){
 const[data,setData]=useState(null);useEffect(()=>{get('/api/pe/intelligence').then(setData)},[]);
 if(!data)return <div className="ph-empty">Loading valuation evidence...</div>;
 return <div><div className="ph-valuation-hero"><div><label>Disclosure coverage</label><strong>{data.valuation.coverage}%</strong></div><p>Valuation analysis uses disclosed pre-money and post-money values only. It does not infer values for blank records.</p></div><div className="ph-valuation-ledger">{data.valuation.rows.map(r=><article key={r.id}><div><small>{r.transactionType}</small><h3>{r.company}</h3><time>{date(r.date)}</time></div><dl><div><dt>Deal</dt><dd>{money(r.dealValue)}</dd></div><div><dt>Pre-money</dt><dd>{money(r.preMoney)}</dd></div><div><dt>Post-money</dt><dd>{money(r.postMoney)}</dd></div></dl></article>)}</div></div>
}
export default function PeHybridDesk(){
 const[tab,setTab]=useState('pulse'),[scope,setScope]=useState('core'),[search,setSearch]=useState(''),[drawer,setDrawer]=useState(null);
 const{data,loading}=usePeOverview({scope,search,limit:500});const rows=data?.deals||[],m=data?.metrics||{};
 const notable=useMemo(()=>[...rows].sort((a,b)=>(b.dealSizeInrMn||0)-(a.dealSizeInrMn||0)).slice(0,4),[rows]);
 return <div className="ph"><Helmet><title>Private Markets Intelligence | Agarwal Global Investments</title></Helmet><header className="ph-hero"><nav><span>AGI / PRIVATE MARKETS</span><b>INDIA DEAL MARKET</b><b>GLOBAL OPPORTUNITY INTELLIGENCE</b><b>GLOBAL INVESTOR NETWORK</b></nav><div className="ph-hero-grid"><div><label>Institutional intelligence</label><h1>The private markets,<br/><i>in full view.</i></h1><p>Transaction evidence, opportunity underwriting and observed investor activity, connected without collapsing distinct universes.</p></div><aside><span>Evidence through</span><strong>{date(data?.provenance?.effectiveDate)}</strong><p>{data?.provenance?.recordCount||0} transactions · {data?.provenance?.sourceCount||0} source files</p></aside></div><AskAgiBar placeholder="Ask AGI about a deal, valuation, opportunity or investor history..."/></header>
 <main className="ph-shell"><nav className="ph-tabs">{TABS.map(([id,label])=><button className={tab===id?'active':''} onClick={()=>setTab(id)} key={id}>{label}</button>)}</nav>
 {(tab==='pulse'||tab==='deals'||tab==='explorer')&&<div className="ph-filters"><div>{[['core','Core Private Markets'],['all','All Observed'],['public','IPO + Block / Bulk']].map(([id,label])=><button className={scope===id?'active':''} onClick={()=>setScope(id)} key={id}>{label}</button>)}</div><label><Search/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search company, type or location"/></label></div>}
 {loading?<div className="ph-empty">Loading evidence...</div>:<>{tab==='pulse'&&<><section className="ph-brief"><div><label>PRIVATE MARKETS TODAY</label><h2>{data?.view?.headline}</h2><p>{data?.view?.interpretation}</p><small><Activity/>Calculated from {m.dealCount||0} observed records in the selected universe.</small></div><aside>{notable.map((r,i)=><button onClick={()=>setDrawer(r)} key={r.id}><span>0{i+1}</span><b>{r.company}</b><strong>{money(r.dealSizeInrMn)}</strong></button>)}</aside></section><section className="ph-metrics">{[['Observed value',money(m.totalValueInrMn)],['Transactions',m.dealCount||0],['Median ticket',money(m.medianValueInrMn)],['Value coverage',(m.valueCoverage||0)+'%'],['Stake coverage',(m.stakeCoverage||0)+'%']].map(([k,v])=><article key={k}><small>{k}</small><strong>{v}</strong></article>)}</section><section className="ph-section"><header><div><label>MARKET STRUCTURE</label><h2>Every dot is a transaction.</h2></div><p>Position shows date and disclosed value. Size reflects disclosed stake.</p></header><DealMap rows={rows} open={setDrawer}/></section><section className="ph-section"><header><div><label>DEAL TAPE</label><h2>Latest observed transactions</h2></div><button onClick={()=>setTab('deals')}>Open full tape</button></header><DealTape rows={rows} open={setDrawer}/></section></>}
 {tab==='deals'&&<section className="ph-section"><header><div><label>INDIA DEAL TAPE</label><h2>{m.dealCount||0} observed transactions</h2></div></header><DealTape rows={rows} open={setDrawer} full/></section>}
 {tab==='opportunities'&&<section className="ph-section"><header><div><label>GLOBAL OPPORTUNITY INTELLIGENCE</label><h2>Underwriting workbench</h2></div></header><Opportunities open={setDrawer}/></section>}
 {tab==='investors'&&<section className="ph-section"><Investors/></section>}
 {tab==='valuations'&&<section className="ph-section"><header><div><label>VALUATION INTELLIGENCE</label><h2>What the evidence discloses.</h2></div></header><Valuations/></section>}
 {tab==='explorer'&&<section className="ph-section"><header><div><label>RAW EVIDENCE</label><h2>Data Explorer</h2></div><p>Click any row to inspect source provenance.</p></header><DealTape rows={rows} open={setDrawer} full/></section>}</>}
 </main><NewsletterSection variant="minimal" initialSelected="agi_macro"/><EvidenceDrawer record={drawer} close={()=>setDrawer(null)}/></div>
}
