import {formatModelValue as fmt} from '@/lib/financialModelEngine';
export function ModelHistory({model,years,overrides,update,calc}){
 return <><p className="fm-table-footnote">Enter reported actuals and their source/reporting date. Blank means not supplied. Actuals are comparison data; update opening balances and forecast drivers separately.</p><div className="fm-table-scroll"><table className="fm-table"><thead><tr><th>Metric · ₹ crore</th>{Array.from({length:8},(_,i)=><th key={i}>FY{years[0]+i-3}{i<3?'A':'E'}</th>)}<th>Source / reporting date</th></tr></thead><tbody>{(model.history||[]).map(row=><tr key={row.row}><th>{row.label}</th>{row.refs.map((ref,i)=><td key={ref}><input className="fm-history-input" type="number" step="any" aria-label={`${row.label} FY${years[0]+i-3} actual`} value={overrides[model.name]?.[ref]??''} onChange={e=>update([ref],e.target.value===''?null:Number(e.target.value))}/></td>)}{row.forecastRefs.map(ref=>{const r=calc.safe(model.name,ref);return <td key={ref}>{r.error?'Unavailable':fmt(r.value)}</td>;})}<td><input className="fm-history-source" aria-label={`${row.label} source and reporting date`} maxLength={500} value={overrides[model.name]?.[row.sourceRef]??''} onChange={e=>update([row.sourceRef],e.target.value)}/></td></tr>)}</tbody></table></div></>;
}
export function ModelSensitivities({model,calc,blocked}){
 if(blocked)return <p className="fm-error">Resolve model checks before using sensitivity valuations.</p>;
 if(!model.sensitivities?.length)return <p className="fm-table-footnote">Use the three scenario cases for this model. FCFF sensitivity grids apply to operating companies.</p>;
 const value=(ref,format)=>{const r=calc.safe(model.name,ref);return r.error?'Unavailable':fmt(r.value,format);};
 return <>{model.sensitivities.map((grid,i)=><div className="fm-table-scroll" key={grid.label}><h3 className="fm-sensitivity-title">{grid.label}</h3><table className="fm-table"><thead><tr><th>₹ crore</th>{grid.header.map(ref=><th key={ref}>{value(ref,i===1?'0.0"x"':'0.0%')}</th>)}</tr></thead><tbody>{grid.values.map((refs,r)=><tr key={r}><th>{value(grid.side[r],i===0?'0.0%':'#,##0.0')}</th>{refs.map(ref=><td key={ref}>{value(ref,'#,##0.0')}</td>)}</tr>)}</tbody></table></div>)}<p className="fm-table-footnote">Formula-driven sensitivities hold other assumptions constant. Revenue/margin grid shows first-year EBITDA, not DCF value. “n/a” marks an invalid terminal assumption.</p></>;
}
