import {useEffect,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend,ReferenceLine} from 'recharts';
import API_ORIGIN from '@/config';
import {ENGINE_PLAIN} from '@/lib/liveAlphaDashboardModel';
const day=d=>new Date(new Date(d).getTime()+19800000).toISOString().slice(0,10);
const stamp=v=>v?`${new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',day:'2-digit',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',hour12:false})} IST`:'Not recorded';
const num=v=>v!=null&&Number.isFinite(Number(v))?Number(v).toLocaleString('en-IN',{maximumFractionDigits:2}):'—';
const pct=v=>v==null?'—':`${Number(v)>0?'+':''}${num(v)}%`;
const horizons=[['15m','15 trading minutes'],['1h','1 trading hour'],['close','Session close'],['1d','1 trading day'],['5d','5 trading days'],['20d','20 trading days'],['exit','Signal changed']];
async function read(url,signal){const r=await fetch(`${API_ORIGIN}/api/market/live-alpha/${url}`,{signal});const body=await r.json();if(!r.ok)throw new Error(body.error||'History is temporarily unavailable.');return body;}
function Stat({label,value}){return <div className="la-metric"><span>{label}</span><strong>{value}</strong></div>;}
function HistoryDetail({id,onClose}){
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{const ac=new AbortController();setData(null);setError('');read(`history/${encodeURIComponent(id)}`,ac.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>ac.abort();},[id]);
 const r=data?.record,historical=r?.kind==='historical_engine_record';
 const rows=data?.chart?.map(p=>({...p,time:Date.parse(p.at)}))||[];
 return <section className="la-panel la-history-detail" aria-label="Signal follow-up detail"><div className="la-section-head la-history-heading"><div><h2>{r?.symbol||'Signal detail'} · Performance since {historical?'evaluation':'publication'}</h2><p>{r?stamp(r.published_at||r.signal_at):'Fetching recorded history and available daily closes…'}</p></div><button onClick={onClose}>Close detail</button></div>
 {error&&<p role="alert" className="la-error">{error}</p>}
 {data&&<><p className="la-note">{historical?'Historical engine record · Publication time not verified.':'Publication is the time this signal was first saved for public availability; it is not a customer’s execution time.'} Original direction: <b>{r.direction}</b> · Current state: {r.signal_status}.</p>
 <div className="la-history-stats"><Stat label="Original reference price" value={`₹${num(r.reference_price)}`}/><Stat label="Latest available price" value={`₹${num(data.latest_price)}`}/><Stat label="Stock price change" value={pct(data.stock_return_pct)}/><Stat label="Direction-adjusted change · before costs" value={pct(data.directional_return_pct)}/></div>
 <p className="la-note">Original quote: {stamp(r.quote_at)} · Latest observation: {stamp(data.latest_price_at)}. {data.reference_check.status==='unverified'?'Original reference could not be reconciled; percentage returns are withheld.':''}</p>
 <div className="la-history-chart"><ResponsiveContainer width="100%" height={330}><LineChart data={rows} margin={{top:20,right:28,bottom:12,left:8}}><CartesianGrid strokeDasharray="3 3" stroke="#e4ebef"/><XAxis dataKey="time" type="number" domain={['dataMin','dataMax']} tickFormatter={v=>new Date(v).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short'})} minTickGap={45}/><YAxis tickFormatter={v=>`${num(v)}%`} width={65}/><Tooltip labelFormatter={v=>stamp(Number(v))} formatter={(v,name)=>[pct(v),name]}/><Legend/><ReferenceLine y={0} stroke="#a3b3bc"/>{rows.length>0&&<ReferenceLine x={rows[0].time} stroke="#b08a4f" label={historical?'Evaluation':'Published'}/>}<Line type="linear" dataKey="stock_return_pct" name="Stock price change" stroke="#147c78" strokeWidth={2} dot={rows.length<8} connectNulls={false} isAnimationActive={false}/><Line type="linear" dataKey="benchmark_return_pct" name="Nifty 50 price change" stroke="#7188b8" strokeWidth={1.5} dot={false} connectNulls={false} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>
 <p className="la-note">Best observed stock change: {pct(data.best_observed_change_pct)} · Worst: {pct(data.worst_observed_change_pct)}. {data.methodology}</p>
 {!historical&&<><div className="la-section-head"><h3>Fixed follow-up windows</h3><p>Price movement and hypothetical holding-period returns are separate. A negative call’s directional result assumes a short; buying that stock earns its ordinary stock return.</p></div><div className="la-tablewrap"><table className="la-table"><thead><tr>{['Window','Due / observed','Status','Stock change','Direction-adjusted','Nifty change','Hypothetical net return'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{(r.followups||[]).sort((a,b)=>Date.parse(a.due_at)-Date.parse(b.due_at)).map(f=><tr key={f.horizon}><td>{horizons.find(x=>x[0]===f.horizon)?.[1]}</td><td>{stamp(f.due_at)}<small>{stamp(f.observed_at)}</small></td><td>{f.status}<small>{f.reason}</small></td><td>{pct(f.stock_return_pct)}</td><td>{pct(f.directional_return_pct)}</td><td>{pct(f.benchmark_return_pct)}</td><td>{pct(f.simulated_net_return_pct)}</td></tr>)}</tbody></table></div><p className="la-note">Simulation uses the first eligible recorded bid/ask within five minutes after publication and a separately eligible exit quote. Each row is a hypothetical holding period, not a strategy trade or portfolio. {data.cost_model}. Overnight short availability is not modelled. Conflicting calls have no directional simulation. Session-close price tracking waits for the published daily candle; simulated close exits use the last minute’s eligible quote.</p></>}
 <div className="la-detail-grid la-history-events"><div><h3>Original signal components</h3>{(r.components||[]).map(c=><p key={c.engine}>{ENGINE_PLAIN[c.engine]?.label||c.engine} · {c.direction} · {c.classification?.replaceAll('_',' ')}</p>)}</div><div><h3>Follow-up log</h3>{!(r.events||[]).length?<p>{historical?'Event history was not captured for this old snapshot.':'No material change recorded yet.'}</p>:(r.events||[]).sort((a,b)=>Date.parse(a.event_at)-Date.parse(b.event_at)).map(e=><p key={e.id}>{stamp(e.event_at)} · {e.kind.replaceAll('_',' ')}{e.details?.score!=null?` · score ${num(e.details.score)}`:''}</p>)}</div></div></>}
 </section>;
}
export default function LiveAlphaHistory({latestSignalAt}){
 const today=day(new Date()),initial=latestSignalAt?day(latestSignalAt):today;
 const [kind,setKind]=useState('published'),[from,setFrom]=useState(day(Date.now()-30*86400000)),[to,setTo]=useState(today),[historicalDate,setHistoricalDate]=useState(initial),[symbol,setSymbol]=useState(''),[direction,setDirection]=useState(''),[horizon,setHorizon]=useState('1d'),[page,setPage]=useState(0),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState(null);
 const [data,setData]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 useEffect(()=>{const ac=new AbortController();setLoading(true);setError('');setData(null);const query=new URLSearchParams({kind,from,to,date:historicalDate,symbol,direction,horizon,page:String(page)});const timer=setTimeout(()=>read(`history?${query}`,ac.signal).then(setData).catch(e=>{if(e.name!=='AbortError')setError(e.message);}).finally(()=>{if(!ac.signal.aborted)setLoading(false);}),250);return()=>{clearTimeout(timer);ac.abort();};},[kind,from,to,historicalDate,symbol,direction,horizon,page,refresh]);
 const change=setter=>e=>{setter(e.target.value);setPage(0);setSelected(null);};const summary=data?.summary||{},historical=kind==='historical',total=Number(summary.published||0);
 return <><section className="la-panel"><div className="la-section-head"><h2>Signal history & follow-up</h2><p>Choose a publication date, see what the system said then, and follow the stock’s subsequent performance.</p></div>
 <div className="la-toolbar"><label>Records<select aria-label="History record type" value={kind} onChange={change(setKind)}><option value="published">Published calls · new archive</option><option value="historical">Earlier engine snapshots</option></select></label>{historical?<label>Evaluation date<input aria-label="Evaluation date" type="date" value={historicalDate} max={today} onChange={change(setHistoricalDate)}/></label>:<><label>From<input aria-label="Published from" type="date" value={from} max={today} onChange={change(setFrom)}/></label><label>Through<input aria-label="Published through" type="date" value={to} max={today} onChange={change(setTo)}/></label></>}<label>Stock<input aria-label="History stock" value={symbol} placeholder="e.g. RELIANCE" maxLength={30} onChange={change(setSymbol)}/></label><label>Direction<select aria-label="History direction" value={direction} onChange={change(setDirection)}><option value="">All directions</option><option value="positive">Positive</option><option value="negative">Negative</option><option value="conflicting">Conflicting</option></select></label>{!historical&&<label>Follow-up<select aria-label="Follow-up horizon" value={horizon} onChange={change(setHorizon)}>{horizons.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>}<button onClick={()=>setRefresh(x=>x+1)}>Refresh history</button></div>
 {error&&<p role="alert" className="la-error">{error}</p>}{loading&&<p className="la-note" role="status">Loading archived records…</p>}
 {data&&<><p className="la-note">{data.note}</p>{!historical&&<div className="la-history-stats"><Stat label="Matching publications" value={num(total)}/><Stat label="Completed / pending / missing" value={`${num(summary.completed)} / ${num(summary.pending)} / ${num(summary.missing)}`}/><Stat label="Mean stock change · selected window" value={pct(summary.mean_stock_return_pct)}/><Stat label="Positive directional outcomes" value={pct(summary.positive_outcome_pct)}/></div>}
 <div className="la-tablewrap"><table className="la-table"><thead><tr>{['Stock / direction',historical?'Engine evaluation':'Published · IST','Reference price ₹','Latest observed price ₹','Stock change',historical?'Record type':'Selected follow-up','Details'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{data.rows.map(r=><tr key={r.id}><td><strong>{r.symbol}</strong><small><span className={`la-tag la-tag--${r.direction}`}>{r.direction}</span> · Score {num(r.score)}</small></td><td>{stamp(r.published_at||r.signal_at)}{!historical&&<small>Quote: {stamp(r.quote_at)}</small>}</td><td>{num(r.reference_price)}</td><td>{num(r.latest_price)}<small>{r.latest_price_at?stamp(r.latest_price_at):'Open chart for history'}</small></td><td>{pct(r.stock_return_pct)}</td><td>{historical?'Unverified publication time':r.measurement?.status||'Not due / not applicable'}{!historical&&<small>{r.signal_status} · {pct(r.measurement?.stock_return_pct)}</small>}</td><td><button onClick={()=>setSelected(r.id)} aria-label={`View ${r.symbol} chart`}>Chart & log ↗</button></td></tr>)}{!data.rows.length&&<tr><td colSpan={7}>{historical?'No stored in-session signals for this date. Try a prior trading day.':'No publications in this range. The verified archive starts with new in-session signals after this release. Use Earlier engine snapshots to inspect saved prior evaluations.'}</td></tr>}</tbody></table></div>
 <div className="la-pager"><span>{total?`${page*25+1}–${Math.min(total,page*25+25)} of ${total}`:'0 records'}</span><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><button disabled={(page+1)*25>=total} onClick={()=>setPage(p=>p+1)}>Next</button></div></>}
 </section>{selected&&<HistoryDetail key={`${selected}-${refresh}`} id={selected} onClose={()=>setSelected(null)}/>}</>;
}
