import {useState} from 'react';
import {setPaperCalendar} from '@/lib/optionsLabAdminApi';
export const researchNames={regime_debit:'Regime · trend debit spread',regime_credit:'Regime · directional credit spread',iron_condor:'Range · iron condor',long_straddle:'Breakout · long straddle',long_strangle:'Breakout · long strangle',iron_fly:'Post-event · iron fly',futures_trend:'Trend · NIFTY futures'};
export const researchDescriptions={regime_debit:'EMA20/50 and ADX trend filter, followed by a completed pullback. ATM long option with an OTM hedge.',regime_credit:'Confirmed trend and IV percentile ≥60. Sell the opposite-side 15–20 delta option with an outer hedge.',iron_condor:'ADX below 18 and IV percentile ≥60. Two hedged 15–20 delta shorts, all four legs filled together.',long_straddle:'Completed breakout after compression and IV percentile ≤40. Buy a matched ATM call and put; 30-minute time stop.',long_strangle:'The same breakout filter, buying OTM 15–20 delta calls and puts; 30-minute time stop.',iron_fly:'High-IV range within 60 minutes after a reviewed blackout ends. Matched ATM shorts with outer wings; no assumption of capturing an earlier IV collapse.',futures_trend:'Confirmed trend plus the futures price on the corresponding side of its own average traded price. Full notional paper reserve; may exceed this account’s capital.'};
const money=n=>n==null?'—':Number(n).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Kolkata'});
export default function NiftyResearchSuite({research,agents,refresh}){
 const [date,setDate]=useState(today),[windows,setWindows]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function save(e){e.preventDefault();setBusy(true);setMessage('');try{
   const ranges=windows.trim()?windows.trim().split('\n').map(line=>{const match=line.trim().match(/^(\d{2}:\d{2})\s*-\s*(\d{2}:\d{2})$/);if(!match)throw new Error('Use one HH:MM-HH:MM window per line, in IST.');return {start:`${date}T${match[1]}:00+05:30`,end:`${date}T${match[2]}:00+05:30`};}):[];
   await setPaperCalendar(date,ranges);setReviewed(false);setMessage('Calendar saved. New signals use this review; pending signals were cancelled.');await refresh();
 }catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const r=research,ctx=r?.regime||{};
 return <section className="np-research" aria-label="Shared research portfolio"><p className="np-eyebrow">SEVEN NEW EXPERIMENTS · ONE SHARED PAPER ACCOUNT</p><h2>Regime research portfolio</h2><p>The original four experiments retain their own balances and rules. This portfolio starts with one ₹1 lakh budget shared by all seven strategies. Strategy figures below are P&amp;L contributions, not seven funded accounts.</p>
 <div className="np-metrics"><div>Shared marked equity<strong>{money(r?.equity)}</strong></div><div>Reserved capital<strong>{money(r?.reserve)}</strong></div><div>Open planned risk<strong>{money(r?.risk)}</strong></div><div>Sampled drawdown<strong>{money(r?.max_drawdown)}</strong></div><div>Market state<strong>{ctx.name||'Waiting for feed'}</strong></div><div>Account status<strong>{r?.halted?'Halted / unresolved':'Paper research'}</strong></div></div>
 <p>Complete five-minute bars: <strong>{r?.completed_bars??0}/50 minimum</strong> · Fresh session bars: <strong>{r?.session_bars??0}/3 minimum</strong> · Prior daily IV observations: <strong>{r?.iv_days??0}/20 minimum</strong>.</p>
 <p>ADX {ctx.adx?.toFixed(1)??'—'} · ATR {ctx.atr?.toFixed(1)??'—'} · EMA20 {ctx.ema20?.toFixed(1)??'—'} · EMA50 {ctx.ema50?.toFixed(1)??'—'} · ATM IV {ctx.iv?.toFixed(1)??'—'}% · IV percentile {ctx.iv_percentile?.toFixed(0)??'—'} · Event review: {ctx.event||'UNREVIEWED'}.</p>
 <details><summary>Event calendar · administrator review</summary><p>No automatic event feed is connected. Review scheduled market events and add blackout windows before enabling new research entries for a date. An empty list explicitly means you reviewed the date and require no blackout. Reviews expire at the end of the selected IST date. This affects the seven new strategies; legacy benchmarks keep their original rules.</p><p>Current saved review: {r?.calendar?.date||'None'} · {r?.calendar?.windows?.length??0} blackout windows.</p><form className="np-calendar" onSubmit={save}><label>Review date (IST)<input type="date" value={date} min={today()} onChange={e=>{setDate(e.target.value);setReviewed(false);}} required/></label><label>Blackout windows (IST, one per line)<textarea aria-label="Blackout windows" value={windows} onChange={e=>{setWindows(e.target.value);setReviewed(false);}} placeholder={'09:15-10:00\n13:00-14:00'} rows={3}/></label><label><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/> I reviewed scheduled events for this date.</label><button disabled={busy||!reviewed}>{busy?'Saving…':'Save dated review'}</button><p role="status">{message}</p></form></details>
 <details><summary>Rules, shared limits and evidence</summary><p>Signals use completed five-minute bars; entries wait for newer quotes on every leg and exits are checked each second. No fractional lots. At most two positions, four entries a day, two per strategy, ₹2,000 planned risk per entry and ₹4,000 open planned risk. A ₹3,000 daily loss trigger stops entries and requests simulated exits. These are triggers, not guaranteed maximum realised losses. Shared contract overlap is rejected. When signals compete, the strategy order shown below determines priority.</p><p>Options reserve their calculated expiry loss including entry charges. Exit charges are extra. Futures reserve full notional and use a 2×ATR stop, so a ₹1 lakh account will generally reject a full NIFTY futures lot. No broker margin estimate is presented as available buying power. Stops, gaps, and costs can exceed planned risk.</p><p>Each leg requires fresh two-sided depth and sufficient size, with basket timestamps no more than one second apart. Options use 0.5% adverse slippage; futures use 0.02%. Fees use the dated NSE/Upstox model, including brokerage, STT, transaction charges, SEBI, stamp duty, IPFT and GST. Four-leg fills are an atomic paper assumption; partial real fills are not simulated.</p><p>IV percentile uses up to 60 prior daily near-expiry ATM observations, requiring at least 20. Changing expiry tenor affects this proxy. Realised volatility is diagnostic, not an equivalent-horizon fair-value forecast. The classifier uses EMA20/50, Wilder ADX/ATR and prior six-bar compression; breadth, OI forecasts and automatic event detection are not included. Thresholds are unvalidated research settings.</p><p>Completed bars survive overnight; partial bars are discarded. New sessions and feed gaps need three fresh complete bars. Missing exit quotes preserve an unresolved position and halt the shared portfolio. No profitable-edge claim or historical results are generated for these new strategies. The legacy replay below still covers only its original two agents.</p></details>
 <h3>Strategy comparison · forward observations only</h3><div className="np-scroll"><table><thead><tr><th>Strategy / evidence</th><th>Closed trades</th><th>Closed net P&amp;L</th><th>Open + closed P&amp;L</th><th>Drawdown</th><th>Win rate</th><th>Profit factor</th></tr></thead><tbody>{Object.entries(researchNames).map(([key,name])=>{const a=agents?.[key];return <tr key={key}><th>{name}<small>{a?.status||'Waiting for the research engine'}</small></th><td>{a?.closed_trades??0}</td><td>{money(a?.net_pnl)}</td><td>{money(a?.equity)}</td><td>{money(a?.max_drawdown)}</td><td>{a?.win_rate==null?'—':`${a.win_rate}%`}</td><td>{a?.profit_factor??'—'}</td></tr>})}</tbody></table></div>
 </section>;
}
