const when=v=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'—';
const money=v=>v==null?'—':Number(v).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2});
const names={news_reaction:'News + price confirmation',price_control:'Price-only comparison'};
export default function NiftyNewsAgent({state,enabled}){
 if(!state)return <section className="np-research" aria-label="News trading agent"><h2>Nifty news agent</h2><p>Waiting for the first paper-worker observation.</p></section>;
 const stale=!state.last_at||Date.now()-new Date(state.last_at).getTime()>30000;
 const accounts=state.agents||{};
 return <section className="np-research" aria-label="News trading agent">
  <p className="np-eyebrow">NEWS REACTION · PAPER EXPERIMENT</p><h2>Nifty news agent</h2>
  <p>Fresh macro news opens a ten-minute window. A completed Nifty breakout determines the direction; the agent simulates buying one call or put lot on the next fresh option quote.</p>
  <p><strong>{stale?'Worker data is stale':enabled?'Running in paper mode':'New entries paused'}</strong> · {state.coverage}<br/>Last checked: {when(state.last_at)} IST · Complete one-minute bars: {state.complete_minutes}/4 minimum</p>
  <p>Two independent ₹1 lakh paper accounts run the same price and risk rules. Only the news account requires a qualifying event. Their returns can diverge after a skipped trade; a difference alone does not prove an edge.</p>
  <div className="np-grid">{Object.entries(accounts).map(([key,a])=><article className="np-agent" key={key}>
   <h3>{names[key]}</h3><p className={a.blocked?'np-error':'np-state'}>{a.status}</p>
   <div className="np-metrics"><div>Marked equity<strong>{money(a.equity)}</strong></div><div>Closed net P&amp;L<strong>{money(a.net_pnl)}</strong></div><div>Closed trades<strong>{a.closed_trades}</strong></div><div>Win rate<strong>{a.win_rate==null?'—':`${a.win_rate}%`}</strong></div><div>Sampled drawdown<strong>{money(a.max_drawdown)}</strong></div><div>Data-gap exits<strong>{a.data_gap_trades}</strong></div></div>
   {a.position&&<div className="np-position"><strong>{a.blocked?'Unresolved position · last known mark':'Open paper position'}</strong><p>{a.position.legs[0].option_type} {a.position.legs[0].strike} · {a.position.legs[0].expiry} · {a.position.quantity} units<br/>Entry: {money(a.position.legs[0].price)} per unit · {when(a.position.entry_at)} IST</p>{a.position.news&&<a href={a.position.news.url} target="_blank" rel="noreferrer">Trigger: {a.position.news.heading}</a>}</div>}
   <details><summary>Trade journal ({a.closed_trades})</summary>{!a.trades.length?<p>No completed paper trades yet. Historical news has not been replayed into this account.</p>:<div className="np-scroll"><table><thead><tr><th>Entry / news</th><th>Exit</th><th>Net P&amp;L</th></tr></thead><tbody>{a.trades.slice().reverse().map((t,i)=><tr key={i}><td>{t.legs[0].option_type} {t.legs[0].strike} · {t.quantity} units<small>{when(t.entry_at)} IST · {money(t.legs[0].price)} / unit</small>{t.news?<><a href={t.news.url} target="_blank" rel="noreferrer">{t.news.heading}</a><small>Received: {when(t.news.received_at)} IST</small></>:<small>No news requirement</small>}</td><td>{t.reason}<small>{when(t.exit_at)} IST · {money(t.exit_legs[0].price)} / unit</small><small>Charges: {money(t.entry_cost+t.exit_cost)}</small>{t.data_gap&&<strong>Data gap: impaired execution evidence</strong>}</td><td>{money(t.pnl)}</td></tr>)}</tbody></table></div>}</details>
   <details><summary>Decisions and skipped trades</summary>{a.events.slice().reverse().map((e,i)=><p key={i}><small>{when(e.at)} IST</small>{e.reason}</p>)}</details>
  </article>)}</div>
  <details><summary>News screening and rejection log</summary><p>Upstox instrument news is checked every minute. Qualifying topics are actual RBI rate/liquidity decisions, Indian macro releases, Fed rate decisions and OPEC supply decisions. These are rule-based topic matches, not verified fact or sentiment judgments. Ordinary company stories remain context because a company event need not move Nifty.</p><div className="np-scroll"><table><thead><tr><th>Headline</th><th>Received (IST)</th><th>Decision</th></tr></thead><tbody>{state.decisions.slice().reverse().map((d,i)=><tr key={`${d.id}-${i}`}><td><a href={d.url} target="_blank" rel="noreferrer">{d.heading}</a><small>Published: {when(d.published_at)} IST</small></td><td>{when(d.received_at)}</td><td>{d.reason}</td></tr>)}</tbody></table></div>{!state.decisions.length&&<p>Waiting for a news refresh.</p>}</details>
  <details><summary>Trading rules, costs and research limits</summary><p>Enter 9:25 am–2:30 pm IST after a completed one-minute close breaks the previous three complete minutes by 0.03%, with no more than 0.6% overshoot. The preceding range must be no wider than 0.4%. The confirmation minute must start after news receipt. Four complete minutes require at least 55 recorded seconds each; gaps restart this context.</p><p>News must arrive within five minutes of its publication, during uninterrupted collection, after this agent starts. Old articles, revisions, speculative headlines and duplicate macro topics within 30 minutes cannot create new events. The event window ends ten minutes after publication. Yahoo is for reading only and is excluded from trade decisions.</p><p>Nearest liquid call or put within 100 Nifty points, 2–14 days to expiry. One whole lot; at most ₹5,000 premium including entry charges, two entries per day, and a ₹2,000 daily loss trigger per account. Premium stop 20%, target 40%, maximum holding time 20 minutes; session exit begins at 3:15 pm. Stops and daily triggers can be exceeded by gaps. Ten-minute cooldown after exits. Both accounts respect the reviewed event calendar below and the desk’s pause control.</p><p>Entries use the next newer ask plus 0.5%; exits use bid minus 0.5%. Quotes must be no older than five seconds, have enough displayed size and a spread no wider than 5%. Estimated NSE/Upstox charges use the same dated fee model as the spread agents. Fills are simulations, not guaranteed execution.</p><p>A missing quote freezes the mark. The first usable quote closes the simulated position as a flagged data-gap recovery, then locks that account’s entries for the day. These trades remain in P&amp;L and are flagged as impaired evidence. The two new accounts are forward-only; the eleven-strategy historical replay does not include them. News coverage is limited to the connected feed, and this experiment has no demonstrated profitability.</p><small>Rules: {state.version} · Started {when(state.started_at)} IST</small></details>
 </section>;
}
