import {useMemo,useState} from 'react';
import './niftyTechnicalChart.css';
const fmt=(n)=>Number.isFinite(n)?n.toFixed(2):'—';
const time=(at)=>new Date(at*1000).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'});
const colors={ema20:'#fbbf24',ema50:'#a78bfa',sma3:'#22d3ee',sma10:'#fb923c'};
export default function NiftyTechnicalChart({chart,agents={},stale}){
 const [count,setCount]=useState(60),[offset,setOffset]=useState(0),[hover,setHover]=useState(null),[overlays,setOverlays]=useState(['ema20','ema50']),[level,setLevel]=useState(null),[drawing,setDrawing]=useState(false);
 const all=chart?.candles||[],end=Math.max(1,all.length-offset),bars=all.slice(Math.max(0,end-count),end);
 const events=useMemo(()=>Object.entries(agents).flatMap(([name,a])=>(a.events||[]).filter(e=>['signal','entry','exit'].includes(e.kind)).map(e=>({...e,name,at:Date.parse(e.at)/1000}))),[agents]);
 const W=1100,H=370,L=65,R=25,T=25,B=35;
 const values=bars.flatMap(b=>[b.low,b.high,...overlays.map(k=>b[k])]).filter(Number.isFinite);
 const low=values.length?Math.min(...values):0,high=values.length?Math.max(...values):1,pad=Math.max((high-low)*.08,1),lo=low-pad,hi=high+pad;
 const x=i=>L+(i+.5)*(W-L-R)/Math.max(bars.length,1),y=p=>T+(hi-p)/(hi-lo)*(H-T-B),width=Math.max(2,(W-L-R)/Math.max(bars.length,1)*.65);
 const selected=bars[hover]||bars.at(-1),last=all.at(-1);
 const toggle=k=>setOverlays(v=>v.includes(k)?v.filter(x=>x!==k):[...v,k]);
 function point(e){const r=e.currentTarget.getBoundingClientRect();return {i:Math.max(0,Math.min(bars.length-1,Math.floor(((e.clientX-r.left)/r.width*W-L)/(W-L-R)*bars.length))),price:hi-((e.clientY-r.top)/r.height*H-T)/(H-T-B)*(hi-lo)};}
 return <section className="nt-chart" aria-label="Nifty technical trading chart"><header><div><p className="np-eyebrow">NIFTY 50 · AGENT TECHNICAL CHART</p><h2>Price, signals and execution</h2><p>5-minute completed candles · {stale?'STALE — last recorded evidence': 'Recorded evidence'} · {last?new Date(last.at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'Waiting for chart data'} IST</p></div><strong>{fmt(last?.close)}</strong></header>
 <div className="nt-controls">{Object.keys(colors).map(k=><button key={k} aria-pressed={overlays.includes(k)} style={{borderColor:colors[k]}} onClick={()=>toggle(k)}>{k.toUpperCase()}</button>)}<label>View <select value={count} onChange={e=>{setCount(+e.target.value);setOffset(0);}}><option value="30">30 candles</option><option value="60">60 candles</option><option value="100">100 candles</option></select></label><button disabled={offset+count>=all.length} onClick={()=>setOffset(v=>Math.min(all.length-count,v+10))}>← Earlier</button><button disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-10))}>Later →</button><button aria-pressed={drawing} onClick={()=>setDrawing(v=>!v)}>Draw price level</button><button onClick={()=>{setLevel(null);setOffset(0);setDrawing(false);}}>Reset</button></div>
 {!bars.length?<p role="status">No completed candle evidence available yet. The chart needs the updated engine and valid recorded samples.</p>:<><div className="nt-readout">{selected&&<>{time(selected.at)} · O {fmt(selected.open)} · H {fmt(selected.high)} · L {fmt(selected.low)} · C {fmt(selected.close)} · ADX {fmt(selected.adx)} · ATR {fmt(selected.atr)}</>}</div><svg role="img" aria-label="Nifty sampled candlesticks with moving averages; green candles rise, red candles fall" viewBox={`0 0 ${W} ${H}`} onMouseMove={e=>setHover(point(e).i)} onMouseLeave={()=>setHover(null)} onClick={e=>{if(drawing){setLevel(point(e).price);setDrawing(false);}}}>
 {[0,1,2,3,4].map(i=>{const p=lo+(hi-lo)*i/4;return <g key={i}><line x1={L} x2={W-R} y1={y(p)} y2={y(p)} stroke="#263c49"/><text x={L-6} y={y(p)+4} textAnchor="end">{p.toFixed(0)}</text></g>;})}
 {bars.map((b,i)=><g key={b.at}><title>{new Date(b.at*1000).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} O {b.open} H {b.high} L {b.low} C {b.close}</title><line x1={x(i)} x2={x(i)} y1={y(b.high)} y2={y(b.low)} stroke={b.close>=b.open?'#34d399':'#fb7185'}/><rect x={x(i)-width/2} y={y(Math.max(b.open,b.close))} width={width} height={Math.max(1,Math.abs(y(b.open)-y(b.close)))} fill={b.close>=b.open?'#34d399':'#fb7185'}/>{i%Math.max(1,Math.floor(bars.length/7))===0&&<text x={x(i)} y={H-10} textAnchor="middle">{time(b.at)}</text>}{i>0&&b.at-bars[i-1].at>300&&<line x1={x(i)-width} x2={x(i)-width} y1={T} y2={H-B} stroke="#f97316" strokeDasharray="3 4"><title>Missing candles or session boundary</title></line>}</g>)}
 {overlays.map(k=><path key={k} d={bars.map((b,i)=>Number.isFinite(b[k])?`${i&&Number.isFinite(bars[i-1][k])&&b.at-bars[i-1].at===300?'L':'M'}${x(i)},${y(b[k])}`:'').join(' ')} fill="none" stroke={colors[k]} strokeWidth="1.6"/>)}
 {events.map((e,j)=>{const i=bars.findIndex(b=>e.at>=b.at&&e.at<b.at+300);return i<0?null:<g key={j}><circle cx={x(i)} cy={y(bars[i].high)-9-(j%3)*7} r="4" fill={e.kind==='exit'?'#fbbf24':e.kind==='entry'?'#fff':'#38bdf8'}/><title>{e.name} · {e.kind} · {time(e.at)} · {e.reason}</title></g>;})}
 {hover!==null&&bars[hover]&&<line x1={x(hover)} x2={x(hover)} y1={T} y2={H-B} stroke="#94a3b8" strokeDasharray="4 4"/>}
 {level!==null&&<g><line x1={L} x2={W-R} y1={y(level)} y2={y(level)} stroke="#f8fafc" strokeDasharray="5 5"/><text x={L+5} y={y(level)-5}>Manual level {fmt(level)}</text></g>}</svg></>}
 <p className="nt-note">{chart?.note||'Chart uses the same completed five-minute samples as the engine.'} EMA periods are five-minute bars, not days. Blue dots: signals · white: entries · yellow: exits. Hover a marker for its recorded reason. Orange separators indicate gaps/session boundaries. Drawing levels does not change trading rules.</p>
 <div className="nt-status"><div><b>Market state</b><p>{chart?.regime?.name||'Unavailable'}</p><small>IV percentile: {chart?.regime?.iv_percentile??'—'} · Event review: {chart?.regime?.event||'See calendar review below'}</small></div><div><b>Execution readiness</b><p>{Object.values(agents).filter(a=>a.blocked).length} halted agents</p><small>Stale quotes and unresolved positions remain visible; no synthetic gap fills.</small></div></div>
 <details><summary>Latest recorded decisions · all agents</summary><div className="nt-journal">{Object.entries(agents).flatMap(([name,a])=>(a.events||[]).slice(-5).map((e,i)=><p key={`${name}-${i}`}><b>{name}</b> · {new Date(e.at).toLocaleTimeString('en-IN',{timeZone:'Asia/Kolkata'})} · {e.kind}: {e.reason}</p>))}</div></details></section>;
}
