import {useCallback,useEffect,useRef,useState} from 'react';
import {Link} from 'react-router-dom';
import {getPaperAgents,controlPaperAgents,backtestPaperAgents} from '@/lib/optionsLabAdminApi';
import './niftyPaperAgents.css';
const names={opening_range:'Opening range breakout',mean_reversion:'Mean reversion',trend_pullback:'Trend-pullback debit spread',volatility_credit:'Volatility-filtered credit spread'};
const descriptions={opening_range:'Break above/below the 9:15–9:45 sampled spot range by 0.1%. Requires all three opening observations.',mean_reversion:'Fade a move beyond two standard deviations and 0.2% from the prior six 15-minute spot observations.',trend_pullback:'A completed five-minute trend, pullback and breakout confirmation. Buy an ATM option and sell a further OTM option of the same expiry.',volatility_credit:'A moderate five-minute trend and ATM implied volatility above an intraday realised-volatility estimate. Sell an OTM option against the trend and buy a further OTM hedge.'};
const isSpread=key=>['trend_pullback','volatility_credit'].includes(key);
function Legs({legs}){return <div className="np-scroll"><table><thead><tr><th>Leg</th><th>Fill / unit</th><th>Estimated charges</th></tr></thead><tbody>{legs.map((leg,i)=><tr key={i}><td>{leg.side} {leg.option_type} {leg.strike}<small>{leg.expiry} · {leg.lot_size} units</small></td><td>{money2(leg.price)}</td><td><details><summary>{money2(leg.charges.total)}</summary>{Object.entries(leg.charges).filter(([key])=>key!=='total').map(([key,value])=><small key={key}>{key}: {money2(value)}</small>)}</details></td></tr>)}</tbody></table></div>}
const money=n=>n==null?'—':Number(n).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const money2=n=>n==null?'—':Number(n).toLocaleString('en-IN',{style:'currency',currency:'INR',minimumFractionDigits:2,maximumFractionDigits:2});
const when=s=>s?new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'No observations yet';
const day=n=>new Date(Date.now()-n*86400000).toISOString().slice(0,10);
export default function NiftyPaperAgents(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('live'),[refreshing,setRefreshing]=useState(false),[loadedAt,setLoadedAt]=useState(null);
 const active=useRef(false),inFlight=useRef(null);
 const [start,setStart]=useState(day(30)),[end,setEnd]=useState(day(0));
 const refresh=useCallback(()=>{
  if(inFlight.current)return inFlight.current;
  setRefreshing(true);
  inFlight.current=getPaperAgents().then(d=>{if(active.current){setData(d);setLoadedAt(new Date().toISOString());setError('');}})
   .catch(e=>{if(active.current)setError(e.message);})
   .finally(()=>{inFlight.current=null;if(active.current)setRefreshing(false);});
  return inFlight.current;
 },[]);
 useEffect(()=>{active.current=true;refresh();const onVisible=()=>{if(!document.hidden)refresh();};const timer=setInterval(onVisible,5000);document.addEventListener('visibilitychange',onVisible);return()=>{active.current=false;clearInterval(timer);document.removeEventListener('visibilitychange',onVisible);};},[refresh]);
 async function action(kind){setBusy(true);setError('');try{if(kind==='backtest'){await backtestPaperAgents(start,end);setView('backtest');}else await controlPaperAgents(kind);await refresh();}catch(e){setError(e.message);}finally{setBusy(false);}}
 const result=view==='live'?data?.live:data?.last_backtest;
 const stream=data?.stream;
 const streaming=data?.interval_seconds===1;
 const heartbeatOld=stream?.heartbeat_at&&Date.now()-new Date(stream.heartbeat_at).getTime()>30000;
 return <main className="np-root"><header className="np-header"><div><Link to="/admin/options-lab">← Options Lab</Link><p className="np-eyebrow">NIFTY 50 · PRIVATE RESEARCH</p><h1>Paper trading desk.</h1><p>Four rule-based experiments. Real recorded quotes. Independent virtual capital.</p></div><span className="np-badge">PAPER ONLY · NO REAL ORDERS</span></header>
 <section className="np-toolbar"><div><strong>{error?(data?'Showing last loaded status':'Agent status unavailable'):data?.enabled?'Paper agents enabled':data?'New entries paused':'Loading agent status…'}</strong><p>{data?`Last processed: ${when(data.live?.last_at)} IST`:'Waiting for the server — account status is not yet available.'}</p>{data?.quote_age_seconds>(streaming?5:1200)&&<p className="np-warning">No recent observation. Check market hours and feed health. Values are as of the time above.</p>}</div><div><button disabled={busy||!data||!!error||data.enabled} onClick={()=>action('start')}>Start / resume agents</button><button disabled={busy||!data||!!error||!data.enabled} onClick={()=>action('pause')}>Pause new entries</button></div></section>
 {streaming&&<section className="np-stream" aria-label="Live stream health"><div><p className="np-eyebrow">UPSTOX LIVE FEED · 1-SECOND CHECKS</p><h2>{heartbeatOld?'Worker heartbeat overdue':stream?.status||'Waiting for streaming worker'}</h2><p>Feed authorization: {stream?.authorization||'Not yet verified'} · {stream?.connected?'Connected':'Disconnected / idle'} · Dashboard updates every 5 seconds</p></div><div className="np-metrics"><div>Fresh contracts<strong>{stream?.fresh_contracts??0} / {stream?.subscribed_contracts??0}</strong></div><div>Processing time<strong>{stream?.processing_ms==null?'—':`${stream.processing_ms} ms`}</strong></div><div>Worker CPU<strong>{stream?.cpu_percent_one_core==null?'—':`${stream.cpu_percent_one_core}%`}</strong><small>Of one CPU core · recent interval</small></div><div>Peak memory<strong>{stream?.peak_memory_mb==null?'—':`${stream.peak_memory_mb} MB`}</strong></div><div>Recorded seconds<strong>{stream?.recorded_frames??0}</strong><small>Since worker restart</small></div><div>Worker heartbeat<strong>{when(stream?.heartbeat_at)}</strong></div></div>{stream?.error&&<p role="alert" className="np-warning">{stream.error}</p>}<p>One shared feed for NIFTY and up to 42 nearby options, plus held contracts. Quotes over 5 seconds old are rejected. One-second evidence is retained for 14 days; account balances and trade journals are preserved.</p></section>}
 {error&&<div role="alert" className="np-error"><p>{error}</p>{data&&<p>Last successfully loaded: {when(loadedAt)} IST. Displayed balances and feed status may be out of date.</p>}<button disabled={refreshing} onClick={refresh}>{refreshing?'Retrying…':'Retry now'}</button></div>}
 <section className="np-method"><h2>New: two spread agents</h2><p>Trend-pullback debit spreads and volatility-filtered credit spreads use completed five-minute candles built from one-second spot samples. These are sampled OHLC candles, not a complete exchange tick history. Both agents monitor exits every second.</p><p><strong>Warm-up: {data?.live?.candle_status?.completed_5m??0} / 12 complete five-minute candles.</strong> Incomplete minutes are discarded. A fresh session or data gap restarts warm-up. New entries run from 10:15 am to 2:15 pm IST; session exits start at 3:15 pm.</p><details><summary>Spread rules, costs and limits</summary><p>Each spread agent starts with ₹1,00,000 independently. One matched two-leg lot at a time, up to ₹2,000 planned expiry loss including entry charges, two entries per day and a ₹2,000 daily loss trigger. Exit charges are additional. Debit spreads stop at 40% of debit and target 50% of remaining gross upside; credit spreads target 50% of credit and stop at the lower of one credit or half their gross maximum loss.</p><p>Both legs must have newer quotes than the signal, no more than one second apart, with enough displayed size. The simulator fills both or neither; actual partial fills are not modelled. Capital reserve covers strike width × lot plus gross long premium and entry fees. It is a paper reserve, not a broker margin quote.</p><details><summary>Spread costs and research assumptions</summary><p>Estimated charges per executed leg: ₹20 brokerage; sell-side STT 0.15%; NSE transaction charge 0.03553%; SEBI ₹10/crore; buy-side stamp duty 0.003%; IPFT ₹0.01/crore; GST 18% on brokerage, transaction and IPFT. Rates checked 28 September 2026, before broker rounding. Every fill adds 0.5% adverse slippage. <a href="https://upstox.com/brokerage-charges/" target="_blank" rel="noreferrer">Fee source</a>.</p><p>The credit agent compares same-expiry ATM IV with annualised volatility from eleven five-minute returns. This is a short-history screening proxy, not a calibrated forecast or proven edge. Missing IV means no entry. Both spreads use expiry 2–14 days away and 50–200-point wings.</p></details></details></section>
 <section className="np-method"><details><summary>Original agents · legacy baseline rules</summary><h2>The original experiment</h2><p>Each agent starts with ₹1,00,000 separately. One long call or put lot at a time, maximum ₹10,000 including premium and entry costs, two entries per day and a ₹2,000 daily loss trigger. Premium stop 20%; target 40%; session exit from 3:15 pm IST. Actual sampled exits can exceed a stop.</p><p>{streaming?'Forward agents evaluate once per second using fresh streamed quotes. Strategy context still uses 15-minute boundary observations; six observations still span roughly 90 minutes. Simulated entries require a newer quote after the signal.':'The agents use the first recorded collection in each 15-minute window.'} Entries use ask plus 0.5% slippage. Exits use bid minus 0.5%. Costs assume ₹20 plus 0.5% of premium turnover on each side—an illustrative all-in cost stress, not your broker’s exact tariff. Lot sizes come from contract metadata. These legacy costs differ from the new spread agents; results are not directly comparable on costs.</p></details></section>
 <section className="np-replay"><div><h2>Replay recorded history</h2><p>15-minute historical replay · up to 60 calendar days. This uses the older stored option-chain snapshots. It covers only the two original agents. The new spreads have no historical backtest yet.</p></div><label>From<input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)}/></label><label>Through<input type="date" value={end} min={start} max={day(0)} onChange={e=>setEnd(e.target.value)}/></label><button disabled={busy||!data||!!error||!start||!end} onClick={()=>action('backtest')}>{busy?'Working…':'Run replay'}</button></section>
 <nav className="np-tabs" aria-label="Simulation mode"><button aria-pressed={view==='live'} onClick={()=>setView('live')}>Forward paper trading</button><button aria-pressed={view==='backtest'} onClick={()=>setView('backtest')}>Historical replay</button></nav>
 {view==='backtest'&&(result?<p>{result.days} observed days · {result.sampled_observations ?? result.observations} sampled observations · {result.quote_rows} option quotes. Requested {result.start} to {result.end}. {result.status==='no_data'?'No stored quotes in this period.':''} Historical replay is exploratory, not out-of-sample validation.</p>:<p>Run a replay to inspect the available history. No backtest results have been created yet.</p>)}
 <div className="np-grid">{result&&Object.entries(result.agents).sort(([a],[b])=>Number(isSpread(b))-Number(isSpread(a))).map(([key,a])=><article className="np-agent" key={key}><p className="np-eyebrow">{isSpread(key)?'NEW SPREAD AGENT':'LEGACY BASELINE'}</p><h2>{names[key]}</h2><p>{descriptions[key]}</p><small>Cost model: {a.fee_model||'Legacy illustrative costs'}</small><p className={a.blocked?'np-error':'np-state'}>{a.status}</p><div className="np-metrics"><div>Marked equity<strong>{money(a.equity)}</strong></div><div>Closed net P&L<strong>{money(a.net_pnl)}</strong></div><div>Closed trades<strong>{a.closed_trades}</strong></div><div>Win rate<strong>{a.win_rate==null?'—':`${a.win_rate}%`}</strong></div><div>Sampled max drawdown<strong>{money(a.max_drawdown)}</strong></div><div>Cash balance<strong>{money(a.cash)}</strong></div><div>Average trade<strong>{money(a.average_pnl)}</strong></div><div>Profit factor<strong>{a.profit_factor??'—'}</strong></div><div>Closed trade charges<strong>{money(a.total_charges)}</strong></div>{isSpread(key)&&<><div>Paper reserve<strong>{money(a.capital_reserved)}</strong></div><div>Cash less reserve<strong>{money(a.available_after_reserve)}</strong></div></>}</div>
 {a.position&&<div className="np-position"><h3>{a.blocked?'Unresolved position — last known mark':'Open simulated position'}</h3>{a.position.legs?<><Legs legs={a.position.legs}/><p>Net P&amp;L stop: −{money(a.position.stop_loss)} · Target: +{money(a.position.target_profit)}<small>Planned expiry loss {money(a.position.max_loss)} · Upside {money(a.position.max_profit)} before exit fees</small></p></>:<><p>{a.position.option_type} {a.position.strike} · {a.position.expiry} · {a.position.quantity} units</p><p>Entry {money(a.position.entry_price)} · Stop {money(a.position.stop)} · Target {money(a.position.target)} per unit</p></>}</div>}
 <h3>Trade journal</h3>{!a.trades.length?<p>No completed trades. Waiting is a valid outcome.</p>:<div className="np-scroll"><table><thead><tr><th>Contract / entry</th><th>Exit / reason</th><th>Net P&L</th></tr></thead><tbody>{a.trades.slice().reverse().map((t,i)=><tr key={i}><td>{t.legs?<details><summary>{t.legs.map(l=>`${l.side} ${l.option_type} ${l.strike}`).join(' / ')}</summary><strong>Entry</strong><Legs legs={t.legs}/><strong>Exit</strong><Legs legs={t.exit_legs}/></details>:<>{t.option_type} {t.strike} · {t.quantity} units</>}<small>{when(t.entry_at)}</small></td><td>{t.reason}<small>{when(t.exit_at)}</small></td><td>{money(t.pnl)}</td></tr>)}</tbody></table></div>}
 <details><summary>Agent decisions and skips</summary>{a.events.slice().reverse().map((e,i)=><p key={i}><small>{when(e.at)}</small> {e.kind}: {e.reason}</p>)}</details></article>)}</div>
 <footer className="np-method"><h2>Read the evidence correctly</h2><p>These are experimental baselines, not validated profitable strategies. A one-second evaluation is not a guarantee of a new quote every second. Feed timestamps and displayed top-of-book sizes help reject stale or undersized quotes; actual execution is not simulated perfectly. Historical replay still uses 15-minute data, so its results cannot validate one-second execution. Wide/crossed quotes, missing liquidity, expiry day and missing lot sizes are excluded. Missing quotes while a position is open halt that agent and keep the position unresolved; equity then remains its last known mark.</p><p>Pausing prevents new entries and cancels pending signals; existing positions continue to be observed for exits while the data worker runs. All four virtual accounts are independent, so their balances should not be treated as one ₹1 lakh portfolio. Spread fills assume both legs execute; a live broker can fill them separately. No real-money execution is connected.</p></footer>
 </main>;
}
