import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {getPaperAgents,controlPaperAgents,backtestPaperAgents} from '@/lib/optionsLabAdminApi';
import './niftyPaperAgents.css';
const names={opening_range:'Opening range breakout',mean_reversion:'Mean reversion'};
const money=n=>n==null?'—':Number(n).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0});
const when=s=>s?new Date(s).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'}):'No observations yet';
const day=n=>new Date(Date.now()-n*86400000).toISOString().slice(0,10);
export default function NiftyPaperAgents(){
 const [data,setData]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[view,setView]=useState('live');
 const [start,setStart]=useState(day(30)),[end,setEnd]=useState(day(0));
 useEffect(()=>{let active=true;const load=()=>getPaperAgents().then(d=>{if(active){setData(d);setError('');}}).catch(e=>{if(active)setError(e.message);});load();const timer=setInterval(()=>{if(!document.hidden)load();},5000);return()=>{active=false;clearInterval(timer);};},[]);
 async function action(kind){setBusy(true);setError('');try{if(kind==='backtest'){await backtestPaperAgents(start,end);setView('backtest');}else await controlPaperAgents(kind);setData(await getPaperAgents());}catch(e){setError(e.message);}finally{setBusy(false);}}
 const result=view==='live'?data?.live:data?.last_backtest;
 const stream=data?.stream;
 const streaming=data?.interval_seconds===1;
 const heartbeatOld=stream?.heartbeat_at&&Date.now()-new Date(stream.heartbeat_at).getTime()>30000;
 return <main className="np-root"><header className="np-header"><div><Link to="/admin/options-lab">← Options Lab</Link><p className="np-eyebrow">NIFTY 50 · PRIVATE RESEARCH</p><h1>Paper trading desk.</h1><p>Two rule-based agents. Real recorded quotes. Virtual capital.</p></div><span className="np-badge">PAPER ONLY · NO REAL ORDERS</span></header>
 <section className="np-toolbar"><div><strong>{data?.enabled?'Paper agents enabled':data?'New entries paused':'Loading agent status…'}</strong><p>Last processed: {when(data?.live?.last_at)} IST</p>{data?.quote_age_seconds>(streaming?5:1200)&&<p className="np-warning">No recent observation. Check market hours and feed health. Values are as of the time above.</p>}</div><div><button disabled={busy||!data||data.enabled} onClick={()=>action('start')}>Start / resume agents</button><button disabled={busy||!data||!data.enabled} onClick={()=>action('pause')}>Pause new entries</button></div></section>
 {streaming&&<section className="np-stream" aria-label="Live stream health"><div><p className="np-eyebrow">UPSTOX LIVE FEED · 1-SECOND CHECKS</p><h2>{heartbeatOld?'Worker heartbeat overdue':stream?.status||'Waiting for streaming worker'}</h2><p>Feed authorization: {stream?.authorization||'Not yet verified'} · {stream?.connected?'Connected':'Disconnected / idle'} · Dashboard updates every 5 seconds</p></div><div className="np-metrics"><div>Fresh contracts<strong>{stream?.fresh_contracts??0} / {stream?.subscribed_contracts??0}</strong></div><div>Processing time<strong>{stream?.processing_ms==null?'—':`${stream.processing_ms} ms`}</strong></div><div>Worker CPU<strong>{stream?.cpu_percent_one_core==null?'—':`${stream.cpu_percent_one_core}%`}</strong><small>Of one CPU core · recent interval</small></div><div>Peak memory<strong>{stream?.peak_memory_mb==null?'—':`${stream.peak_memory_mb} MB`}</strong></div><div>Recorded seconds<strong>{stream?.recorded_frames??0}</strong><small>Since worker restart</small></div><div>Worker heartbeat<strong>{when(stream?.heartbeat_at)}</strong></div></div>{stream?.error&&<p role="alert" className="np-warning">{stream.error}</p>}<p>One shared feed for NIFTY and up to 42 nearby options, plus held contracts. Quotes over 5 seconds old are rejected. One-second evidence is retained for 14 days; account balances and trade journals are preserved.</p></section>}
 {error&&<p role="alert" className="np-error">{error}</p>}
 <section className="np-method"><h2>The experiment</h2><p>Each agent starts with ₹1,00,000 separately. One long call or put lot at a time, maximum ₹10,000 including premium and entry costs, two entries per day and a ₹2,000 daily loss trigger. Premium stop 20%; target 40%; session exit from 3:15 pm IST. Actual sampled exits can exceed a stop.</p><p>{streaming?'Forward agents evaluate once per second using fresh streamed quotes. Strategy context still uses 15-minute boundary observations; six observations still span roughly 90 minutes. Simulated entries require a newer quote after the signal.':'The agents use the first recorded collection in each 15-minute window.'} Entries use ask plus 0.5% slippage. Exits use bid minus 0.5%. Costs assume ₹20 plus 0.5% of premium turnover on each side—an illustrative all-in cost stress, not your broker’s exact tariff. Lot sizes come from contract metadata.</p></section>
 <section className="np-replay"><div><h2>Replay recorded history</h2><p>15-minute historical replay · up to 60 calendar days. This uses the older stored option-chain snapshots. It does not backtest the new one-second execution.</p></div><label>From<input type="date" value={start} max={end} onChange={e=>setStart(e.target.value)}/></label><label>Through<input type="date" value={end} min={start} max={day(0)} onChange={e=>setEnd(e.target.value)}/></label><button disabled={busy||!data||!start||!end} onClick={()=>action('backtest')}>{busy?'Working…':'Run replay'}</button></section>
 <nav className="np-tabs" aria-label="Simulation mode"><button aria-pressed={view==='live'} onClick={()=>setView('live')}>Forward paper trading</button><button aria-pressed={view==='backtest'} onClick={()=>setView('backtest')}>Historical replay</button></nav>
 {view==='backtest'&&(result?<p>{result.days} observed days · {result.sampled_observations ?? result.observations} sampled observations · {result.quote_rows} option quotes. Requested {result.start} to {result.end}. {result.status==='no_data'?'No stored quotes in this period.':''} Historical replay is exploratory, not out-of-sample validation.</p>:<p>Run a replay to inspect the available history. No backtest results have been created yet.</p>)}
 <div className="np-grid">{result&&Object.entries(result.agents).map(([key,a])=><article className="np-agent" key={key}><p className="np-eyebrow">AGENT {key==='opening_range'?'01':'02'}</p><h2>{names[key]}</h2><p>{key==='opening_range'?'Break above/below the 9:15–9:45 sampled spot range by 0.1%. Requires all three opening observations.':'Fade a move beyond two standard deviations and 0.2% from the prior six 15-minute spot observations.'}</p><p className={a.blocked?'np-error':'np-state'}>{a.status}</p><div className="np-metrics"><div>Marked equity<strong>{money(a.equity)}</strong></div><div>Closed net P&L<strong>{money(a.net_pnl)}</strong></div><div>Closed trades<strong>{a.closed_trades}</strong></div><div>Win rate<strong>{a.win_rate==null?'—':`${a.win_rate}%`}</strong></div><div>Sampled max drawdown<strong>{money(a.max_drawdown)}</strong></div><div>Available cash<strong>{money(a.cash)}</strong></div></div>
 {a.position&&<div className="np-position"><h3>{a.blocked?'Unresolved position — last known mark':'Open simulated position'}</h3><p>{a.position.option_type} {a.position.strike} · {a.position.expiry} · {a.position.quantity} units</p><p>Entry {money(a.position.entry_price)} · Stop {money(a.position.stop)} · Target {money(a.position.target)} per unit</p></div>}
 <h3>Trade journal</h3>{!a.trades.length?<p>No completed trades. Waiting is a valid outcome.</p>:<div className="np-scroll"><table><thead><tr><th>Contract / entry</th><th>Exit / reason</th><th>Net P&L</th></tr></thead><tbody>{a.trades.slice().reverse().map((t,i)=><tr key={i}><td>{t.option_type} {t.strike} · {t.quantity} units<small>{when(t.entry_at)}</small></td><td>{t.reason}<small>{when(t.exit_at)}</small></td><td>{money(t.pnl)}</td></tr>)}</tbody></table></div>}
 <details><summary>Agent decisions and skips</summary>{a.events.slice().reverse().map((e,i)=><p key={i}><small>{when(e.at)}</small> {e.kind}: {e.reason}</p>)}</details></article>)}</div>
 <footer className="np-method"><h2>Read the evidence correctly</h2><p>These are experimental baselines, not validated profitable strategies. A one-second evaluation is not a guarantee of a new quote every second. Feed timestamps and displayed top-of-book sizes help reject stale or undersized quotes; actual execution is not simulated perfectly. Historical replay still uses 15-minute data, so its results cannot validate one-second execution. Wide/crossed quotes, missing liquidity, expiry day and missing lot sizes are excluded. Missing quotes while a position is open halt that agent and keep the position unresolved; equity then remains its last known mark.</p><p>Pausing prevents new entries and cancels pending signals; existing positions continue to be observed for exits while the data worker runs. Both virtual accounts are independent, so their balances should not be treated as one ₹1 lakh portfolio. No real-money execution is connected.</p></footer>
 </main>;
}
