import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {Helmet} from 'react-helmet-async';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,PieChart,Pie,Cell} from 'recharts';
import {RefreshCw,ArrowLeft} from 'lucide-react';
import usePublicStats from '@/lib/usePublicStats';
import './toolsStats.css';
const num=n=>Number(n||0).toLocaleString('en-IN');
const colors=['#a5d7fc','#b9e2ff','#78bdf2','#d0eaff','#91c7ed','#e4f3ff'];
function Breakdown({title,rows=[]}){const max=Math.max(1,...rows.map(r=>r.views));return <section className="ts-card"><h2>{title}<small>Page views</small></h2>{rows.length?rows.map(r=><div className="ts-bar" key={r.label}><span style={{width:`${r.views/max*100}%`}}/><strong>{r.label}</strong><b>{num(r.views)}</b></div>):<p className="ts-empty">No recorded data for this period.</p>}</section>;}
export default function ToolsStatsPage(){const[days,setDays]=useState(1),[metric,setMetric]=useState('visitors'),[deviceTab,setDeviceTab]=useState('devices');const{data,error,refresh}=usePublicStats(days);
 return <main className="ts"><Helmet><title>Website Stats | AGI Tools</title></Helmet><header className="ts-top"><Link to="/finance-tools"><ArrowLeft size={17}/> AGI Tools</Link><span>PUBLIC WEBSITE STATS</span></header><div className="ts-heading"><div><h1>A closer look at our audience.</h1><p>Recorded activity across the AGI website. All dates and times use IST.</p></div><div className="ts-controls"><label><span className="ts-sr">Reporting period</span><select value={days} onChange={e=>setDays(Number(e.target.value))}><option value={1}>Today · IST</option><option value={7}>Last 7 days</option><option value={30}>Last 30 days</option><option value={90}>Last 90 days</option></select></label><button onClick={refresh} aria-label="Refresh statistics"><RefreshCw size={18}/></button></div></div>
 {error&&<p role="alert" className="ts-error">{error}{data?' Showing the last successful result.':''}</p>}{!data&&!error&&<p role="status">Loading recorded traffic…</p>}
 {data&&<><section className="ts-card ts-main"><div className="ts-kpis">{[['Visitors',data.visitors,'Distinct browsers'],['Visits',data.visits,'Browser sessions'],['Page views',data.pageviews,'Recorded page openings'],['Repeat visitors',data.repeatVisitors,'Multiple visits in this range'],['Recent activity',data.active,'Browsers viewing in last 5 min']].map(([label,value,note])=><div key={label}><span>{label}</span><strong>{num(value)}</strong><small>{note}</small></div>)}</div><div className="ts-chart-head"><div className="ts-tabs">{['visitors','views'].map(m=><button key={m} aria-pressed={metric===m} onClick={()=>setMetric(m)}>{m==='views'?'Page views':'Visitors'}</button>)}</div><span>{days===1?'Hourly':'Daily'} · Current interval is incomplete</span></div>{data.trend.length?<div className="ts-chart" role="img" aria-label={`${metric} by ${days===1?'hour':'day'}. Exact counts in the table below.`}><ResponsiveContainer width="100%" height={320}><AreaChart data={data.trend} margin={{top:15,right:20,left:0,bottom:10}}><defs><linearGradient id="trafficFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#90caf9" stopOpacity={.45}/><stop offset="100%" stopColor="#90caf9" stopOpacity={.02}/></linearGradient></defs><CartesianGrid strokeDasharray="4 5" vertical={false}/><XAxis dataKey="date" tickFormatter={d=>days===1?d.slice(11):d.slice(5)} minTickGap={30}/><YAxis allowDecimals={false}/><Tooltip formatter={v=>[num(v),metric==='views'?'Page views':'Visitors']} labelFormatter={v=>`${v} IST`}/><Area type="linear" dataKey={metric} stroke="#88c7f7" strokeWidth={3} fill="url(#trafficFill)" dot={data.trend.length===1}/></AreaChart></ResponsiveContainer></div>:<p className="ts-empty">Traffic history will appear once the updated reporting service has recorded data.</p>}<details><summary>View exact figures</summary><table><thead><tr><th>Period (IST)</th><th>Visitors</th><th>Page views</th></tr></thead><tbody>{data.trend.map(r=><tr key={r.date}><td>{r.date}</td><td>{num(r.visitors)}</td><td>{num(r.views)}</td></tr>)}</tbody></table></details></section>
 <div className="ts-grid"><section className="ts-card"><h2>Traffic channels<small>Page views</small></h2>{data.channels.length?<><div className="ts-donut"><ResponsiveContainer width="100%" height={230}><PieChart><Pie data={data.channels} dataKey="views" nameKey="label" innerRadius={65} outerRadius={100} paddingAngle={3}>{data.channels.map((r,i)=><Cell key={r.label} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="ts-legend">{data.channels.map((r,i)=><div key={r.label}><i style={{background:colors[i%colors.length]}}/>{r.label}<b>{num(r.views)}</b></div>)}</div></>:<p className="ts-empty">No recorded channels yet.</p>}</section><Breakdown title="Page groups" rows={data.pages}/><section className="ts-card"><div className="ts-tabs">{[['devices','Device'],['browsers','Browser'],['operatingSystems','OS']].map(([k,l])=><button key={k} aria-pressed={deviceTab===k} onClick={()=>setDeviceTab(k)}>{l}</button>)}</div><Breakdown title="Audience technology" rows={data[deviceTab]}/><p className="ts-caption">Browser and OS collection starts with this release. Earlier events show Unknown.</p></section><section className="ts-card"><h2>Recorded actions</h2><div className="ts-actions"><div><span>Model downloads</span><strong>{num(data.downloads)}</strong></div><div><span>Sign-up completions</span><strong>{num(data.signups)}</strong></div></div><p>Browser-reported actions in this period, not audited account or sales totals.</p><h3>Not collected</h3><p>Location, bounce rate, session duration, campaign attribution and listing clicks are not measured by this tracker. No estimates are substituted.</p></section></div>
 <footer className="ts-method"><p>Updated {new Date(data.updatedAt).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})} IST · Refreshes every minute while visible.{data.trackingSince?` Tracking began ${new Date(data.trackingSince).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata'})}.`:''}</p><details><summary>How these numbers are measured</summary><p>Visitors estimate distinct browsers, not people. A browser may appear in several time buckets, so chart totals need not equal unique visitors. Visits reset after 30 minutes of inactivity. Recent activity records page openings in the last five minutes, not live concurrent users. Blocked requests, privacy choices and basic bot filtering affect coverage.</p><p>{data.breakdownNote} Referring domains and individual page paths are grouped for this public report. No visitor IDs, IP addresses, email addresses or private account details are published.</p><p>Counts cover AGI website activity, not just this directory. Past activity is not reconstructed. These figures do not guarantee sponsorship traffic or leads.</p></details></footer></>}
 </main>;
}
