import { useEffect, useMemo, useState } from 'react';
import { Bell, Briefcase, CheckCircle2, FileSearch, Gauge, Layers3, Loader2, Play, Radar, ShieldCheck, Sparkles } from 'lucide-react';
import { createInstitutionalGroup, createInstitutionalWatchlist, getInstitutionalResearchLayer, getInstitutionalWorkspace, markInstitutionalPersonalizedAlert } from '@/lib/institutionalHoldingsApi';

const percent = (value, signed = false) => `${signed && Number(value) > 0 ? '+' : ''}${(Number(value || 0) * 100).toFixed(1)}%`;
const displayDate = (value) => { const date = value ? new Date(value) : null; return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' }) : 'Timestamp unavailable'; };
function Metric({ label, value, note }) { return <div className="rounded-xl border border-white/10 bg-white/[0.035] p-4"><div className="text-[10px] font-bold uppercase tracking-[.18em] text-slate-500">{label}</div><div className="mt-2 text-2xl font-semibold text-white">{value}</div>{note ? <div className="mt-1 text-xs text-slate-500">{note}</div> : null}</div>; }
function Empty({ children }) { return <div className="rounded-xl border border-dashed border-white/10 p-8 text-center text-sm leading-6 text-slate-500">{children}</div>; }

export default function InstitutionalResearchLayer() {
  const [data, setData] = useState(null); const [tab, setTab] = useState('rotation'); const [managerSlug, setManagerSlug] = useState('');
  const [workspace, setWorkspace] = useState(null); const [working, setWorking] = useState(''); const [message, setMessage] = useState('');
  const [groupName, setGroupName] = useState('High-conviction managers'); const [watchlistName, setWatchlistName] = useState('Institutional signals'); const [watchTickers, setWatchTickers] = useState('AAPL, MSFT, NVDA');
  const loadResearchLayer = () => {
    setWorking('research'); setMessage('');
    getInstitutionalResearchLayer()
      .then((payload) => { setData(payload); setManagerSlug(payload.managers?.[0]?.slug || ''); })
      .catch((error) => setMessage(error.message || 'Institutional research is temporarily unavailable.'))
      .finally(() => setWorking(''));
  };
  useEffect(() => { loadResearchLayer(); }, []);
  const movers = useMemo(() => (data?.sector_rotation || []).filter((row) => row.sector !== 'Unclassified'), [data]);
  const loadWorkspace = async () => { setWorking('workspace'); setMessage(''); try { setWorkspace(await getInstitutionalWorkspace()); } catch (error) { setMessage(error.message); } finally { setWorking(''); } };
  const tabs = [['rotation', 'Sector rotation', Layers3], ['performance', 'Performance lab', Gauge, 'validating'], ['filings', '13D/G + Form 4', FileSearch], ['briefs', 'Analyst briefs', Sparkles], ['workspace', 'My workspace', Briefcase]];
  if (!data) return <section className="mx-auto mt-8 flex max-w-7xl flex-col items-center justify-center rounded-2xl border border-slate-200 bg-[#07151d] p-16 text-center text-slate-400">{working === 'research' ? <><Loader2 className="mb-3 h-5 w-5 animate-spin" /><span>Loading institutional research layer</span></> : <><div className="text-base font-semibold text-white">Institutional research is temporarily unavailable</div><div className="mt-2 max-w-xl text-sm">{message || 'The evidence service did not respond. Your existing holdings data remains available.'}</div><button type="button" onClick={loadResearchLayer} className="mt-5 rounded-xl bg-cyan-300 px-5 py-3 text-sm font-bold text-slate-950">Retry research layer</button></>}</section>;
  return <section className="mx-auto mt-8 max-w-7xl overflow-hidden rounded-2xl border border-cyan-300/15 bg-[#07151d] text-slate-100 shadow-2xl shadow-slate-950/10">
    <div className="relative overflow-hidden border-b border-white/10 px-6 py-7 lg:px-8"><div className="absolute inset-0 opacity-40 [background-image:linear-gradient(rgba(34,211,238,.08)_1px,transparent_1px),linear-gradient(90deg,rgba(34,211,238,.08)_1px,transparent_1px)] [background-size:32px_32px]" /><div className="relative flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.28em] text-cyan-300"><Radar className="h-4 w-4" /> Institutional intelligence V3</div><h2 className="mt-3 text-3xl font-semibold tracking-tight text-white">From disclosure to decision</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">Point-in-time classifications, filing-aware performance, ownership disclosures and analyst-controlled research in one evidence trail.</p></div><div className="flex items-center gap-2 rounded-full border border-emerald-300/20 bg-emerald-300/10 px-4 py-2 text-xs font-semibold text-emerald-300"><ShieldCheck className="h-4 w-4" /> No look-ahead methodology</div></div>
      <div className="relative mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><Metric label="Tracked managers" value={data.readiness?.managers_tracked || 0} /><Metric label="12-quarter ready" value={data.readiness?.managers_with_12_quarters || 0} note="Full history gate" /><Metric label="Classifications" value={data.readiness?.classifications || 0} /><Metric label="13D/G + Form 4" value={data.readiness?.external_filings || 0} /><Metric label="Approved briefs" value={data.readiness?.approved_briefs || 0} /></div></div>
    <div className="flex gap-2 overflow-x-auto border-b border-white/10 px-5 py-3">{tabs.map(([key, label, Icon, state]) => state === 'validating' ? <span key={key} title="Withheld while the filing-aware backtest is revalidated" className="inline-flex shrink-0 cursor-not-allowed items-center gap-2 rounded-lg px-4 py-2 text-xs font-semibold text-slate-600"><Icon className="h-4 w-4" />{label}<span className="rounded-full border border-amber-300/30 px-2 py-[2px] text-[9px] font-bold uppercase tracking-wider text-amber-300/80">In review</span></span> : <button key={key} type="button" onClick={() => { setTab(key); if (key === 'workspace' && !workspace) loadWorkspace(); }} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-4 py-2 text-xs font-semibold transition ${tab === key ? 'bg-cyan-300 text-slate-950' : 'text-slate-400 hover:bg-white/5 hover:text-white'}`}><Icon className="h-4 w-4" />{label}</button>)}</div>
    {message ? <div className="mx-6 mt-5 rounded-xl border border-cyan-300/15 bg-cyan-300/5 px-4 py-3 text-sm text-cyan-100">{message}</div> : null}
    <div className="p-6 lg:p-8">{data.status === 'setup_required' ? <Empty>{data.message}</Empty> : null}
      {tab === 'rotation' && data.status === 'ready' ? <div className="grid gap-6 lg:grid-cols-[1.15fr_.85fr]"><div><div className="mb-4 flex items-center justify-between"><div><div className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-300">Aggregate positioning</div><h3 className="mt-1 text-xl font-semibold text-white">Sector rotation map</h3></div><span className="text-xs text-slate-500">Latest vs prior disclosed quarter</span></div><div className="space-y-2">{movers.length ? movers.slice(0, 12).map((row) => <div key={row.sector} className="grid grid-cols-[minmax(130px,1fr)_90px_90px] items-center gap-3 rounded-xl border border-white/10 bg-white/[0.025] px-4 py-3 text-sm"><span className="font-medium text-slate-200">{row.sector}</span><span className="text-right text-slate-400">{percent(row.current_weight)}</span><span className={`text-right font-semibold ${row.weight_change >= 0 ? 'text-emerald-300' : 'text-rose-300'}`}>{percent(row.weight_change, true)}</span></div>) : <Empty>Sector intelligence appears as SEC classifications are collected.</Empty>}</div></div><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-amber-300">Interpretation guardrail</div><h3 className="mt-2 text-xl font-semibold">What this signal means</h3><p className="mt-3 text-sm leading-6 text-slate-400">This measures changes in disclosed 13F long-equity value. It is not live positioning and does not reveal shorts, cash, swaps or a manager's full portfolio.</p><div className="mt-5 rounded-xl bg-black/20 p-4 text-xs leading-5 text-slate-500">{data.readiness?.methodology}</div></div></div> : null}
      {/* The backtester is withheld, not hidden. It advertised that it waits for public
          acceptance and uses adjusted prices; an audit found it entered on the acceptance
          date itself rather than the next tradable session, and that adjusted-price
          coverage for the tracked managers is 0%. Returns computed on that basis would be
          wrong in a direction that flatters the manager, so no number goes to a client
          until the entry rule and the price history are both fixed and tested. */}
      {tab === 'performance' ? <div className="rounded-2xl border border-amber-300/20 bg-amber-300/[0.04] p-6"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-amber-300">Withheld pending revalidation</div><h3 className="mt-2 text-xl font-semibold text-white">Performance results are not being published</h3><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">An internal audit found the filing-aware backtest entered positions on the SEC acceptance date itself rather than the next tradable session, and that adjusted closing prices are not yet loaded for the tracked managers. Either issue alone is enough to make a return figure misleading, so results are withheld rather than shown with a caveat.</p><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">The lab returns once entry timing runs off the next tradable session after public acceptance, price coverage is complete for the tested window, and the results reproduce against a known benchmark.</p></div> : null}
      {tab === 'filings' ? <div>{data.filing_events?.length ? <div className="grid gap-3 md:grid-cols-2">{data.filing_events.slice(0, 20).map((event) => <a key={event.id} href={event.source_url} target="_blank" rel="noreferrer" className="rounded-xl border border-white/10 bg-white/[0.03] p-4 hover:border-cyan-300/30"><div className="flex justify-between"><span className="rounded-full bg-cyan-300/10 px-2 py-1 text-[10px] font-bold text-cyan-300">{event.form_type}</span><span className="text-xs text-slate-500">{displayDate(event.filed_at)}</span></div><div className="mt-3 font-semibold">{event.ticker || event.event_type.replaceAll('_', ' ')}</div><div className="mt-1 text-xs capitalize text-slate-500">{event.event_type.replaceAll('_', ' ')}</div></a>)}</div> : <Empty>Run the research refresh to collect 13D/G and Form 4 disclosures from SEC EDGAR.</Empty>}</div> : null}
      {tab === 'briefs' ? <div>{data.approved_briefs?.length ? <div className="grid gap-4 md:grid-cols-2">{data.approved_briefs.map((brief) => <article key={brief.id} className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-emerald-300"><CheckCircle2 className="h-4 w-4" /> Analyst approved</div><h3 className="mt-3 text-lg font-semibold leading-6">{brief.headline}</h3><p className="mt-3 text-sm leading-6 text-slate-400">{brief.summary}</p><p className="mt-4 text-xs text-slate-500">Known after {displayDate(brief.evidence?.accepted_at)}</p></article>)}</div> : <Empty>Generated briefs stay private until an analyst approves every claim.</Empty>}</div> : null}
      {tab === 'workspace' ? <div className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-cyan-300">Saved fund groups</div><h3 className="mt-2 text-xl font-semibold">Compare managers you follow</h3><input value={groupName} onChange={(event) => setGroupName(event.target.value)} className="mt-5 w-full rounded-xl border border-white/10 bg-[#0d222d] px-3 py-3 text-sm" /><select value={managerSlug} onChange={(event) => setManagerSlug(event.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-[#0d222d] px-3 py-3 text-sm">{data.managers?.map((manager) => <option key={manager.id} value={manager.slug}>{manager.display_name}</option>)}</select><button type="button" onClick={async () => { setWorking('group'); try { const id = data.managers.find((row) => row.slug === managerSlug)?.id; await createInstitutionalGroup({ name: groupName, managerIds: id ? [id] : [] }); await loadWorkspace(); setMessage('Fund group saved.'); } catch (error) { setMessage(error.message); setWorking(''); } }} className="mt-3 rounded-xl bg-cyan-300 px-4 py-3 text-sm font-bold text-slate-950">Save group</button><div className="mt-5 space-y-2">{workspace?.groups?.map((group) => <div key={group.id} className="rounded-xl bg-black/20 px-4 py-3 text-sm">{group.name} <span className="text-slate-500">· {group.institutional_manager_group_members?.length || 0} managers</span></div>)}</div></div>
        <div className="rounded-2xl border border-white/10 bg-white/[0.035] p-5"><div className="text-[10px] font-bold uppercase tracking-[.2em] text-amber-300">Watchlists and alerts</div><h3 className="mt-2 text-xl font-semibold">Get disclosure changes that matter</h3><input value={watchlistName} onChange={(event) => setWatchlistName(event.target.value)} className="mt-5 w-full rounded-xl border border-white/10 bg-[#0d222d] px-3 py-3 text-sm" /><input value={watchTickers} onChange={(event) => setWatchTickers(event.target.value)} className="mt-3 w-full rounded-xl border border-white/10 bg-[#0d222d] px-3 py-3 text-sm" /><button type="button" onClick={async () => { setWorking('watchlist'); try { await createInstitutionalWatchlist({ name: watchlistName, items: watchTickers.split(',').map((value) => value.trim()).filter(Boolean) }); await loadWorkspace(); setMessage('Watchlist saved.'); } catch (error) { setMessage(error.message); setWorking(''); } }} className="mt-3 rounded-xl bg-amber-300 px-4 py-3 text-sm font-bold text-slate-950">Save watchlist</button><div className="mt-5 space-y-2">{workspace?.alerts?.slice(0, 8).map((alert) => <button key={alert.id} type="button" onClick={async () => { await markInstitutionalPersonalizedAlert(alert.id); await loadWorkspace(); }} className="flex w-full items-start gap-3 rounded-xl bg-black/20 px-4 py-3 text-left"><Bell className={`mt-0.5 h-4 w-4 ${alert.is_read ? 'text-slate-600' : 'text-amber-300'}`} /><span><span className="block text-sm font-semibold">{alert.title}</span><span className="mt-1 block text-xs text-slate-500">{alert.body}</span></span></button>)}</div>{!workspace && working !== 'workspace' ? <button type="button" onClick={loadWorkspace} className="mt-4 text-xs font-semibold text-cyan-300">Sign in and load my workspace</button> : null}</div></div> : null}
    </div>
  </section>;
}
