import {useMemo,useState} from 'react';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,ReferenceLine} from 'recharts';
import history from '../data/jpm-factor-history.json';
import {FACTORS,factorWindow,startForPeriod,researchAxis} from '../lib/factorHistory.mjs';
import './FactorHistory.css';
const pct=v=>`${v>=0?'+':''}${v.toFixed(2)}%`;
const fmt=d=>new Date(typeof d==='number'?d:`${d}T00:00:00Z`).toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'});
function Chart({points,factors,selected,label}){
 const axis=researchAxis(points,factors.map(([key])=>key));
 const tick=n=>new Intl.NumberFormat('en-GB',{maximumFractionDigits:axis.decimals}).format(n);
 return <div className="factor-history-chart" role="img" aria-label={label}><ResponsiveContainer width="100%" height="100%"><LineChart data={points} accessibilityLayer margin={{top:15,right:18,bottom:8,left:0}}><CartesianGrid vertical={false} stroke="#e5eaf0" strokeDasharray="3 3"/><XAxis dataKey="timestamp" type="number" scale="time" domain={[points[0].timestamp,points.at(-1).timestamp]} minTickGap={65} tick={{fontSize:11}} tickFormatter={d=>fmt(d)}/><YAxis domain={axis.domain} ticks={axis.ticks} width={68} tick={{fontSize:11}} tickFormatter={tick}/><ReferenceLine y={100} stroke="#a2acb5" strokeDasharray="4 4"/><Tooltip labelFormatter={(label,payload)=>`${fmt(Number(label))}${payload?.[0]?.payload?.referenceOnly?' · rebasing reference':''}`} formatter={(v,n)=>[`${Number(v).toFixed(2)} (${pct(Number(v)-100)})`,n]}/>{factors.map(([key,name,color])=><Line key={key} name={name} dataKey={key} type="linear" stroke={color} strokeWidth={key===selected?3:1.5} dot={false} isAnimationActive={false}/>)}</LineChart></ResponsiveContainer></div>;
}
export default function FactorHistory({portfolioId}){
 const selected=FACTORS.find(([key])=>portfolioId===`in-${key}`);
 const [period,setPeriod]=useState('all'),[from,setFrom]=useState('2026-01-01'),[to,setTo]=useState(history.asOf);
 const end=period==='custom'?to:history.asOf,start=period==='custom'?from:startForPeriod(end,period);
 const result=useMemo(()=>factorWindow(history,start,end),[start,end]);
 if(!selected)return null;
 return <section className="factor-history" aria-label="JPM factor research history"><div className="factor-history-heading"><div><span className="pf-eyebrow">THE FACTOR IDEA · HISTORICAL RESEARCH</span><h3>JPM factor research history</h3><p>Workbook observations through {fmt(history.asOf)}. Your AGI portfolio tracking appears separately below.</p></div><span className="factor-history-badge">Workbook snapshot</span></div><p className="factor-history-source-note"><strong>Main data sheet selected.</strong> Excel’s saved chart conflicts with this sheet on 14 August 2026. The original source difference remains unresolved; the comparison below shows its effect. These are research series, not AGI portfolio returns.</p>
 <div className="factor-history-filters" role="group" aria-label="Research chart period">{[['30D','30 days'],['3M','3 months'],['6M','6 months'],['1Y','1 year'],['3Y','3 years'],['5Y','5 years'],['all','Since 2010'],['custom','Custom']].map(([v,label])=><button key={v} type="button" aria-pressed={period===v} onClick={()=>setPeriod(v)}>{label}</button>)}</div>
 {period==='custom'&&<div className="factor-history-dates"><label>From <input type="date" value={from} min={history.baselineDate} max={history.asOf} onInput={e=>setFrom(e.currentTarget.value)} onChange={e=>setFrom(e.target.value)}/></label><label>Through <input type="date" value={to} min={history.baselineDate} max={history.asOf} onInput={e=>setTo(e.currentTarget.value)} onChange={e=>setTo(e.target.value)}/></label></div>}
 {result.error?<p role="status">{result.error}</p>:<><p className="factor-history-range">{fmt(result.start)} – {fmt(result.end)} · rebased to 100 · cumulative research change</p>{result.hasSyntheticBaseline&&<p className="factor-history-source-note">The 1 January 2010 point is a 100 reference, not an observed return. Excel has an error on that date; valid observations begin 4 January 2010.</p>}{result.includesSourceConflict&&<p className="factor-history-range">This period includes the disputed 14 August observation and follows the main sheet.</p>}<div className="factor-history-grid"><article><div className="factor-history-card-heading"><h4>{selected[1]}</h4><strong style={{color:selected[2]}}>{pct(result.returns[selected[0]])}</strong></div><Chart points={result.points} factors={[selected]} selected={selected[0]} label={`${selected[1]} historical research index`}/></article><article><div className="factor-history-card-heading"><h4>Compare all five factors</h4><span>Same dates · same starting value</span></div><Chart points={result.points} factors={FACTORS} selected={selected[0]} label="Comparison of five historical factor research series"/></article></div><div className="factor-history-returns">{FACTORS.map(([key,name,color])=><div key={key}><span><i style={{background:color}}/>{name}</span><strong>{pct(result.returns[key])}</strong></div>)}</div></>}
 <details className="factor-history-method"><summary>Source comparison, calculation and workbook checks</summary><p><strong>Saved-chart reconciliation: 31 December 2025 reference through 14 August 2026.</strong> All earlier helper observations match; the terminal day differs. Neither version has been independently confirmed by the publisher.</p><div className="factor-history-source-table"><table><thead><tr><th>Factor</th><th>Saved Excel chart</th><th>Main sheet used here</th><th>Difference (pp)</th></tr></thead><tbody>{history.reconciliation.map(r=><tr key={r.factor}><th>{FACTORS.find(([key])=>key===r.factor)?.[1]}</th><td>{pct(r.returnPct)}</td><td>{pct(r.sourceReturnPct)}</td><td>{(r.sourceReturnPct-r.returnPct).toFixed(2)}</td></tr>)}</tbody></table></div><p>Source: {history.source}, “Factor Performance”, columns N–R. Each index compounds the supplied daily observations: previous index × (1 + daily value). Period change = final rebased index − 100. Periods end at the workbook’s latest date, not today. A start date means the close of that date; its daily change is excluded. A non-observation start uses the preceding available date. Lines use actual calendar spacing and straight segments; no intermediate returns are estimated.</p><p>These are historical factor research series, not the returns of today’s AGI holdings. The workbook does not establish the full long/short construction, fees or investability; no claim of an investable portfolio return is made.</p><p>Recheck: the saved chart’s 14 August 2026 observations differ from the main data sheet. These charts consistently use the main data sheet. Its 1 January 2010 cells contain #NAME?; 100 is only a starting reference on that date, and valid compounding begins 4 January 2010. No missing prices or returns are estimated.</p><p>All 815 cached comparison-chart points were reproduced from their saved helper data. The source discrepancy remains disclosed rather than adjusted to match the screenshot.</p></details>
 </section>;
}
