import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {ResponsiveContainer,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip} from 'recharts';
import {API_ORIGIN} from '@/config';
import './IndiaPortfolios.css';
const date=v=>v?new Date(v).toLocaleString('en-IN',{timeZone:'Asia/Kolkata',dateStyle:'medium',timeStyle:'short'})+' IST':'—';
const money=v=>v==null?'—':new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v);
const pct=v=>v==null?'—':`${v>=0?'+':''}${v.toFixed(2)}%`;
const labels={scheduled:'Scheduled · 5 October 2026',awaiting_fresh_prices:'Waiting for fresh launch quotes',start_missed:'Launch not recorded · administrator review needed',awaiting_daily:'Waiting for the first 4 pm update',daily_recorded:'Daily prices recorded',daily_pending:'Latest daily update pending · showing previous record'};
export function useIndiaTracking(){const [data,setData]=useState(null),[error,setError]=useState('');useEffect(()=>{let active=true,controller;async function refresh(){controller=new AbortController();try{const r=await fetch(`${API_ORIGIN||''}/api/portfolios/india-tracking`,{signal:controller.signal,cache:'no-store'});const d=await r.json();if(!r.ok||!Array.isArray(d.portfolios))throw Error(d.error||'Daily tracking temporarily unavailable');if(active){setData(d);setError('');}}catch(e){if(active&&e.name!=='AbortError')setError(e.message);}}refresh();const timer=setInterval(refresh,60000);return()=>{active=false;clearInterval(timer);controller?.abort();};},[]);return {data,error};}
function pointsFor(t,stock){if(!t?.startedAt)return [];const points=[{date:t.startedAt,value:stock?stock.basePrice:100}];return points.concat((stock?.history||t.history||[]).map(h=>({date:`${h.date}T16:00:00+05:30`,value:stock?h.price:h.nav})));}
function PriceChart({points=[],title,base=100,stock=false,compact=false}){
 const [period,setPeriod]=useState('All'),[mode,setMode]=useState('price');
 const last=points.at(-1),cut=last?new Date(last.date):new Date();
 if(period!=='All')cut.setUTCMonth(cut.getUTCMonth()-Number(period));
 const data=points.filter(p=>period==='All'||new Date(p.date)>=cut).map(p=>({...p,label:new Date(p.date).toLocaleDateString('en-IN',{timeZone:'Asia/Kolkata',day:'numeric',month:'short',year:'2-digit'}),value:mode==='return'?(p.value/base-1)*100:p.value}));
 return <section className={`india-chart ${compact?'india-chart-mini':''}`} aria-label={title}>
 {!compact&&<div className="india-chart-toolbar"><h3>{title}</h3><div><label>Period <select aria-label={`${title} period`} value={period} onChange={e=>setPeriod(e.target.value)}>{[['1','1M'],['3','3M'],['6','6M'],['12','1Y'],['All','Since launch']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label> Display <select aria-label={`${title} display`} value={mode} onChange={e=>setMode(e.target.value)}><option value="price">{stock?'Price · ₹':'Portfolio index · starts at 100'}</option><option value="return">Return · %</option></select></label></div></div>}
 {data.length?<><div style={{height:compact?110:290,width:'100%'}}><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{top:12,right:18,left:0,bottom:5}} accessibilityLayer><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e5eaf0"/>{!compact&&<XAxis dataKey="label" minTickGap={35} tick={{fontSize:11}}/>}<YAxis hide={compact} domain={['auto','auto']} tick={{fontSize:11}} tickFormatter={n=>Number(n).toFixed(mode==='return'?1:2)}/><Tooltip labelFormatter={(_,payload)=>payload?.[0]?date(payload[0].payload.date):''} formatter={v=>[mode==='return'?pct(v):stock?money(v):Number(v).toFixed(2),mode==='return'?'Since launch':stock?'Price':'Portfolio index']}/><Line type="linear" dataKey="value" stroke="#147c73" strokeWidth={2.5} dot={data.length<3?{r:4}:false} activeDot={{r:5}} isAnimationActive={false}/></LineChart></ResponsiveContainer></div>{!compact&&<small>Daily observations. Returns use the original launch price; changing the chart period does not reset the return. Missing sessions are not estimated.</small>}</>:<div className="india-chart-empty" style={{minHeight:compact?100:230}}><span>↗</span><strong>Waiting for recorded prices</strong><small>First daily point after 4 pm IST on launch day. No simulated history.</small></div>}
 </section>;
}
export default function IndiaPortfolios({portfolios,admin}){const {data,error}=useIndiaTracking();return <section className="pf-explorer india-portfolios"><div className="pf-explorer-intro"><div><span className="pf-eyebrow">INDIA · RESEARCH PORTFOLIOS</span><h2>Explore India portfolios.</h2><p>Daily stock prices, portfolio charts and returns from launch.</p></div>{admin&&<Link className="pf-button" to="/admin/portfolios">Manage portfolios ↗</Link>}</div><div className="pf-evidence-strip"><div><strong>Daily update · 4:00 pm IST</strong><span>Starts Monday, 5 October 2026 · Upstox daily candles · trading days only</span></div></div>{error&&<p className="pf-warning" role="alert">{error}</p>}<div className="pf-explorer-grid">{portfolios.map(p=>{const t=data?.portfolios.find(x=>x.id===p.id);return <article className="pf-explore-card india-card" key={p.id}><div className="india-card-body"><span className="pf-eyebrow">{p.category||'AGI RESEARCH PORTFOLIO'}</span><Link className="pf-card-title" to={`/portfolios/india/${p.id}`}><h3>{p.name}</h3><span>↗</span></Link><p>{p.description}</p><div className="pf-card-stat-grid"><div><span>Since launch · price return</span><strong>{pct(t?.returnPct)}</strong></div><div><span>Stocks</span><strong>{p.holdings.filter(h=>h.assetType!=='gold_etf').length}{p.holdings.some(h=>h.assetType==='gold_etf')?' + gold ETF':''}</strong></div></div><PriceChart compact title={`${p.name} composite chart`} points={pointsFor(t)}/><p>{labels[t?.status]||'Checking tracking status…'}</p>{t?.priceDate&&<small>Prices dated {t.priceDate} · recorded {date(t.markedAt)}</small>}</div><footer><span>{p.holdings.filter(h=>h.assetType!=='gold_etf').reduce((s,h)=>s+h.weight,0).toFixed(2)}% equities{p.holdings.some(h=>h.assetType==='gold_etf')?' · 2% GOLDBEES':''}</span><Link to={`/portfolios/india/${p.id}`}>View charts →</Link></footer></article>;})}</div><p className="pf-footnote">Factor portfolios use supplied ranks, sectors and market-cap snapshots; inputs remain partly unverified. Preferred uses an approximately equal-weight allocation of the 17 supplied preferred picks. All-Weather combines equity factors. Returns are hypothetical price returns before fees and taxes; dividends and corporate actions require separate review.</p></section>;}
export function IndiaPortfolioDetail({portfolio:p,admin}){
 const {data,error}=useIndiaTracking(),[selected,setSelected]=useState(p.holdings[0]?.symbol);
 const t=data?.portfolios.find(x=>x.id===p.id),holdings=t?.positions||p.holdings,stock=holdings.find(h=>h.symbol===selected)||holdings[0];
 return <section className="india-portfolios"><Link to="/portfolios/india">← India portfolios</Link><div className="pf-heading"><div><span className="pf-eyebrow">INDIA · RESEARCH PORTFOLIO</span><h2>{p.name}</h2><p>{p.description}</p></div>{admin&&<Link className="pf-button" to={`/admin/portfolios?edit=${p.id}`}>Manage allocation</Link>}</div>{error&&<p role="alert" className="pf-warning">{error}</p>}<div className="pf-evidence-strip"><div><strong>{labels[t?.status]||'Checking tracking status…'}</strong><span>Prices update at 4 pm IST on trading days. Missing candles are retried.</span><span>Launch: {t?.startedAt?date(t.startedAt):'5 October 2026 · first complete fresh quote batch after 9:15 am IST'}</span><span>Last daily update: {date(t?.markedAt)}</span></div></div>
 <div className="india-metrics"><div><span>Portfolio index · launch = 100</span><strong>{t?.nav?.toFixed(2)||'—'}</strong></div><div><span>Return since launch</span><strong>{pct(t?.returnPct)}</strong></div><div><span>Change since prior recorded value</span><strong>{pct(t?.dayReturnPct)}</strong></div></div>
 <PriceChart title="Composite portfolio" points={pointsFor(t)}/>
 <div className="india-stock-selector"><h3>Individual stock charts</h3><label>Choose holding <select aria-label="Choose holding" value={stock?.symbol||''} onChange={e=>setSelected(e.target.value)}>{holdings.map(h=><option key={h.symbol} value={h.symbol}>{h.symbol} · {h.name}</option>)}</select></label></div>
 <div className="india-metrics"><div><span>{stock?.symbol} · daily price</span><strong>{money(stock?.price)}</strong></div><div><span>Return since launch</span><strong>{pct(stock?.returnPct)}</strong></div><div><span>Price date</span><strong>{stock?.priceDate||'—'}</strong></div></div>
 <PriceChart key={stock?.symbol} stock title={`${stock?.symbol||'Stock'} price history`} base={stock?.basePrice||1} points={pointsFor(t,stock)}/>
 <h3>Holdings & returns</h3><p>Select any ticker to view its chart. Each stock keeps its own daily history, even while another holding's price is pending.</p><div className="pf-holdings" style={{overflowX:'auto'}}><table><thead><tr><th>Stock / chart</th><th>Sector</th><th>Target weight</th><th>Launch price</th><th>Daily price</th><th>Since launch</th><th>Price date</th></tr></thead><tbody>{holdings.map(h=><tr key={h.symbol}><td><strong>{h.name}</strong><br/><button type="button" className="india-ticker" onClick={()=>setSelected(h.symbol)} aria-pressed={stock?.symbol===h.symbol}>{h.symbol} ↗</button></td><td>{h.sector||'—'}</td><td>{h.weight.toFixed(2)}%</td><td>{money(h.basePrice)}</td><td>{money(h.price)}</td><td>{pct(h.returnPct)}</td><td>{h.priceDate||'Awaiting daily update'}</td></tr>)}</tbody></table></div>
 <details className="india-method"><summary>How prices, charts and returns are calculated</summary><p>{p.weightMethod}</p><p>Launch prices establish fixed fractional units. Composite index = sum of each launch weight × daily price / launch price, plus any cash weight. It starts at 100; return = index − 100. Stock return = (daily price / launch price − 1) × 100.</p><p>Collection begins at 4 pm IST, using the dated Upstox daily candle close, not a previous-session quote. One point is recorded per trading day. Missing prices are retried every five minutes after 4 pm; up to seven calendar days are recovered after an interruption. A portfolio point is published only when all its prices are available. This is not a tick chart or a guarantee of exchange-certified closing prices.</p><p>Before fees and taxes. Dividends and corporate-action adjustments are not automated; splits, demergers and symbol changes require review. Dated rebalancing is not yet enabled; launched holdings are protected from direct edits. {p.id==='in-preferred'?'Selection follows the supplied research summary; AGI sets the weights. This is not a J.P. Morgan managed portfolio.':'Factor inputs remain partly unverified.'}</p></details>
 {t?.history?.length>0&&<details className="india-method"><summary>Recorded portfolio values</summary><table><thead><tr><th>Date</th><th>Index</th><th>Since launch</th></tr></thead><tbody>{t.history.map(h=><tr key={h.date}><td>{h.date}</td><td>{h.nav.toFixed(2)}</td><td>{pct(h.nav-100)}</td></tr>)}</tbody></table></details>}
 </section>;
}
