import {usaHistoryURL} from './USPortfolioTracking';
import {PriceChart} from './IndiaPortfolios';
import {HoldingLogos} from '@/components/CompanyLogo';
import { useEffect, useMemo, useRef, useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, Search, X, Dna, ShieldCheck, Cpu, Cloud, Globe2, Landmark, Layers3, Rocket, HeartPulse, Zap, Gem, TrendingUp, Building2, Wallet, Coins, Car, Atom, Sprout, Factory, SlidersHorizontal, CheckCircle2, BarChart3 } from 'lucide-react';
import { portfolioReturn, HORIZONS } from '@/lib/portfolioHistory';
const THEMES={
 genomics:[Dna,'mint','Companies working on genetic research, diagnostics and new approaches to treating disease.'],
 cybersecurity:[ShieldCheck,'blue','Security software and infrastructure protecting identities, applications and digital networks.'],
 'artificial-intelligence':[Cpu,'violet','The chips, software and computing infrastructure supporting the adoption of artificial intelligence.'],
 'us-top10':[TrendingUp,'mint','Ten US businesses selected by AGI for quality and long-term growth.'],
 'cloud-computing':[Cloud,'gold','Software platforms, cloud services and infrastructure supporting the shift to connected computing.'],
 'big-tech':[Globe2,'blue','Large technology companies spanning platforms, computing, commerce and digital services.'],
 'aging':[HeartPulse,'rose','Healthcare, medical technology and care facilities serving an aging population.'],
 'all-weather':[Layers3,'blue','An allocation across equities, bonds, gold and commodities with different economic sensitivities.'],
 'alphabet-strategy':[Building2,'violet','A dated reference basket inspired by Alphabet’s disclosed investment holdings.'],
 'berkshire-strategy':[Landmark,'gold','A reference basket inspired by Berkshire Hathaway’s disclosed public equity investments.'],
 'blackrock-smart-beta':[SlidersHorizontal,'blue','Factor ETFs combining different equity characteristics, including quality, value and momentum.'],
 'blockchain-ecosystem':[Coins,'violet','Businesses exposed to digital assets, mining, exchanges and blockchain infrastructure.'],
 'clean-energy':[Sprout,'mint','Companies participating in renewable power, electrification and energy technology.'],
 'critical-minerals':[Gem,'gold','Mining and materials businesses supplying minerals used across industry and electrification.'],
 'defense-security':[ShieldCheck,'blue','Aerospace, defence and security businesses supplying equipment, systems and services.'],
 deglobalization:[Factory,'gold','Industrial and infrastructure businesses exposed to changes in manufacturing and supply chains.'],
 'digital-cash':[Wallet,'mint','Payment networks and financial platforms enabling digital transactions and services.'],
 'electric-vehicles':[Car,'blue','Vehicle manufacturers and component suppliers exposed to electric mobility.'],
 'gates-strategy':[Landmark,'violet','A reference basket inspired by the Gates Trust’s disclosed public investments.'],
 'global-multi-asset-aggressive':[Globe2,'rose','An equity-oriented global multi-asset allocation. Review the actual holdings and weights.'],
 'global-multi-asset-conservative':[Layers3,'mint','A global multi-asset allocation with a larger defensive sleeve; capital is still at risk.'],
 'global-multi-asset-moderate':[Layers3,'blue','A global allocation combining equities and fixed income. Review the balance between sleeves.'],
 moat:[Building2,'gold','A selection of businesses assessed through the lens of competitive advantage.'],
 'nuclear-energy':[Atom,'mint','Uranium, nuclear technology and power businesses participating in the nuclear energy ecosystem.'],
 'space-tech':[Rocket,'violet','Satellite, launch and related technology businesses exposed to the space economy.'],
 'swensen-portfolio':[Layers3,'gold','An endowment-inspired allocation across domestic and international equities, bonds and real estate.']
};
const categoryLabel=c=>({'Themes':'Megatrends','Multi-asset':'Multi-asset','Factors & selection':'Strategies','Investor-inspired':'Investor-inspired'}[c]||c);
const pct=v=>`${v>=0?'+':''}${v.toFixed(2)}%`;
const PERIODS=['since',...HORIZONS];
const periodLabel=m=>m==='since'?'Since 15 Sep':m===12?'1Y':`${m}M`;
export default function PortfolioExplorer({portfolios,market,admin}){
 const [search,setSearch]=useState(''),[category,setCategory]=useState('All'),[months,setMonths]=useState('since'),[sort,setSort]=useState('name'),[coveredOnly,setCoveredOnly]=useState(false),[selected,setSelected]=useState([]),[showCompare,setShowCompare]=useState(false),[data,setData]=useState(null),[error,setError]=useState(''),[retry,setRetry]=useState(0);
 const compareRef=useRef(null);
 useEffect(()=>{if(market!=='usa')return;const c=new AbortController();setError('');fetch(usaHistoryURL,{signal:c.signal,cache:'no-cache'}).then(r=>{if(!r.ok)throw Error('Price history unavailable');return r.json();}).then(d=>{if(d.schemaVersion!==1)throw Error('Unsupported price snapshot');setData(d);}).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>c.abort();},[market,retry]);
 const calculated=useMemo(()=>new Map(portfolios.map(p=>[p.id,data?Object.fromEntries(PERIODS.map(m=>[m,portfolioReturn(data,p,m)])):{}])),[data,portfolios]);
 const visible=useMemo(()=>portfolios.filter(p=>(category==='All'||p.category===category)&&`${p.name} ${p.description} ${p.holdings.map(h=>`${h.name} ${h.symbol}`).join(' ')}`.toLowerCase().includes(search.toLowerCase())&&(!coveredOnly||(calculated.get(p.id)?.[months]&&!calculated.get(p.id)[months].reason))).sort((a,b)=>{
  if(sort==='name')return a.name.localeCompare(b.name);if(sort==='holdings')return b.holdings.length-a.holdings.length||a.name.localeCompare(b.name);
  const av=calculated.get(a.id)?.[months],bv=calculated.get(b.id)?.[months];const aok=av&&!av.reason,bok=bv&&!bv.reason;if(!aok||!bok)return (bok?1:0)-(aok?1:0)||a.name.localeCompare(b.name);
  return (sort==='drawdown'?av.maxDrawdownPct-bv.maxDrawdownPct:bv.returnPct-av.returnPct)||a.name.localeCompare(b.name);
 }),[portfolios,category,search,coveredOnly,sort,calculated,months]);
 const chosen=portfolios.filter(p=>selected.includes(p.id));const complete=portfolios.filter(p=>calculated.get(p.id)?.[months]&&!calculated.get(p.id)[months].reason).length;
 const toggle=id=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):s.length<3?[...s,id]:s);
 const clearFilters=()=>{setSearch('');setCategory('All');setCoveredOnly(false);setSort('name');};
 const openComparison=()=>{setShowCompare(true);requestAnimationFrame(()=>compareRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));};
 const isStale=data&&Date.now()-Date.parse(data.asOf+'T00:00:00Z')>7*86400000;
 return <section className="pf-explorer">
  <div className="pf-explorer-intro"><div><span className="pf-eyebrow">{market==='usa'?'UNITED STATES':'INDIA'} · RESEARCH COLLECTION</span><h2>Explore portfolios</h2><p>Find an idea. Compare the evidence. Look inside the allocation.</p></div><div className="pf-explorer-actions">{market==='usa'&&<a href="/research/portfolio-performance.html" className="pf-outline-link">Full performance report <ArrowUpRight size={16}/></a>}{admin&&<Link to="/admin/portfolios" className="pf-button">Manage portfolios <ArrowUpRight size={16}/></Link>}</div></div>
  {market==='usa'&&data?.refresh?.error&&<p className="pf-warning" role="status">{data.refresh.error} Returns remain dated through {data.asOf}.</p>}
  {market==='usa'&&<div className="pf-evidence-strip"><BarChart3 size={20}/><div><strong>Daily portfolio tracking from 15 September 2026</strong><span>{data?`Since 15 Sep: continuous model record; other periods: current-allocation simulations · Prices through ${data.asOf} · USD · before fees and taxes · daily refresh after 5 pm New York`:'Price snapshot loading…'}{isStale?' · Snapshot over 7 days old':''}</span></div><span className="pf-evidence-count">{data?`${complete}/${portfolios.length} complete for ${periodLabel(months)}`:'Checking coverage'}</span></div>}
  {error&&<p className="pf-warning" role="alert">{error}. Allocations remain available; no returns are estimated. <button onClick={()=>setRetry(r=>r+1)}>Retry prices</button></p>}
  <div className="pf-explorer-toolbar"><div className="pf-search-wrap"><Search size={19}/><input aria-label="Search portfolios or holdings" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search portfolios, companies or tickers…"/>{search&&<button aria-label="Clear search" onClick={()=>setSearch('')}><X size={16}/></button>}</div><div className="pf-period-picker" aria-label="Return period">{PERIODS.map(m=><button key={m} aria-pressed={months===m} onClick={()=>setMonths(m)}>{periodLabel(m)}</button>)}</div><label className="pf-sort-label">Sort by<select aria-label="Sort portfolios" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="return">Highest backtested return</option><option value="drawdown">Lowest historical drawdown</option><option value="holdings">Number of holdings</option></select></label></div>
  <div className="pf-explorer-filters"><div className="pf-category-pills" aria-label="Portfolio categories">{['All',...new Set(portfolios.map(p=>p.category))].map(c=><button key={c} aria-pressed={category===c} onClick={()=>setCategory(c)}>{categoryLabel(c)}<span>{c==='All'?portfolios.length:portfolios.filter(p=>p.category===c).length}</span></button>)}</div>{market==='usa'&&<label className="pf-coverage-toggle"><input type="checkbox" checked={coveredOnly} onChange={e=>setCoveredOnly(e.target.checked)}/>Complete {periodLabel(months)} history only</label>}</div>
  <div className="pf-results-line"><span aria-live="polite">{visible.length} portfolios{category!=='All'?` · ${categoryLabel(category)}`:''}</span><span>Select up to 3 to compare{(search||category!=='All'||coveredOnly||sort!=='name')&&<> · <button onClick={clearFilters}>Reset filters</button></>}</span></div>
  {showCompare&&chosen.length>0&&<section ref={compareRef} className="pf-compare-panel" aria-label="Portfolio comparison"><header><div><span className="pf-eyebrow">SIDE BY SIDE</span><h3>Compare your shortlist</h3></div><button aria-label="Close comparison" onClick={()=>setShowCompare(false)}><X size={20}/></button></header><div className="pf-compare-scroll"><table><thead><tr><th>Metric</th>{chosen.map(p=><th key={p.id}><Link to={`/portfolios/${market}/${p.id}`}>{p.name} ↗</Link></th>)}</tr></thead><tbody><tr><th>Category</th>{chosen.map(p=><td key={p.id}>{categoryLabel(p.category)}</td>)}</tr><tr><th>Holdings</th>{chosen.map(p=><td key={p.id}>{p.holdings.length}</td>)}</tr>{PERIODS.map(m=><tr key={m}><th>{periodLabel(m)} backtested return</th>{chosen.map(p=>{const r=calculated.get(p.id)?.[m];return <td key={p.id}>{r&&!r.reason?pct(r.returnPct):r?.isNew?'New':'Unavailable'}</td>;})}</tr>)}<tr><th>{periodLabel(months)} max drawdown</th>{chosen.map(p=>{const r=calculated.get(p.id)?.[months];return <td key={p.id}>{r&&!r.reason?`${r.maxDrawdownPct.toFixed(2)}%`:r?.isNew?'New':'Unavailable'}</td>;})}</tr><tr><th>{periodLabel(months)} covered weight</th>{chosen.map(p=><td key={p.id}>{calculated.get(p.id)?.[months]?.covered.toFixed(2)??'—'}%</td>)}</tr><tr><th>Top holdings by weight</th>{chosen.map(p=><td key={p.id}>{[...p.holdings].sort((a,b)=>b.weight-a.weight).slice(0,3).map(h=><div key={h.name}>{h.name} · {h.weight.toFixed(2)}%</div>)}</td>)}</tr></tbody></table></div><p>Each period starts with the current stocks and weights and holds them without rebalancing. Editing the allocation recalculates these backtests; they are separate from a since-launch track record. Lower past drawdown does not establish a lower future risk.</p></section>}
  <div className="pf-explorer-grid">{visible.map(p=>{const [Icon,tone,desc]=THEMES[p.id]||[Layers3,'blue','Explore the portfolio’s current holdings, target weights and available historical evidence.'];const r=calculated.get(p.id)?.[months],ready=r&&!r.reason;return <article className="pf-explore-card" key={p.id}>
   <div className="pf-explore-card-top"><div className={`pf-theme-icon ${tone}`}><Icon size={30} strokeWidth={1.5}/></div><label className="pf-compare-check"><input type="checkbox" aria-label={`Compare ${p.name}`} checked={selected.includes(p.id)} disabled={selected.length>=3&&!selected.includes(p.id)} onChange={()=>toggle(p.id)}/>Compare</label></div>
   <Link className="pf-card-title" to={`/portfolios/${market}/${p.id}`}><h3>{p.name}</h3><ArrowUpRight size={19}/></Link><p className="pf-card-description">{p.description||(p.customized?'A customised AGI allocation. Open the portfolio to review its current holdings and weights.':desc)}</p>
   <div className="pf-card-stat-grid"><div><span>{periodLabel(months)} {months==='since'?'model return':'backtested return'}</span><strong className={ready?(r.returnPct>=0?'pf-positive':'pf-negative'):'pf-muted'}>{ready?pct(r.returnPct):data?(r?.isNew?'New':'Unavailable'):'—'}</strong></div><div><span>{periodLabel(months)} max drawdown</span><strong className="pf-drawdown">{ready?`${r.maxDrawdownPct.toFixed(2)}%`:'—'}</strong></div></div>
   <div className={`pf-card-coverage ${ready?'complete':'partial'}`}>{ready?<><CheckCircle2 size={14}/><span>Complete price history</span></>:<><span className="pf-status-dot"/><span>{p.incomplete?'Incomplete allocation':r?.isNew?'New listing · more history needed':r?`${r.covered.toFixed(2)}% weight covered · review gaps`:error?'Prices unavailable':market==='usa'?'Checking history…':'History not connected'}</span></>}</div>
   {ready&&<PriceChart compact title={`${p.name} composite performance`} currency="USD" startLabel="Since 15 Sep" points={r.curve.map(v=>({date:v.date+'T12:00:00Z',value:v.value*100}))}/>}
   <HoldingLogos market={market} holdings={[...p.holdings].sort((a,b)=>b.weight-a.weight)}/><footer><div><span>{categoryLabel(p.category)}</span><b>{p.holdings.length} holdings · {p.customized?'AGI custom':'Reference basket'}</b></div><Link aria-label={`Explore ${p.name}`} to={`/portfolios/${market}/${p.id}`}><ArrowUpRight size={20}/></Link></footer>
  </article>;})}</div>
  {!visible.length&&<div className="pf-empty"><Search size={28}/><h3>{portfolios.length?'No portfolios match these filters':'No portfolios published yet'}</h3><p>{portfolios.length?'Try another company, category or coverage setting.':'Use the admin editor to create a portfolio and publish its allocation.'}</p>{portfolios.length>0&&<button className="pf-button" onClick={clearFilters}>Reset filters</button>}</div>}
  {chosen.length>0&&<div className="pf-compare-tray"><div><strong>{chosen.length}/3 selected</strong><span>{chosen.map(p=>p.name).join(' · ')}</span></div><button onClick={()=>{setSelected([]);setShowCompare(false);}}>Clear</button><button className="pf-button" onClick={openComparison}>Compare {chosen.length} <ArrowUpRight size={16}/></button></div>}
  <p className="pf-explorer-disclosure">Historical simulation using current allocations. Cards describe portfolio exposure, not a suitability rating. Historical simulations exclude fees, taxes and currency conversion; research candidates have no allocation.</p>
  <details className="pf-explorer-disclosure"><summary>Portfolio sources and methodology</summary><p>Initial USA reference allocations were captured from Vested on 2 October 2026. Custom allocations are identified separately. No affiliation or endorsement is implied. Individual portfolio pages preserve their source and capture date.</p></details>
 </section>;
}
