import {useEffect,useState} from 'react';
import CompanyLogo from './CompanyLogo';
import {PriceChart} from './IndiaPortfolios';
import {portfolioReturn,USA_START} from '@/lib/portfolioHistory';
import {API_ORIGIN} from '@/config';
const pct=v=>v==null?'—':`${v>=0?'+':''}${v.toFixed(2)}%`;
const usd=v=>v==null?'—':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(v);
export const usaHistoryURL=`${API_ORIGIN||''}/api/portfolios/usa-history`;
export default function USPortfolioTracking({portfolio}){
 const [data,setData]=useState(null),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();async function read(){try{const r=await fetch(usaHistoryURL,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error('Price history temporarily unavailable');const d=await r.json();if(d.schemaVersion!==1)throw Error('Unsupported price history');setData(d);setError('');}catch(e){if(e.name!=='AbortError')setError(e.message);}}read();const timer=setInterval(read,300000);return()=>{clearInterval(timer);c.abort();};},[]);
 const r=data?portfolioReturn({...data,ledgers:undefined},portfolio,'since'):null;
 const points=r?.curve?.map(p=>({date:p.date+'T12:00:00Z',value:p.value*100}))||[];
 return <section className="pf-performance india-portfolios"><span className="pf-eyebrow">USA · DAILY PORTFOLIO TRACKING · USD</span><h2>Performance from 15 September 2026</h2><p>Current holdings and starting weights, held from the 15 September close. This historical simulation recalculates when holdings change; it is not an actual investor or rebalanced fund track record.</p><div className="pf-evidence-strip"><div><strong>Yahoo Finance · daily adjusted close</strong><span>Automatic refresh after 5 pm New York · US trading sessions · {data?`Prices through ${data.asOf}`:'Loading prices…'}</span></div></div>{(error||data?.refresh?.error)&&<p className="pf-warning" role="alert">{error||data.refresh.error}. Last successful dated data remains visible.</p>}
 {data&&Date.now()-Date.parse(data.asOf+'T00:00:00Z')>4*86400000&&<p className="pf-warning">Prices are more than four calendar days old. Returns stop on {data.asOf}.</p>}
 <div className="pf-card-stat-grid"><div><span>Return since 15 September</span><strong>{r&&!r.reason?pct(r.returnPct):r?.isNew?'New':'—'}</strong></div><div><span>Portfolio index · starts at 100</span><strong>{r&&!r.reason?(100+r.returnPct).toFixed(2):'—'}</strong></div><div><span>Maximum daily drawdown</span><strong>{r&&!r.reason?pct(r.maxDrawdownPct):'—'}</strong></div></div>
 {r?.reason?<p className="pf-warning">{r.reason}. {r.covered.toFixed(2)}% of portfolio weight has complete history; missing holdings are not replaced with cash.</p>:<PriceChart title="Composite portfolio performance" points={points} currency="USD" startLabel="Since 15 Sep"/>}
 <h3>Every holding · prices, returns and charts</h3><div className="pf-price-table"><table><thead><tr><th>Company</th><th>Starting weight</th><th>15 Sep adjusted close</th><th>Latest adjusted close</th><th>Return</th><th>Contribution</th></tr></thead><tbody>{r?.rows.map((h,i)=><tr key={`${h.name}-${i}`}><td><CompanyLogo market="usa" name={h.name} symbol={h.symbol}/>{h.name}<small> {h.symbol}</small></td><td>{h.weight.toFixed(2)}%</td><td>{usd(h.startPrice)}</td><td>{usd(h.endPrice)}</td><td>{h.reason?(h.isNew?'New':h.reason):pct(h.returnPct)}</td><td>{!r.reason&&!h.reason?`${(h.returnPct*h.weight/r.total).toFixed(2)} pp`:'—'}</td></tr>)}</tbody></table></div>
 {r?.rows.map((h,i)=><details key={`${h.name}-${i}`} className="pf-price-details"><summary>{h.name} · {h.symbol||'Unverified ticker'} · {h.reason?(h.isNew?'New':'History unavailable'):pct(h.returnPct)}</summary>{h.reason?<p>{h.reason}</p>:<PriceChart title={`${h.name} adjusted price`} stock currency="USD" startLabel="Since 15 Sep" base={h.startPrice} points={h.values.map(v=>({date:v.date+'T12:00:00Z',value:v.value*h.startPrice}))}/>}</details>)}
 {r&&!r.reason&&<details><summary>Daily portfolio values</summary><table><thead><tr><th>Date</th><th>Index</th><th>Return from {USA_START}</th></tr></thead><tbody>{r.curve.map(p=><tr key={p.date}><td>{p.date}</td><td>{(p.value*100).toFixed(2)}</td><td>{pct((p.value-1)*100)}</td></tr>)}</tbody></table></details>}
 <p className="pf-footnote">Yahoo adjusted prices account for provider-supplied splits and distributions; they are not historical execution quotes. USD results exclude fees, taxes and currency conversion. Every positive-weight holding needs complete prices on the common US trading calendar. No prices are invented or forward-filled.</p></section>;
}
