"""Phase 2D Consumer Internet and Digital Commerce curriculum."""
from __future__ import annotations
from financials_valuation.schema import KPIKnowledge, SectorValuationModel, ValuationMethodRule
from technology_valuation.model import TECHNOLOGY_PARENT_SECTOR

CONSUMER_VERSION="technology-valuation-v2d.0.0"
def _k(key,name,definition,formula,unit,why,causal,valuation,limitations):
    return KPIKnowledge(key,name,definition,formula,unit,"Quarterly/Annual",("Regulatory filing","NSE/BSE filing","Audited financial statements","Official company disclosure"),why,(causal,),valuation,limitations,("VALIDATED","TRUSTED"))
def _m(method,tier,reason,required,failure):
    return ValuationMethodRule(method,tier,reason,required,(reason,),("Sensitive to revenue recognition, cohorts, inventory, incentives and PIT assumptions.",),(failure,))

CONSUMER_KPIS=(
    _k("net_revenue","Net Revenue","Recognized revenue net of cancellations, returns and discounts.","reported net revenue","currency","Correct accounting base for growth and margins.","orders x AOV - returns -> net revenue","Denominator for revenue multiples.","Marketplace and first-party accounting cannot be mixed."),
    _k("net_revenue_growth","Net Revenue Growth","Change in recognized net revenue.","closing / opening net revenue - 1","decimal","Measures accounting growth after reversals.","customers, frequency and AOV -> revenue growth","Major scenario input.","Acquisitions, inflation and accounting changes require separation."),
    _k("active_customers","Active Customers","Unique customers purchasing in a defined period.","reported active customers","users","Measures the monetizable customer base.","acquisition and retention -> active customers","Supports cohort economics.","Active windows vary."),
    _k("order_frequency","Order Frequency","Net orders per active customer.","net orders / active customers","orders_per_customer","Separates customer growth from engagement.","repeat behavior -> frequency -> revenue","Tests growth quality.","Seasonality matters."),
    _k("average_order_value","Average Order Value","Net sales per net order.","net sales / net orders","currency_per_order","Measures price and basket mix.","pricing and basket -> AOV -> sales","Supports revenue bridge.","Returns and taxes must be consistent."),
    _k("repeat_rate","Repeat Rate","Share of eligible customers purchasing again.","repeat customers / eligible customers","decimal","Tests whether demand persists after acquisition.","experience -> repeat -> LTV","Controls CAC quality.","Cohort window must be disclosed."),
    _k("return_rate","Return Rate","Returned orders divided by gross orders.","returned orders / gross orders","decimal","Reduces true revenue and raises handling cost.","returns -> net sales and inventory loss","Important earnings-quality control.","Category mix and policy differ."),
    _k("gross_margin","Gross Margin","Gross profit divided by net revenue.","gross profit / net revenue","decimal","Shows merchandise and monetization economics.","mix, sourcing and pricing -> gross margin","Controls revenue-multiple comparability.","Ad, subscription and retail mix can distort comparisons."),
    _k("inventory_turns","Inventory Turns","COGS divided by average inventory.","COGS / average inventory","multiple","Measures inventory productivity and working-capital risk.","turns -> cash conversion","Supports balance-sheet risk analysis.","Inventory-light models require separate treatment."),
    _k("contribution_margin","Contribution Margin","Profit after variable fulfillment, payment and incentive costs divided by revenue.","contribution profit / net revenue","decimal","Tests order-level economics.","gross margin - variable costs -> contribution","Controls quality of growth.","Definitions vary by company."),
    _k("customer_acquisition_cost","Customer Acquisition Cost","Sales and marketing per new customer.","sales and marketing / new customers","currency_per_customer","Measures growth efficiency.","marketing -> acquisition -> repeat payback","Supports unit economics.","Brand and retention spend allocations vary."),
    _k("advertising_arpu","Advertising ARPU","Advertising revenue per monetizable user.","advertising revenue / monetizable users","currency_per_user","Captures high-margin attention monetization.","engagement and ad load -> ad ARPU","Explains mix and margin.","User definitions and ad load vary."),
    _k("fcf_margin","FCF Margin","Free cash flow divided by net revenue.","FCF / net revenue","decimal","Tests self-funded scale after working capital and capex.","contribution - fixed costs - working capital - capex -> FCF","Supports mature valuation.","Working-capital timing can be material."),
)
CONSUMER_METHODS=(
    _m("EV_SALES","PRIMARY_GROWTH","EV/revenue fits growth businesses only with gross-margin and contribution context.",("enterprise_value","net_revenue"),"Revenue recognition or unit economics are unreliable"),
    _m("EV_GROSS_PROFIT","PRIMARY_CROSS_CHECK","EV/gross profit controls for business-model and revenue-mix differences.",("enterprise_value","gross_profit"),"Gross profit is unreliable"),
    _m("TECH_PRICE_TO_EARNINGS","MATURE_ONLY","P/E fits normalized profitable digital commerce.",("market_price","normalized_eps"),"Negative or unnormalized earnings"),
    _m("GORDON_DCF","MATURE_SECONDARY","DCF fits supportable normalized cash economics.",("next_fcf","discount_rate","terminal_growth"),"Cash flows or terminal economics are unstable"),
)
CONSUMER_MODEL=SectorValuationModel(sector_id=f"{TECHNOLOGY_PARENT_SECTOR}.CONSUMER_INTERNET_DIGITAL_COMMERCE",sector_name="Consumer Internet and Digital Commerce",subsector="CONSUMER_INTERNET_DIGITAL_COMMERCE",business_model_types=("Consumer Internet","Digital Commerce","E-commerce","Online Retail"),economic_structure="Active customers, order frequency and average order value drive gross sales. Returns and discounts determine net revenue; product, advertising and subscription mix determine gross margin; fulfillment, acquisition, inventory and working capital determine contribution profit and free cash flow.",revenue_drivers=("Active customers","Order frequency","Average order value","Repeat rate","Advertising ARPU","Subscriptions","Product mix","Pricing"),cost_drivers=("COGS","Fulfillment","Returns","Payments","Customer acquisition","Discounts","Technology","Content","Support"),capital_structure="Inventory, warehouses, leases and working capital can make commerce capital-intensive even when the digital interface is asset-light.",regulatory_characteristics=("Consumer protection","Data privacy","E-commerce FDI","Advertising standards","Tax","Product liability","Competition law"),key_kpis=CONSUMER_KPIS,valuation_methods=CONSUMER_METHODS,valuation_drivers=("Net revenue growth","Repeat rate","Gross margin","Contribution margin","CAC","Inventory turns","Advertising mix","FCF margin"),valuation_risks=("Weak cohorts","Returns","Discount-led growth","Inventory obsolescence","Fulfillment inflation","Ad-load saturation","Privacy regulation","Working-capital reversal","SBC dilution"),scenario_variables=("Net revenue growth","Gross margin","Target EV/revenue"),monitoring_variables=("Net revenue growth","Active customers","Order frequency","AOV","Repeat rate","Return rate","Gross margin","Inventory turns","Contribution margin","CAC","Advertising ARPU","FCF margin"),common_analytical_errors=("Treating GMV as net revenue","Mixing first-party and marketplace accounting","Ignoring returns","Ignoring inventory and working capital","Using downloads as active users","Calling paid growth retention","Ignoring ad/subscription mix"),evidence_sources=("Regulatory filings","Audited annual reports","NSE","BSE","Official results","Investor presentations","Licensed transcripts"),effective_date="2026-08-15",confidence=.86,validation_status="VALIDATED",version=CONSUMER_VERSION)
