"""Fail-closed Phase 2E semiconductor evaluator."""
from __future__ import annotations
from datetime import date
from statistics import median
from typing import Any
from causal_research_engine.service import ask_context
from causal_research_engine.technology_templates import semiconductor_templates
from financial_engine import calculate
from technology_valuation.semiconductor_model import SEMI_MODEL
REQUIRED_SEMI_INPUTS=("enterprise_value","revenue","opening_revenue","closing_revenue","ebitda","gross_profit","cogs","opening_inventory","closing_inventory","capacity","utilization","yield_rate","average_selling_price","bookings","rnd_expense","capex","fcf","terminal_ev_ebitda","horizon_years","agi_revenue_growth_expectation","target_ev_ebitda")
def _issue(x,a):
    if not isinstance(x,dict) or not isinstance(x.get("value"),(int,float)) or isinstance(x.get("value"),bool):return "MISSING_OR_INVALID"
    if not x.get("source_id") or not x.get("period") or not x.get("available_at"):return "PROVENANCE_REQUIRED"
    if str(x["available_at"])[:10]>a[:10]:return "POINT_IN_TIME_VIOLATION"
def _scenario(i,a,s):
    missing=[k for k in ("revenue_growth","ebitda_margin","target_ev_ebitda") if k not in s]
    if missing:return {"status":"DATA_UNAVAILABLE","missing":missing,"epistemic_label":"SCENARIO","probability":None}
    r=calculate(calculation_id="SEMI_SCENARIO_EV",inputs={"revenue":i["revenue"],"revenue_growth":{**i["revenue"],"value":float(s["revenue_growth"])},"ebitda_margin":{**i["ebitda"],"value":float(s["ebitda_margin"])},"target_ev_ebitda":{**i["target_ev_ebitda"],"value":float(s["target_ev_ebitda"])}},as_of=a,assumptions=[{"text":"Cycle-normalized scenario, not fact"}]);return {"status":r.get("status"),"epistemic_label":"SCENARIO","assumptions":s,"enterprise_value":r.get("calculated_value"),"probability":None,"calculation":r}
def evaluate_semiconductor(*,company:dict[str,Any],inputs:dict[str,Any],as_of:str,peers:list[dict[str,Any]]|None=None,history:list[dict[str,Any]]|None=None,scenarios:dict[str,dict[str,Any]]|None=None)->dict[str,Any]:
    try:date.fromisoformat(str(as_of)[:10])
    except (TypeError,ValueError):return {"status":"DATA_UNAVAILABLE","execution_eligible":False,"certified":False}
    issues={k:v for k in REQUIRED_SEMI_INPUTS if (v:=_issue(inputs.get(k),as_of))}
    if issues:return {"status":"POINT_IN_TIME_VIOLATION" if "POINT_IN_TIME_VIOLATION" in issues.values() else "DATA_UNAVAILABLE","input_issues":issues,"execution_eligible":False,"certified":False}
    positive=("enterprise_value","revenue","opening_revenue","closing_revenue","ebitda","gross_profit","cogs","opening_inventory","closing_inventory","capacity","average_selling_price","bookings","rnd_expense","capex","terminal_ev_ebitda","horizon_years","target_ev_ebitda"); risks=[f"{k.upper()}_MUST_BE_POSITIVE" for k in positive if float(inputs[k]["value"])<=0]
    for k in ("utilization","yield_rate"):
        if not 0<float(inputs[k]["value"])<=1:risks.append(f"{k.upper()}_OUT_OF_RANGE")
    if float(inputs["gross_profit"]["value"])>float(inputs["revenue"]["value"]):risks.append("GROSS_PROFIT_EXCEEDS_REVENUE")
    if risks:return {"status":"VALIDATION_FAILED","risk_flags":risks,"execution_eligible":False,"certified":False}
    specs=(("ev_ebitda","EV_EBITDA",("enterprise_value","ebitda")),("ev_sales","EV_SALES",("enterprise_value","revenue")),("revenue_growth","SEMI_REVENUE_GROWTH",("opening_revenue","closing_revenue")),("capacity_revenue","SEMI_CAPACITY_REVENUE",("capacity","utilization","yield_rate","average_selling_price")),("book_to_bill","BOOK_TO_BILL",("bookings","revenue")),("gross_margin","DIGITAL_GROSS_MARGIN",("gross_profit","revenue")),("rnd_intensity","SEMI_RND_INTENSITY",("rnd_expense","revenue")),("capex_intensity","SEMI_CAPEX_INTENSITY",("capex","revenue")),("inventory_turns","DIGITAL_INVENTORY_TURNS",("cogs","opening_inventory","closing_inventory")),("fcf_margin","FCF_MARGIN",("fcf","revenue"))); calcs={}
    for n,c,keys in specs:
        w={k:inputs[k] for k in keys}
        if c=="BOOK_TO_BILL":w={"total_contract_value":inputs["bookings"],"revenue":inputs["revenue"]}
        if c=="DIGITAL_GROSS_MARGIN":w={"gross_profit":inputs["gross_profit"],"net_revenue":inputs["revenue"]}
        calcs[n]=calculate(calculation_id=c,inputs=w,as_of=as_of)
    if any(r.get("status")!="SUCCESS" for r in calcs.values()):return {"status":"VALUATION_UNAVAILABLE","calculations":calcs,"execution_eligible":False,"certified":False}
    current=float(calcs["ev_ebitda"]["calculated_value"]); implied=calculate(calculation_id="IMPLIED_GROWTH_FROM_MULTIPLE",inputs={"current_multiple":{**inputs["enterprise_value"],"value":current},"terminal_multiple":inputs["terminal_ev_ebitda"],"horizon_years":inputs["horizon_years"]},as_of=as_of); ig=implied.get("calculated_value") if implied.get("status")=="SUCCESS" else None; expected=float(inputs["agi_revenue_growth_expectation"]["value"]); label="DATA_INSUFFICIENT" if ig is None or expected==0 else "EXPECTATIONS_STRETCHED" if ig/expected>1.1 else "EXPECTATIONS_FAVORABLE" if ig/expected<.9 else "EXPECTATIONS_NEUTRAL"; peer=[float(x["ev_ebitda"]) for x in (peers or []) if isinstance(x.get("ev_ebitda"),(int,float))];hist=[float(x["ev_ebitda"]) for x in (history or []) if isinstance(x.get("ev_ebitda"),(int,float)) and str(x.get("available_at") or "")[:10]<=as_of[:10]];sr={n:_scenario(inputs,as_of,(scenarios or {}).get(n) or {}) for n in ("BEAR","BASE","BULL")};g=float(inputs["agi_revenue_growth_expectation"]["value"]);margin=float(inputs["ebitda"]["value"])/float(inputs["revenue"]["value"]);m=float(inputs["target_ev_ebitda"]["value"]);grid=[{"revenue_growth":x,"ebitda_margin":y,"target_ev_ebitda":m,"enterprise_value":_scenario(inputs,as_of,{"revenue_growth":x,"ebitda_margin":y,"target_ev_ebitda":m}).get("enterprise_value")} for x in (g-.05,g,g+.05) for y in (max(0,margin-.03),margin,min(1,margin+.03))];symbol=str(company.get("symbol") or company.get("company_id") or "SEMI");graph=ask_context(entity=symbol,question=f"What drives cycle-normalized semiconductor value for {symbol}?",industry="Semiconductors",analysis_as_of=as_of)
    return {"status":"OPERATIONAL_NOT_CERTIFIED","lifecycle_status":"OPERATIONAL","company_id":symbol,"as_of":as_of,"model":SEMI_MODEL.to_dict(),"business_economics":{"revenue_model":"end demand x semiconductor content -> units x ASP -> revenue; utilization x yield -> margin; R&D and capex -> FCF","operating_model":{"classification_required":True,"fabless_is_not_foundry":True,"announced_capacity_is_not_qualified_output":True},"competitive_advantage":{"status":"EVIDENCE_REQUIRED","moat_claim_allowed":False},"ai_analysis":{"benefit":"accelerator, memory, networking and advanced-packaging demand","risk":"customer concentration, export controls, overbuild and node obsolescence","net_impact":"EVIDENCE_REQUIRED"}},"kpis":{n:r["calculated_value"] for n,r in calcs.items()}|{"utilization":inputs["utilization"]["value"],"yield_rate":inputs["yield_rate"]["value"]},"valuation":{"primary_method":"EV_EBITDA","current_ev_ebitda":current,"ev_sales":calcs["ev_sales"]["calculated_value"],"peer_median_ev_ebitda":median(peer) if peer else None,"historical_median_ev_ebitda":median(hist) if hist else None,"cycle_normalization_required":True},"market_expectations":{"classification":label,"implied_growth":ig,"agi_revenue_growth_expectation":expected,"calculation":implied},"scenarios":sr,"sensitivity":{"variables":["revenue_growth","ebitda_margin"],"grid":grid},"causal_context":{"templates":[r.to_dict() for r in semiconductor_templates(symbol)],"existing_graph":graph.get("causal_research",{}),"status":"PROPOSED_NOT_TRUSTED"},"monitoring":list(SEMI_MODEL.monitoring_variables),"provenance":{k:{q:inputs[k].get(q) for q in ("source_id","available_at","period","unit","currency")} for k in REQUIRED_SEMI_INPUTS},"evidence_gaps":[n for n,p in (("peer_valuation",bool(peer)),("historical_valuation",bool(hist)),("cycle_normalization",False)) if not p],"confidence":"MEDIUM" if peer and hist else "LOW","investment_attractiveness":"RESEARCH_ONLY","execution_eligible":False,"certified":False,"investment_certified":False}
