"""Twenty-three-gate semiconductor curriculum certification."""
from __future__ import annotations
from typing import Any
from technology_valuation.answer import format_technology_answer
from technology_valuation.semiconductor_model import SEMI_MODEL
from technology_valuation.semiconductor_service import REQUIRED_SEMI_INPUTS,evaluate_semiconductor

def certify_semiconductors(company_packs:dict[str,dict[str,Any]],*,authorized_reviewer:str|None=None,reviewer_authorized:bool=False,review_evidence_id:str|None=None)->dict[str,Any]:
    results={s:evaluate_semiconductor(company={"symbol":s},inputs=p.get("inputs") or {},as_of=str(p.get("as_of") or ""),peers=p.get("peers"),history=p.get("history"),scenarios=p.get("scenarios")) for s,p in company_packs.items()};op=len(results)>=2 and all(r.get("status")=="OPERATIONAL_NOT_CERTIFIED" for r in results.values());sample=next(iter(company_packs.values()),{});i=sample.get("inputs") or {};a=str(sample.get("as_of") or "2026-08-15");missing=dict(i);missing.pop(REQUIRED_SEMI_INPUTS[0],None);future={k:dict(v) for k,v in i.items() if isinstance(v,dict)}
    if REQUIRED_SEMI_INPUTS[0] in future:future[REQUIRED_SEMI_INPUTS[0]]["available_at"]="9999-12-31"
    bad={k:dict(v) for k,v in i.items() if isinstance(v,dict)}
    if "yield_rate" in bad:bad["yield_rate"]["value"]=1.2
    gates={"classification":op,"business_model":bool(SEMI_MODEL.economic_structure),"kpi":len(SEMI_MODEL.key_kpis)>=12,"revenue_driver":len(SEMI_MODEL.revenue_drivers)>=7,"margin_driver":len(SEMI_MODEL.cost_drivers)>=7,"cash_flow":any(k.key=="fcf_margin" for k in SEMI_MODEL.key_kpis),"capital_intensity":bool(SEMI_MODEL.capital_structure),"competitive_advantage":op and all((r.get("business_economics") or {}).get("competitive_advantage",{}).get("moat_claim_allowed") is False for r in results.values()),"method_selection":len(SEMI_MODEL.valuation_methods)>=4,"historical_valuation":op and all((r.get("valuation") or {}).get("historical_median_ev_ebitda") is not None for r in results.values()),"reverse_valuation":op and all((r.get("market_expectations") or {}).get("classification")!="DATA_INSUFFICIENT" for r in results.values()),"peer_comparison":op and all((r.get("valuation") or {}).get("peer_median_ev_ebitda") is not None for r in results.values()),"scenario":op and all(all(v.get("status")=="SUCCESS" for v in (r.get("scenarios") or {}).values()) for r in results.values()),"sensitivity":op and all(len((r.get("sensitivity") or {}).get("grid") or [])==9 for r in results.values()),"macro_transmission":op and all((r.get("causal_context") or {}).get("templates") for r in results.values()),"ai_impact":op and all((r.get("business_economics") or {}).get("ai_analysis",{}).get("net_impact")=="EVIDENCE_REQUIRED" for r in results.values()),"point_in_time":bool(future) and evaluate_semiconductor(company={},inputs=future,as_of=a).get("status")=="POINT_IN_TIME_VIOLATION","accounting_quality":op,"missing_data":bool(missing) and evaluate_semiconductor(company={},inputs=missing,as_of=a).get("status")=="DATA_UNAVAILABLE","contradiction":op and all(any(t.get("counter_effects") for t in (r.get("causal_context") or {}).get("templates") or []) for r in results.values()),"provenance":op and all(len(r.get("provenance") or {})==len(REQUIRED_SEMI_INPUTS) and bool(company_packs[s].get("warehouse_receipt_id")) and bool(company_packs[s].get("independent_verification_id")) for s,r in results.items()),"client_answer":op and all(format_technology_answer(r).get("execution_eligible") is False for r in results.values()),"adversarial":bool(bad) and evaluate_semiconductor(company={},inputs=bad,as_of=a).get("status")=="VALIDATION_FAILED"};passed=sum(gates.values());external=bool(authorized_reviewer and reviewer_authorized and review_evidence_id)
    return {"sector_id":SEMI_MODEL.sector_id,"subsector":"SEMICONDUCTOR_RELATED","model_version":SEMI_MODEL.version,"certification_status":"PASSED" if passed==23 and external else "IN_PROGRESS" if passed else "FAILED","lifecycle_status":"EVIDENCE_VALIDATED" if passed==23 else "OPERATIONAL" if op else "ENGINEERED","passed_gates":passed,"total_gates":23,"gates":gates,"companies":results,"investment_certified":False,"automatic_promotion":False}
