"""Phase 2E Semiconductor-related business curriculum."""
from __future__ import annotations
from financials_valuation.schema import KPIKnowledge,SectorValuationModel,ValuationMethodRule
from technology_valuation.model import TECHNOLOGY_PARENT_SECTOR
SEMI_VERSION="technology-valuation-v2e.0.0"
def _k(k,n,d,f,u,w,c,v,l):return KPIKnowledge(k,n,d,f,u,"Quarterly/Annual",("Regulatory filing","NSE/BSE filing","Audited financial statements","Official company disclosure"),w,(c,),v,l,("VALIDATED","TRUSTED"))
def _m(m,t,r,req,fail):return ValuationMethodRule(m,t,r,req,(r,),("Use cycle-normalized economics and PIT evidence.",),(fail,))
SEMI_KPIS=(
 _k("revenue_growth","Revenue Growth","Change in reported semiconductor-related revenue.","closing/opening revenue - 1","decimal","Measures cycle and content growth.","units x ASP -> revenue","Scenario driver.","Acquisitions, FX and pass-through require separation."),
 _k("unit_shipments","Unit Shipments","Saleable chips, wafers, packages or equipment shipped.","reported units","units","Separates volume from pricing.","end demand and inventory -> units","Revenue bridge.","Product units may not be comparable."),
 _k("average_selling_price","Average Selling Price","Revenue per comparable unit.","product revenue / units","currency_per_unit","Captures mix, content and pricing.","mix and scarcity -> ASP","Revenue and margin driver.","Heterogeneous products distort averages."),
 _k("capacity","Qualified Capacity","Potential production or packaging output.","reported capacity","units","Defines supply ceiling.","capex and qualification -> capacity","Supports utilization analysis.","Nameplate is not saleable output."),
 _k("utilization","Utilization","Used qualified capacity divided by available capacity.","used / available capacity","decimal","Fixed-cost absorption drives margins.","demand -> utilization -> margin","Major cycle variable.","Fabless businesses need supplier utilization instead."),
 _k("yield_rate","Yield","Saleable output divided by processed output.","good units / processed units","decimal","Measures manufacturing maturity.","yield -> unit cost -> margin","Critical ramp variable.","Company disclosure may be limited."),
 _k("book_to_bill","Book-to-Bill","Orders booked divided by recognized revenue.","bookings / revenue","multiple","Indicates cycle direction.","orders -> backlog -> revenue","Forward cross-check.","Cancellations and long lead times matter."),
 _k("gross_margin","Gross Margin","Gross profit divided by revenue.","gross profit / revenue","decimal","Reflects utilization, yield, mix and pricing.","ASP and unit cost -> gross margin","Cycle-normalization anchor.","Subsidies and startup costs require adjustment."),
 _k("rnd_intensity","R&D Intensity","Research and development expense divided by revenue.","R&D / revenue","decimal","Measures investment in nodes, IP and products.","R&D -> design wins -> future revenue","Durability input.","Expense does not guarantee viable IP."),
 _k("capex_intensity","Capex Intensity","Capital expenditure divided by revenue.","capex / revenue","decimal","Shows reinvestment burden.","capex -> qualified capacity -> output","Controls FCF and returns.","Fabless and foundry models differ radically."),
 _k("inventory_turns","Inventory Turns","COGS divided by average inventory.","COGS / average inventory","multiple","Detects cycle and obsolescence risk.","inventory correction -> orders","Earnings-quality control.","Strategic buffers may be intentional."),
 _k("fcf_margin","FCF Margin","Free cash flow divided by revenue.","FCF / revenue","decimal","Tests cash after R&D and capex.","gross profit - R&D - capex - working capital -> FCF","Valuation support.","Cycle peaks can overstate normalized cash."),
)
SEMI_METHODS=(_m("EV_EBITDA","PRIMARY_MATURE","EV/EBITDA fits profitable operations when EBITDA is cycle-normalized.",( "enterprise_value","ebitda"),"Peak-cycle EBITDA is used"),_m("TECH_PRICE_TO_EARNINGS","SECONDARY_MATURE","P/E is useful with normalized earnings and dilution.",( "market_price","normalized_eps"),"Earnings are negative or unnormalized"),_m("EV_SALES","EARLY_STAGE_ONLY","EV/revenue is a cross-check for pre-profit businesses with evidenced margin path.",( "enterprise_value","revenue"),"No credible gross-margin or utilization path"),_m("GORDON_DCF","PRIMARY_INTRINSIC","DCF is required for capital-intensive long-duration projects.",( "next_fcf","discount_rate","terminal_growth"),"Cash flows and capacity ramp are unsupported"))
SEMI_MODEL=SectorValuationModel(sector_id=f"{TECHNOLOGY_PARENT_SECTOR}.SEMICONDUCTOR_RELATED",sector_name="Semiconductor-related Businesses",subsector="SEMICONDUCTOR_RELATED",business_model_types=("Fabless Semiconductor","Semiconductor Design","Foundry","ATMP/OSAT","Semiconductor Equipment"),economic_structure="End-market units and semiconductor content drive demand. Units and ASP drive revenue; utilization, yield and mix drive gross margin; R&D, qualification, inventory and capex determine design durability, cash flow and returns.",revenue_drivers=("End-market demand","Semiconductor content","Unit shipments","ASP","Design wins","Utilization","Yield","Backlog"),cost_drivers=("Wafer and substrate cost","Packaging","Depreciation","R&D","Engineering","Energy","Materials","Qualification","Capex"),capital_structure="Fabless design is R&D intensive; foundry and ATMP are capital intensive. Subsidies, project debt, customer advances and long ramps must be separated from recurring economics.",regulatory_characteristics=("Export controls","Technology licensing","Environmental permits","Industrial subsidies","National security","Trade restrictions"),key_kpis=SEMI_KPIS,valuation_methods=SEMI_METHODS,valuation_drivers=("Cycle-normalized revenue","Utilization","Yield","Gross margin","R&D productivity","Capex intensity","Design wins","FCF"),valuation_risks=("Inventory correction","Customer concentration","Node obsolescence","Yield ramp","Capex overbuild","Export controls","Subsidy dependence","Project delay","ASP pressure"),scenario_variables=("Revenue growth","EBITDA margin","Target EV/EBITDA"),monitoring_variables=("End demand","Unit shipments","ASP","Utilization","Yield","Book-to-bill","Inventory turns","Gross margin","R&D intensity","Capex intensity","FCF margin"),common_analytical_errors=("Applying foundry economics to fabless design","Annualizing peak-cycle margins","Treating announced capacity as qualified output","Ignoring inventory correction","Treating subsidies as recurring profit","Ignoring yield and qualification"),evidence_sources=("Regulatory filings","Audited annual reports","NSE","BSE","Official results","Government approvals","Customer disclosures","Licensed transcripts"),effective_date="2026-08-15",confidence=.85,validation_status="VALIDATED",version=SEMI_VERSION)
