"""Fail-closed Phase 2F Telecom evaluator."""
from __future__ import annotations
from datetime import date
from statistics import median
from typing import Any
from causal_research_engine.service import ask_context
from causal_research_engine.technology_templates import telecom_templates
from financial_engine import calculate
from technology_valuation.telecom_model import TELECOM_MODEL
REQUIRED_TELECOM_INPUTS=("enterprise_value","revenue","ebitda","opening_subscribers","closing_subscribers","monthly_arpu","churn","market_share","data_usage","capex","net_debt","spectrum_liabilities","interest_expense","enterprise_revenue","fcf","terminal_ev_ebitda","horizon_years","agi_ebitda_growth_expectation","target_ev_ebitda","tariff_change","realization","incremental_margin")
def _issue(x,a):
    if not isinstance(x,dict) or not isinstance(x.get("value"),(int,float)) or isinstance(x.get("value"),bool):return "MISSING_OR_INVALID"
    if not x.get("source_id") or not x.get("period") or not x.get("available_at"):return "PROVENANCE_REQUIRED"
    if str(x["available_at"])[:10]>a[:10]:return "POINT_IN_TIME_VIOLATION"
def _scenario(i,a,s):
    required=("tariff_change","realization","incremental_margin","target_ev_ebitda");missing=[k for k in required if k not in s]
    if missing:return {"status":"DATA_UNAVAILABLE","missing":missing,"epistemic_label":"SCENARIO","probability":None}
    v={"ebitda":i["ebitda"],"arpu":i["monthly_arpu"],"subscribers":i["closing_subscribers"],"net_debt":i["net_debt"],"spectrum_liabilities":i["spectrum_liabilities"]}
    for k in required:v[k]={**i[k],"value":float(s[k])}
    r=calculate(calculation_id="TELECOM_SCENARIO_EQUITY",inputs=v,as_of=a,assumptions=[{"text":"Tariff scenario, not fact"}]);return {"status":r.get("status"),"epistemic_label":"SCENARIO","assumptions":s,"equity_value":r.get("calculated_value"),"probability":None,"calculation":r}
def evaluate_telecom(*,company:dict[str,Any],inputs:dict[str,Any],as_of:str,peers:list[dict[str,Any]]|None=None,history:list[dict[str,Any]]|None=None,scenarios:dict[str,dict[str,Any]]|None=None)->dict[str,Any]:
    try:date.fromisoformat(str(as_of)[:10])
    except (TypeError,ValueError):return {"status":"DATA_UNAVAILABLE","execution_eligible":False,"certified":False}
    issues={k:v for k in REQUIRED_TELECOM_INPUTS if (v:=_issue(inputs.get(k),as_of))}
    if issues:return {"status":"POINT_IN_TIME_VIOLATION" if "POINT_IN_TIME_VIOLATION" in issues.values() else "DATA_UNAVAILABLE","input_issues":issues,"execution_eligible":False,"certified":False}
    positive=("enterprise_value","revenue","ebitda","opening_subscribers","closing_subscribers","monthly_arpu","data_usage","capex","interest_expense","terminal_ev_ebitda","horizon_years","target_ev_ebitda");risks=[f"{k.upper()}_MUST_BE_POSITIVE" for k in positive if float(inputs[k]["value"])<=0]
    for k in ("churn","market_share","realization","incremental_margin"):
        if not 0<=float(inputs[k]["value"])<=1:risks.append(f"{k.upper()}_OUT_OF_RANGE")
    if float(inputs["enterprise_revenue"]["value"])>float(inputs["revenue"]["value"]):risks.append("ENTERPRISE_REVENUE_EXCEEDS_TOTAL")
    if risks:return {"status":"VALIDATION_FAILED","risk_flags":risks,"execution_eligible":False,"certified":False}
    specs=(("ev_ebitda","EV_EBITDA",("enterprise_value","ebitda")),("subscriber_growth","TELECOM_SUBSCRIBER_GROWTH",("opening_subscribers","closing_subscribers")),("service_revenue_bridge","TELECOM_ANNUAL_SERVICE_REVENUE",("opening_subscribers","closing_subscribers","monthly_arpu")),("ev_per_subscriber","TELECOM_EV_PER_SUBSCRIBER",("enterprise_value","subscribers")),("ebitda_margin","TELECOM_EBITDA_MARGIN",("ebitda","revenue")),("capex_intensity","TELECOM_CAPEX_INTENSITY",("capex","revenue")),("net_debt_ebitda","TELECOM_NET_DEBT_EBITDA",("net_debt","spectrum_liabilities","ebitda")),("interest_coverage","TELECOM_INTEREST_COVERAGE",("ebitda","interest_expense")),("enterprise_mix","TELECOM_ENTERPRISE_MIX",("enterprise_revenue","revenue")),("fcf_margin","FCF_MARGIN",("fcf","revenue")));calcs={}
    for n,c,keys in specs:
        w={k:inputs[k] for k in keys if k in inputs}
        if c=="TELECOM_EV_PER_SUBSCRIBER":w={"enterprise_value":inputs["enterprise_value"],"subscribers":inputs["closing_subscribers"]}
        calcs[n]=calculate(calculation_id=c,inputs=w,as_of=as_of)
    if any(r.get("status")!="SUCCESS" for r in calcs.values()):return {"status":"VALUATION_UNAVAILABLE","calculations":calcs,"execution_eligible":False,"certified":False}
    current=float(calcs["ev_ebitda"]["calculated_value"]);implied=calculate(calculation_id="IMPLIED_GROWTH_FROM_MULTIPLE",inputs={"current_multiple":{**inputs["enterprise_value"],"value":current},"terminal_multiple":inputs["terminal_ev_ebitda"],"horizon_years":inputs["horizon_years"]},as_of=as_of);ig=implied.get("calculated_value") if implied.get("status")=="SUCCESS" else None;expected=float(inputs["agi_ebitda_growth_expectation"]["value"]);label="DATA_INSUFFICIENT" if ig is None or expected==0 else "EXPECTATIONS_STRETCHED" if ig/expected>1.1 else "EXPECTATIONS_FAVORABLE" if ig/expected<.9 else "EXPECTATIONS_NEUTRAL";peer=[float(x["ev_ebitda"]) for x in (peers or []) if isinstance(x.get("ev_ebitda"),(int,float))];hist=[float(x["ev_ebitda"]) for x in (history or []) if isinstance(x.get("ev_ebitda"),(int,float)) and str(x.get("available_at") or "")[:10]<=as_of[:10]];sr={n:_scenario(inputs,as_of,(scenarios or {}).get(n) or {}) for n in ("BEAR","BASE","BULL")};t=float(inputs["tariff_change"]["value"]);r=float(inputs["realization"]["value"]);m=float(inputs["incremental_margin"]["value"]);target=float(inputs["target_ev_ebitda"]["value"]);grid=[{"tariff_change":x,"realization":y,"incremental_margin":m,"target_ev_ebitda":target,"equity_value":_scenario(inputs,as_of,{"tariff_change":x,"realization":y,"incremental_margin":m,"target_ev_ebitda":target}).get("equity_value")} for x in (max(-.99,t-.05),t,t+.05) for y in (max(0,r-.15),r,min(1,r+.15))];symbol=str(company.get("symbol") or company.get("company_id") or "TELECOM");graph=ask_context(entity=symbol,question=f"How do tariffs transmit into telecom equity value for {symbol}?",industry="Telecom",analysis_as_of=as_of)
    return {"status":"OPERATIONAL_NOT_CERTIFIED","lifecycle_status":"OPERATIONAL","company_id":symbol,"as_of":as_of,"model":TELECOM_MODEL.to_dict(),"business_economics":{"revenue_model":"subscribers x ARPU plus enterprise contracts -> revenue -> EBITDA -> capex/spectrum/interest -> FCF -> deleveraging -> equity value","subscriber_quality":{"status":"EVIDENCE_REQUIRED","registered_is_not_active":True},"competitive_advantage":{"status":"EVIDENCE_REQUIRED","moat_claim_allowed":False},"ai_analysis":{"benefit":"network optimization, service automation and enterprise demand","risk":"incremental compute/network capex and weak direct monetization","net_impact":"EVIDENCE_REQUIRED"}},"kpis":{n:r["calculated_value"] for n,r in calcs.items()}|{"arpu":inputs["monthly_arpu"]["value"],"churn":inputs["churn"]["value"],"market_share":inputs["market_share"]["value"],"data_usage":inputs["data_usage"]["value"]},"valuation":{"primary_method":"EV_EBITDA","current_ev_ebitda":current,"ev_per_subscriber":calcs["ev_per_subscriber"]["calculated_value"],"peer_median_ev_ebitda":median(peer) if peer else None,"historical_median_ev_ebitda":median(hist) if hist else None,"debt_and_spectrum_deducted_in_scenarios":True},"market_expectations":{"classification":label,"implied_growth":ig,"agi_ebitda_growth_expectation":expected,"calculation":implied},"scenarios":sr,"sensitivity":{"variables":["tariff_change","realization"],"grid":grid},"causal_context":{"templates":[x.to_dict() for x in telecom_templates(symbol)],"existing_graph":graph.get("causal_research",{}),"status":"PROPOSED_NOT_TRUSTED"},"monitoring":list(TELECOM_MODEL.monitoring_variables),"provenance":{k:{q:inputs[k].get(q) for q in ("source_id","available_at","period","unit","currency")} for k in REQUIRED_TELECOM_INPUTS},"evidence_gaps":[n for n,p in (("peer_valuation",bool(peer)),("historical_valuation",bool(hist)),("tariff_realization",False)) if not p],"confidence":"MEDIUM" if peer and hist else "LOW","investment_attractiveness":"RESEARCH_ONLY","execution_eligible":False,"certified":False,"investment_certified":False}
