"""Phase 2F Telecom institutional curriculum."""
from __future__ import annotations
from financials_valuation.schema import KPIKnowledge,SectorValuationModel,ValuationMethodRule
from technology_valuation.model import TECHNOLOGY_PARENT_SECTOR
TELECOM_VERSION="technology-valuation-v2f.0.0"
def _k(k,n,d,f,u,w,c,v,l):return KPIKnowledge(k,n,d,f,u,"Quarterly/Annual",("TRAI","Regulatory filing","NSE/BSE filing","Audited financial statements","Official company disclosure"),w,(c,),v,l,("VALIDATED","TRUSTED"))
def _m(m,t,r,req,fail):return ValuationMethodRule(m,t,r,req,(r,),("Separate spectrum liabilities, leases, subsidiaries and PIT assumptions.",),(fail,))
TELECOM_KPIS=(
 _k("subscribers","Subscribers","Active revenue-generating subscriber base.","reported active subscribers","subscribers","Defines wireless and broadband scale.","additions - churn -> subscribers","Supports revenue and EV/subscriber.","Registered SIMs are not active users."),
 _k("subscriber_growth","Subscriber Growth","Change in active subscribers.","closing/opening subscribers - 1","decimal","Separates volume from ARPU.","net additions -> subscribers","Revenue bridge.","M2M and inactive definitions vary."),
 _k("arpu","Average Revenue per User","Monthly service revenue per average subscriber.","service revenue / average subscribers / months","currency_per_month","Primary monetization measure.","tariffs and mix -> ARPU","Key scenario input.","Reported definitions differ by service."),
 _k("churn","Churn","Subscriber losses divided by opening base.","disconnects / opening subscribers","decimal","Measures retention and tariff elasticity.","price and quality -> churn","Controls realization and LTV.","Voluntary/involuntary definitions vary."),
 _k("data_usage","Data Usage","Average data consumed per subscriber.","network data / subscribers","data_per_subscriber","Signals engagement and capacity need.","usage -> utilization -> capex","Network investment input.","Unlimited plans weaken direct monetization."),
 _k("market_share","Market Share","Company subscribers or revenue divided by market total.","company / market","decimal","Shows competitive position.","quality and distribution -> share","Pricing-power evidence.","Subscriber and revenue share differ."),
 _k("ebitda_margin","EBITDA Margin","EBITDA divided by revenue.","EBITDA / revenue","decimal","Measures service operating leverage.","ARPU and costs -> EBITDA margin","Primary multiple context.","Leases and exceptional items require consistency."),
 _k("capex_intensity","Capex Intensity","Network capex divided by revenue.","capex / revenue","decimal","Shows reinvestment burden.","coverage and capacity -> capex","FCF bridge.","Spectrum payments are separate."),
 _k("net_debt_ebitda","Net Debt to EBITDA","Net debt plus spectrum liabilities divided by EBITDA.","(net debt + spectrum liabilities) / EBITDA","multiple","Measures solvency and equity sensitivity.","capex and spectrum -> leverage","Equity bridge.","Lease treatment must be consistent."),
 _k("interest_coverage","Interest Coverage","EBITDA divided by interest expense.","EBITDA / interest","multiple","Tests debt-service capacity.","EBITDA -> interest coverage","Risk gate.","EBITDA is before capex."),
 _k("enterprise_mix","Enterprise Revenue Mix","Enterprise connectivity revenue divided by revenue.","enterprise revenue / total revenue","decimal","Separates contracted connectivity from consumer wireless.","contracts -> visibility","Peer/method context.","Reported segments can include pass-through."),
 _k("fcf_margin","FCF Margin","FCF divided by revenue.","FCF / revenue","decimal","Tests cash after capex and working capital.","EBITDA - capex - interest - tax -> FCF","Deleveraging capacity.","Spectrum cash payments require disclosure."),
)
TELECOM_METHODS=(_m("EV_EBITDA","PRIMARY","EV/EBITDA fits network operations when leases and subsidiaries are consistently treated.",( "enterprise_value","ebitda"),"EBITDA is not normalized"),_m("TELECOM_EV_PER_SUBSCRIBER","SECONDARY_WIRELESS","EV/subscriber is a scale cross-check with ARPU, churn and network quality.",( "enterprise_value","subscribers"),"Used without subscriber quality"),_m("GORDON_DCF","PRIMARY_INTRINSIC","DCF captures capex, spectrum, debt and tariff timing.",( "next_fcf","discount_rate","terminal_growth"),"Tariff and capex assumptions are unsupported"),_m("FCF_YIELD","MATURE_SECONDARY","FCF yield tests equity cash support after investment.",( "fcf_per_share","market_price"),"FCF excludes recurring spectrum/capex burden"))
TELECOM_MODEL=SectorValuationModel(sector_id=f"{TECHNOLOGY_PARENT_SECTOR}.TELECOM",sector_name="Telecom",subsector="TELECOM",business_model_types=("Wireless Telecom","Broadband/Fiber","Enterprise Telecom"),economic_structure="Subscribers and enterprise contracts create usage; tariffs and mix determine ARPU; ARPU and subscribers drive service revenue; network costs determine EBITDA; spectrum, capex, interest and tax determine FCF, deleveraging and equity value.",revenue_drivers=("Subscribers","ARPU","Tariffs","Churn","4G/5G mix","Postpaid mix","Data usage","Enterprise contracts","Roaming"),cost_drivers=("Spectrum","Network opex","Tower rentals","Energy","Interconnect","Customer acquisition","Capex","Interest"),capital_structure="Spectrum liabilities, leases, network debt and minority interests materially affect equity value; enterprise and tower subsidiaries require transparent consolidation.",regulatory_characteristics=("Spectrum auctions","TRAI tariffs","License fees","AGR obligations","Interconnect","Net neutrality","Security rules"),key_kpis=TELECOM_KPIS,valuation_methods=TELECOM_METHODS,valuation_drivers=("ARPU","Subscriber quality","Churn","EBITDA margin","Capex intensity","Spectrum burden","Deleveraging","Enterprise mix"),valuation_risks=("Price competition","Churn","Spectrum cost","Capex intensity","Leverage","Regulation","Technology migration","Network quality","Customer concentration"),scenario_variables=("Tariff change","Realization","Incremental margin","Target EV/EBITDA"),monitoring_variables=("Subscribers","ARPU","Churn","Market share","Data usage","5G mix","EBITDA margin","Capex intensity","Net debt/EBITDA","Interest coverage","FCF"),common_analytical_errors=("Applying tariff increase at 100% realization","Ignoring churn/down-trading","Ignoring spectrum liabilities","Using EBITDA without capex","Comparing lease-adjusted and unadjusted peers","Treating all telecom models alike"),evidence_sources=("TRAI","DoT","Regulatory filings","Audited annual reports","NSE","BSE","Official results","Investor presentations"),effective_date="2026-08-15",confidence=.89,validation_status="VALIDATED",version=TELECOM_VERSION)
