"""Twenty-three-gate telecom-tower curriculum certification."""
from __future__ import annotations
from typing import Any
from technology_valuation.answer import format_technology_answer
from technology_valuation.tower_model import TOWER_MODEL
from technology_valuation.tower_service import REQUIRED_TOWER_INPUTS,evaluate_tower

def certify_towers(company_packs:dict[str,dict[str,Any]],*,authorized_reviewer:str|None=None,reviewer_authorized:bool=False,review_evidence_id:str|None=None)->dict[str,Any]:
    results={s:evaluate_tower(company={"symbol":s},inputs=p.get("inputs") or {},as_of=str(p.get("as_of") or ""),peers=p.get("peers"),history=p.get("history"),scenarios=p.get("scenarios")) for s,p in company_packs.items()}
    operational=len(results)>=2 and all(r.get("status")=="OPERATIONAL_NOT_CERTIFIED" for r in results.values())
    sample=next(iter(company_packs.values()),{});inputs=sample.get("inputs") or {};as_of=str(sample.get("as_of") or "2026-08-15")
    missing=dict(inputs);missing.pop(REQUIRED_TOWER_INPUTS[0],None)
    future={k:dict(v) for k,v in inputs.items() if isinstance(v,dict)}
    if REQUIRED_TOWER_INPUTS[0] in future:future[REQUIRED_TOWER_INPUTS[0]]["available_at"]="9999-12-31"
    bad={k:dict(v) for k,v in inputs.items() if isinstance(v,dict)}
    if "tenants" in bad and "sites" in bad:bad["tenants"]["value"]=bad["sites"]["value"]-1
    gates={"classification":operational,"business_model":bool(TOWER_MODEL.economic_structure),"kpi":len(TOWER_MODEL.key_kpis)>=12,"revenue_driver":len(TOWER_MODEL.revenue_drivers)>=7,"margin_driver":len(TOWER_MODEL.cost_drivers)>=7,"cash_flow":any(k.key=="fcf_margin" for k in TOWER_MODEL.key_kpis),"capital_intensity":bool(TOWER_MODEL.capital_structure),"competitive_advantage":operational and all((r.get("business_economics") or {}).get("competitive_advantage",{}).get("moat_claim_allowed") is False for r in results.values()),"method_selection":len(TOWER_MODEL.valuation_methods)>=4,"historical_valuation":operational and all((r.get("valuation") or {}).get("historical_median_ev_ebitda") is not None for r in results.values()),"reverse_valuation":operational and all((r.get("market_expectations") or {}).get("implied_growth") is not None for r in results.values()),"peer_comparison":operational and all((r.get("valuation") or {}).get("peer_median_ev_ebitda") is not None for r in results.values()),"scenario":operational and all(all(v.get("status")=="SUCCESS" for v in (r.get("scenarios") or {}).values()) for r in results.values()),"sensitivity":operational and all(len((r.get("sensitivity") or {}).get("grid") or [])==9 for r in results.values()),"macro_transmission":operational and all((r.get("causal_context") or {}).get("templates") for r in results.values()),"ai_impact":operational and all((r.get("business_economics") or {}).get("ai_analysis",{}).get("net_impact")=="EVIDENCE_REQUIRED" for r in results.values()),"point_in_time":bool(future) and evaluate_tower(company={},inputs=future,as_of=as_of).get("status")=="POINT_IN_TIME_VIOLATION","accounting_quality":operational,"missing_data":bool(missing) and evaluate_tower(company={},inputs=missing,as_of=as_of).get("status")=="DATA_UNAVAILABLE","contradiction":operational and all(any(t.get("counter_effects") for t in (r.get("causal_context") or {}).get("templates") or []) for r in results.values()),"provenance":operational and all(len(r.get("provenance") or {})==len(REQUIRED_TOWER_INPUTS) and bool(company_packs[s].get("warehouse_receipt_id")) and bool(company_packs[s].get("independent_verification_id")) for s,r in results.items()),"client_answer":operational and all(format_technology_answer(r).get("execution_eligible") is False for r in results.values()),"adversarial":bool(bad) and evaluate_tower(company={},inputs=bad,as_of=as_of).get("status")=="VALIDATION_FAILED"}
    passed=sum(gates.values());external=bool(authorized_reviewer and reviewer_authorized and review_evidence_id)
    return {"sector_id":TOWER_MODEL.sector_id,"subsector":TOWER_MODEL.subsector,"model_version":TOWER_MODEL.version,"certification_status":"PASSED" if passed==23 and external else "IN_PROGRESS" if passed else "FAILED","lifecycle_status":"EVIDENCE_VALIDATED" if passed==23 else "OPERATIONAL" if operational else "ENGINEERED","passed_gates":passed,"total_gates":23,"gates":gates,"companies":results,"investment_certified":False,"automatic_promotion":False}
