"""Fail-closed Phase 2G tower evaluator."""
from __future__ import annotations
from datetime import date
from statistics import median
from typing import Any
from causal_research_engine.service import ask_context
from causal_research_engine.technology_templates import telecom_tower_templates
from financial_engine import calculate
from technology_valuation.tower_model import TOWER_MODEL
REQUIRED_TOWER_INPUTS=("enterprise_value","revenue","rental_revenue","ebitda","sites","tenants","tenant_additions","annual_rent_per_tenant","energy_costs","energy_reimbursements","contract_duration","customer_concentration","capex","net_debt","fcf","terminal_ev_ebitda","horizon_years","target_ev_ebitda","scenario_tenancy_ratio","scenario_ebitda_margin")
def _issue(x,a):
    if not isinstance(x,dict) or not isinstance(x.get("value"),(int,float)) or isinstance(x.get("value"),bool):return "MISSING_OR_INVALID"
    if not x.get("source_id") or not x.get("period") or not x.get("available_at"):return "PROVENANCE_REQUIRED"
    if str(x["available_at"])[:10]>a[:10]:return "POINT_IN_TIME_VIOLATION"
def _scenario(i,a,s):
    req=("sites","tenancy_ratio","annual_rent_per_tenant","ebitda_margin","target_ev_ebitda");missing=[k for k in req if k not in s]
    if missing:return {"status":"DATA_UNAVAILABLE","missing":missing,"epistemic_label":"SCENARIO","probability":None}
    v={k:{**i["sites"],"value":float(s[k])} for k in req};v["net_debt"]=i["net_debt"];r=calculate(calculation_id="TOWER_SCENARIO_EQUITY",inputs=v,as_of=a,assumptions=[{"text":"Tower scenario, not fact"}]);return {"status":r.get("status"),"epistemic_label":"SCENARIO","assumptions":s,"equity_value":r.get("calculated_value"),"probability":None,"calculation":r}
def evaluate_tower(*,company:dict[str,Any],inputs:dict[str,Any],as_of:str,peers:list[dict[str,Any]]|None=None,history:list[dict[str,Any]]|None=None,scenarios:dict[str,dict[str,Any]]|None=None)->dict[str,Any]:
    try:date.fromisoformat(str(as_of)[:10])
    except (TypeError,ValueError):return {"status":"DATA_UNAVAILABLE","execution_eligible":False,"certified":False}
    issues={k:v for k in REQUIRED_TOWER_INPUTS if (v:=_issue(inputs.get(k),as_of))}
    if issues:return {"status":"POINT_IN_TIME_VIOLATION" if "POINT_IN_TIME_VIOLATION" in issues.values() else "DATA_UNAVAILABLE","input_issues":issues,"execution_eligible":False,"certified":False}
    positive=("enterprise_value","revenue","rental_revenue","ebitda","sites","tenants","annual_rent_per_tenant","energy_costs","contract_duration","capex","terminal_ev_ebitda","horizon_years","target_ev_ebitda","scenario_tenancy_ratio");risks=[f"{k.upper()}_MUST_BE_POSITIVE" for k in positive if float(inputs[k]["value"])<=0]
    for k in ("customer_concentration","scenario_ebitda_margin"):
        if not 0<=float(inputs[k]["value"])<=1:risks.append(f"{k.upper()}_OUT_OF_RANGE")
    if float(inputs["tenants"]["value"])<float(inputs["sites"]["value"]):risks.append("TENANTS_BELOW_ACTIVE_SITES")
    if risks:return {"status":"VALIDATION_FAILED","risk_flags":risks,"execution_eligible":False,"certified":False}
    specs=(("ev_ebitda","EV_EBITDA",("enterprise_value","ebitda")),("tenancy_ratio","TOWER_TENANCY_RATIO",("tenants","sites")),("revenue_per_tenant","TOWER_REVENUE_PER_TENANT",("rental_revenue","tenants")),("ev_per_site","TOWER_EV_PER_SITE",("enterprise_value","sites")),("energy_coverage","TOWER_ENERGY_PASS_THROUGH",("energy_reimbursements","energy_costs")),("ebitda_margin","TELECOM_EBITDA_MARGIN",("ebitda","revenue")),("capex_intensity","TELECOM_CAPEX_INTENSITY",("capex","revenue")),("net_debt_ebitda","TOWER_NET_DEBT_EBITDA",("net_debt","ebitda")),("fcf_margin","FCF_MARGIN",("fcf","revenue")));calcs={n:calculate(calculation_id=c,inputs={k:inputs[k] for k in keys},as_of=as_of) for n,c,keys in specs}
    if any(r.get("status")!="SUCCESS" for r in calcs.values()):return {"status":"VALUATION_UNAVAILABLE","calculations":calcs,"execution_eligible":False,"certified":False}
    current=float(calcs["ev_ebitda"]["calculated_value"]);implied=calculate(calculation_id="IMPLIED_GROWTH_FROM_MULTIPLE",inputs={"current_multiple":{**inputs["enterprise_value"],"value":current},"terminal_multiple":inputs["terminal_ev_ebitda"],"horizon_years":inputs["horizon_years"]},as_of=as_of);peer=[float(x["ev_ebitda"]) for x in (peers or []) if isinstance(x.get("ev_ebitda"),(int,float))];hist=[float(x["ev_ebitda"]) for x in (history or []) if isinstance(x.get("ev_ebitda"),(int,float)) and str(x.get("available_at") or "")[:10]<=as_of[:10]];sr={n:_scenario(inputs,as_of,(scenarios or {}).get(n) or {}) for n in ("BEAR","BASE","BULL")};base_sites=float(inputs["sites"]["value"]);base_t=float(inputs["scenario_tenancy_ratio"]["value"]);rent=float(inputs["annual_rent_per_tenant"]["value"]);margin=float(inputs["scenario_ebitda_margin"]["value"]);target=float(inputs["target_ev_ebitda"]["value"]);grid=[{"sites":base_sites,"tenancy_ratio":t,"annual_rent_per_tenant":rent,"ebitda_margin":m,"target_ev_ebitda":target,"equity_value":_scenario(inputs,as_of,{"sites":base_sites,"tenancy_ratio":t,"annual_rent_per_tenant":rent,"ebitda_margin":m,"target_ev_ebitda":target}).get("equity_value")} for t in (max(1,base_t-.1),base_t,base_t+.1) for m in (max(0,margin-.05),margin,min(1,margin+.05))];symbol=str(company.get("symbol") or "TOWER");graph=ask_context(entity=symbol,question=f"What drives contracted tower value for {symbol}?",industry="Telecom Infrastructure and Towers",analysis_as_of=as_of)
    return {"status":"OPERATIONAL_NOT_CERTIFIED","lifecycle_status":"OPERATIONAL","company_id":symbol,"as_of":as_of,"model":TOWER_MODEL.to_dict(),"business_economics":{"revenue_model":"active sites x tenancy x rent plus recoveries -> EBITDA -> capex/interest -> FCF","site_quality":{"status":"EVIDENCE_REQUIRED","active_sites_only":True,"energy_is_not_rental_revenue":True},"competitive_advantage":{"status":"EVIDENCE_REQUIRED","moat_claim_allowed":False},"ai_analysis":{"benefit":"predictive maintenance and energy optimization","risk":"limited direct monetization","net_impact":"EVIDENCE_REQUIRED"}},"kpis":{n:r["calculated_value"] for n,r in calcs.items()}|{"tenant_additions":inputs["tenant_additions"]["value"],"contract_duration":inputs["contract_duration"]["value"],"customer_concentration":inputs["customer_concentration"]["value"]},"valuation":{"primary_method":"EV_EBITDA","current_ev_ebitda":current,"ev_per_site":calcs["ev_per_site"]["calculated_value"],"peer_median_ev_ebitda":median(peer) if peer else None,"historical_median_ev_ebitda":median(hist) if hist else None},"market_expectations":{"classification":"SCENARIO_DEPENDENT","implied_growth":implied.get("calculated_value"),"calculation":implied},"scenarios":sr,"sensitivity":{"variables":["tenancy_ratio","ebitda_margin"],"grid":grid},"causal_context":{"templates":[x.to_dict() for x in telecom_tower_templates(symbol)],"existing_graph":graph.get("causal_research",{}),"status":"PROPOSED_NOT_TRUSTED"},"monitoring":list(TOWER_MODEL.monitoring_variables),"provenance":{k:{q:inputs[k].get(q) for q in ("source_id","available_at","period","unit","currency")} for k in REQUIRED_TOWER_INPUTS},"evidence_gaps":[n for n,p in (("peer_valuation",bool(peer)),("historical_valuation",bool(hist)),("contract_renewal_evidence",False)) if not p],"confidence":"MEDIUM" if peer and hist else "LOW","investment_attractiveness":"RESEARCH_ONLY","execution_eligible":False,"certified":False,"investment_certified":False}
