const number=(v)=>v==null||v===''||!Number.isFinite(Number(v))?null:Number(v);
const round=(v,d=6)=>v==null?null:Number(v.toFixed(d));
const mean=(xs)=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;

function averageRanks(values){const indexed=values.map((value,index)=>({value,index})).sort((a,b)=>a.value-b.value);const ranks=Array(values.length);for(let i=0;i<indexed.length;){let j=i;while(j+1<indexed.length&&indexed[j+1].value===indexed[i].value)j++;const rank=(i+j+2)/2;for(let k=i;k<=j;k++)ranks[indexed[k].index]=rank;i=j+1;}return ranks;}
function pearson(a,b){const am=mean(a),bm=mean(b);let numerator=0,aa=0,bb=0;for(let i=0;i<a.length;i++){const x=a[i]-am,y=b[i]-bm;numerator+=x*y;aa+=x*x;bb+=y*y;}return aa&&bb?numerator/Math.sqrt(aa*bb):null;}
export function spearmanRankIc(forecasts,actuals){if(forecasts.length!==actuals.length||forecasts.length<3)return null;return round(pearson(averageRanks(forecasts),averageRanks(actuals)));}

export function rankForecastCrossSection(rows){const eligible=(rows||[]).filter((r)=>number(r.expected_alpha_pct)!=null).sort((a,b)=>Number(b.expected_alpha_pct)-Number(a.expected_alpha_pct)||String(a.symbol).localeCompare(String(b.symbol)));const n=eligible.length;return eligible.map((row,index)=>{const rank=index+1,percentile=n===1?1:1-index/(n-1),decile=Math.min(10,Math.max(1,Math.ceil(percentile*10)));return{forecast_id:row.id,forecast_date:String(row.forecast_time).slice(0,10),horizon:row.horizon,symbol:row.symbol,universe_size:n,forecast_rank:rank,percentile:round(percentile),decile};});}

export function evaluateCrossSection(forecasts,outcomes){const outcomeById=new Map((outcomes||[]).map((o)=>[o.forecast_id,o]));const completed=forecasts.filter((f)=>number(outcomeById.get(f.id)?.actual_alpha_pct)!=null);const ranks=rankForecastCrossSection(completed),deciles={};for(const rank of ranks){const value=number(outcomeById.get(rank.forecast_id).actual_alpha_pct);(deciles[`D${rank.decile}`]??=[]).push(value);}const decileReturns=Object.fromEntries(Object.entries(deciles).map(([key,values])=>[key,round(mean(values))]));const predicted=completed.map((f)=>Number(f.expected_alpha_pct)),actual=completed.map((f)=>Number(outcomeById.get(f.id).actual_alpha_pct));return{observations:completed.length,rank_ic:spearmanRankIc(predicted,actual),decile_returns:decileReturns,top_bottom_spread:decileReturns.D10!=null&&decileReturns.D1!=null?round(decileReturns.D10-decileReturns.D1):null,point_in_time_safe:true};}

export function buildWalkForwardFolds(dates,{minimumTrainPeriods=20,testPeriods=1,rollingTrainPeriods=null}={}){const periods=[...new Set(dates.map(String))].sort(),folds=[];for(let split=minimumTrainPeriods;split+testPeriods<=periods.length;split+=testPeriods){const trainStart=rollingTrainPeriods?Math.max(0,split-rollingTrainPeriods):0;const train=periods.slice(trainStart,split),test=periods.slice(split,split+testPeriods);folds.push({fold:folds.length+1,train_start:train[0],train_end:train.at(-1),test_start:test[0],test_end:test.at(-1),training_periods:train.length,test_periods:test.length,leakage_safe:train.at(-1)<test[0]});}return folds;}

export function buildPointInTimeTrainingRows(featureSnapshots,forecasts,outcomes){const featureById=new Map(featureSnapshots.map((x)=>[x.id,x])),outcomeByForecast=new Map(outcomes.map((x)=>[x.forecast_id,x]));return forecasts.flatMap((forecast)=>{const snapshot=featureById.get(forecast.feature_snapshot_id),outcome=outcomeByForecast.get(forecast.id);if(!snapshot||!outcome||number(outcome.actual_alpha_pct)==null)return[];if(new Date(outcome.observed_at)<=new Date(snapshot.captured_at))throw new Error(`Point-in-time violation for forecast ${forecast.id}.`);return[{forecast_id:forecast.id,symbol:forecast.symbol,as_of:snapshot.captured_at,horizon:forecast.horizon,feature_version:snapshot.feature_version,features:snapshot.features,target_return:Number(outcome.actual_alpha_pct),target_direction:Number(outcome.actual_alpha_pct)>0?1:0,target_observed_at:outcome.observed_at,point_in_time_safe:true}];});}

export function summarizeRankIc(rows){const values=rows.map((r)=>number(r.rank_ic)).filter((v)=>v!=null),avg=mean(values);if(!values.length)return{periods:0,mean_rank_ic:null,ic_std_dev:null,positive_periods_pct:null,icir:null};const variance=mean(values.map((v)=>(v-avg)**2)),std=Math.sqrt(variance);return{periods:values.length,mean_rank_ic:round(avg),ic_std_dev:round(std),positive_periods_pct:round(100*values.filter((v)=>v>0).length/values.length,2),icir:std?round(avg/std):null};}
