import test from 'node:test';import assert from 'node:assert/strict';
import {buildPointInTimeTrainingRows,buildWalkForwardFolds,evaluateCrossSection,rankForecastCrossSection,spearmanRankIc,summarizeRankIc} from './forecastV2Validation.js';
const forecasts=[{id:'a',symbol:'A',forecast_time:'2026-08-01T10:00:00Z',horizon:'5d',expected_alpha_pct:3},{id:'b',symbol:'B',forecast_time:'2026-08-01T10:00:00Z',horizon:'5d',expected_alpha_pct:2},{id:'c',symbol:'C',forecast_time:'2026-08-01T10:00:00Z',horizon:'5d',expected_alpha_pct:-1}];
test('ranks the highest forecast into the highest decile',()=>{const rows=rankForecastCrossSection(forecasts);assert.equal(rows[0].forecast_rank,1);assert.equal(rows[0].decile,10);assert.equal(rows.at(-1).decile,1);});
test('calculates Spearman Rank IC and realized spread',()=>{assert.equal(spearmanRankIc([3,2,1],[30,20,10]),1);const x=evaluateCrossSection(forecasts,[{forecast_id:'a',actual_alpha_pct:2},{forecast_id:'b',actual_alpha_pct:1},{forecast_id:'c',actual_alpha_pct:-2}]);assert.equal(x.rank_ic,1);assert.equal(x.top_bottom_spread,4);});
test('creates strictly past-only walk-forward folds',()=>{const dates=Array.from({length:25},(_,i)=>`2026-01-${String(i+1).padStart(2,'0')}`);const folds=buildWalkForwardFolds(dates,{minimumTrainPeriods:20});assert.equal(folds.length,5);assert.ok(folds.every((f)=>f.leakage_safe));});
test('builds separate regression and direction targets',()=>{const rows=buildPointInTimeTrainingRows([{id:'s',captured_at:'2026-08-01T10:00:00Z',feature_version:'v1',features:{x:1}}],[{id:'f',feature_snapshot_id:'s',symbol:'A',horizon:'5d'}],[{forecast_id:'f',actual_alpha_pct:-1.5,observed_at:'2026-08-08T10:00:00Z'}]);assert.equal(rows[0].target_return,-1.5);assert.equal(rows[0].target_direction,0);});
test('rejects target leakage',()=>{assert.throws(()=>buildPointInTimeTrainingRows([{id:'s',captured_at:'2026-08-08T10:00:00Z',features:{}}],[{id:'f',feature_snapshot_id:'s'}],[{forecast_id:'f',actual_alpha_pct:1,observed_at:'2026-08-01T10:00:00Z'}]),/Point-in-time violation/);});
test('summarizes Rank IC health',()=>{const x=summarizeRankIc([{rank_ic:.1},{rank_ic:-.05},{rank_ic:.15}]);assert.equal(x.periods,3);assert.equal(x.positive_periods_pct,66.67);assert.ok(x.icir>0);});
