import crypto from 'node:crypto';

const creds=()=>({url:String(process.env.SUPABASE_URL||'').replace(/\/$/,''),key:String(process.env.SUPABASE_SERVICE_ROLE_KEY||'')});
async function rest(path,{method='GET',body,prefer}={}){const{url,key}=creds();if(!url||!key)throw Error('Supabase service credentials missing');const response=await fetch(url+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body?JSON.stringify(body):undefined});if(!response.ok)throw Error('Insider Trading storage '+response.status+': '+(await response.text()).slice(0,240));const text=await response.text();return text?JSON.parse(text):[]}
const uuid=value=>{const hash=crypto.createHash('sha256').update(String(value)).digest('hex').slice(0,32);return hash.slice(0,8)+'-'+hash.slice(8,12)+'-'+hash.slice(12,16)+'-'+hash.slice(16,20)+'-'+hash.slice(20)};
const clean=value=>value==null||String(value).trim()===''?null:String(value).trim();
const lower=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const number=value=>{const parsed=Number(String(value??'').replace(/[,%₹$]/g,'').trim());return Number.isFinite(parsed)?parsed:null};
const date=value=>{if(!value)return null;const parsed=new Date(value);if(!Number.isFinite(parsed.getTime()))return null;return parsed.toISOString().slice(0,10)};
const valueOf=(row,...names)=>{for(const name of names){const direct=row.values?.[name];if(direct!=null&&String(direct).trim()!=='')return direct;const key=Object.keys(row.values||{}).find(item=>lower(item)===lower(name));if(key)return row.values[key]}return null};
const modeSignal=(action,mode)=>{const text=lower(mode),side=lower(action);if(/esop|employee stock|option/.test(text))return 'compensation';if(/conversion|convertible|warrant/.test(text))return 'conversion';if(/market purchase|open market|market sale/.test(text))return side.includes('disposal')||side.includes('sale')?'open_market_sale':'open_market_purchase';if(side.includes('disposal')||side.includes('sale'))return 'disposal';if(side.includes('acquisition')||side.includes('purchase'))return 'acquisition';return 'other'};
function normalize(payload){const output=[],errors=[];for(const sheet of payload.sheets||[])for(const row of sheet.rows||[]){const stock=clean(valueOf(row,'Stock')),insider=clean(valueOf(row,'Client Name')),action=clean(valueOf(row,'Action*','Action')),reported=date(valueOf(row,'Reported To/By Exchange','Reported Date'));if(!stock||!insider||!action||!reported){errors.push({sourceRow:row.sourceRow,sheet:sheet.name,reason:'Stock, client, action or reported date is missing'});continue}const mode=clean(valueOf(row,'Mode'));const period=String(valueOf(row,'Period')||'').match(/(\d{1,2}\s+[A-Za-z]{3}\s+\d{4})(?:\s+-?\s*(\d{1,2}\s+[A-Za-z]{3}\s+\d{4}))?/);const record={country:'IN',stock_name:stock,insider_name:insider,insider_category:clean(valueOf(row,'Client Category')),action,reported_date:reported,period_from:date(period?.[1]),period_to:date(period?.[2]||period?.[1]),quantity:number(valueOf(row,'Quantity')),post_transaction_holding:number(valueOf(row,'Post Transaction Holding')),traded_percent:number(valueOf(row,'Traded %')),average_price:number(valueOf(row,'Avg. Price','Avg Price')),transaction_value:number(valueOf(row,'Value')),regulation:clean(valueOf(row,'Regulation (Insider/SAST)')),security_type:clean(valueOf(row,'Security Type')),transaction_mode:mode,signal_type:modeSignal(action,mode),source_file:payload.filename,source_sheet:sheet.name,source_row:row.sourceRow,is_public:true};record.natural_key=crypto.createHash('sha256').update([record.country,lower(stock),lower(insider),lower(action),reported,record.period_from,record.quantity,record.transaction_value,lower(mode)].join('|')).digest('hex');record.id=uuid('insider|'+record.natural_key);output.push(record)}return{rows:[...new Map(output.map(record=>[record.natural_key,record])).values()],errors}}
async function existingKeys(rows){const keys=new Set();for(let index=0;index<rows.length;index+=100){const query=rows.slice(index,index+100).map(row=>row.natural_key).join(',');if(query)(await rest('insider_trades?select=natural_key&natural_key=in.('+query+')')).forEach(row=>keys.add(row.natural_key))}return keys}
export async function previewInsiderImport(payload){const normalized=normalize(payload),existing=await existingKeys(normalized.rows),inserted=normalized.rows.filter(row=>!existing.has(row.natural_key)).length;return{valid:normalized.rows.length>0,counts:{inserted,updated:normalized.rows.length-inserted,rejected:normalized.errors.length,total:normalized.rows.length+normalized.errors.length},errors:normalized.errors.slice(0,50),coverage:{from:normalized.rows.map(row=>row.reported_date).sort()[0]||null,to:normalized.rows.map(row=>row.reported_date).sort().at(-1)||null,companies:new Set(normalized.rows.map(row=>lower(row.stock_name))).size}}}
export async function approveInsiderImport(payload){const preview=await previewInsiderImport(payload);if(!preview.valid)throw Error('Workbook contains no valid India insider records');const{rows}=normalize(payload),importId=uuid('insider-import|IN|'+payload.fileHash);await rest('insider_trading_imports?on_conflict=id',{method:'POST',body:[{id:importId,country:'IN',source_file:payload.filename,file_sha256:payload.fileHash,status:'processing',date_from:preview.coverage.from,date_to:preview.coverage.to,records_seen:preview.counts.total,records_accepted:rows.length,records_rejected:preview.counts.rejected}],prefer:'resolution=merge-duplicates,return=minimal'});for(let index=0;index<rows.length;index+=100)await rest('insider_trades?on_conflict=id',{method:'POST',body:rows.slice(index,index+100).map(row=>({...row,import_id:importId,updated_at:new Date().toISOString()})),prefer:'resolution=merge-duplicates,return=minimal'});await rest('insider_trading_imports?id=eq.'+importId,{method:'PATCH',body:{status:'completed',completed_at:new Date().toISOString()},prefer:'return=minimal'});return{...preview,approved:true,importId}}
export async function getInsiderAdminOverview(){const[history,count]=await Promise.all([rest('insider_trading_imports?select=*&order=created_at.desc&limit=40'),rest('insider_trades?select=id',{prefer:'count=exact'})]);return{history,count:count.length}}
export async function getInsiderActivity(query={}){const params=new URLSearchParams({select:'*',country:'eq.IN',is_public:'eq.true',order:'reported_date.desc,transaction_value.desc',limit:String(Math.min(Number(query.limit)||1000,2000))});if(query.from)params.set('reported_date','gte.'+query.from);if(query.to)params.append('reported_date','lte.'+query.to);const rows=await rest('insider_trades?'+params.toString()),search=lower(query.search),filtered=rows.filter(row=>(!search||lower(row.stock_name+' '+row.insider_name).includes(search))&&(!query.signal||query.signal==='all'||row.signal_type===query.signal));const values=filtered.map(row=>Number(row.transaction_value)||0),purchase=filtered.filter(row=>['open_market_purchase','acquisition'].includes(row.signal_type)),sale=filtered.filter(row=>['open_market_sale','disposal'].includes(row.signal_type));const groups=Object.values(filtered.reduce((acc,row)=>{const key=row.reported_date;acc[key]??={date:key,count:0,value:0,purchases:0,sales:0};acc[key].count++;acc[key].value+=Number(row.transaction_value)||0;if(purchase.includes(row))acc[key].purchases++;if(sale.includes(row))acc[key].sales++;return acc},{})).sort((a,b)=>b.date.localeCompare(a.date));return{country:'IN',trades:filtered,daily:groups,stats:{records:filtered.length,companies:new Set(filtered.map(row=>lower(row.stock_name))).size,totalValue:values.reduce((a,b)=>a+b,0),purchaseValue:purchase.reduce((sum,row)=>sum+(Number(row.transaction_value)||0),0),saleValue:sale.reduce((sum,row)=>sum+(Number(row.transaction_value)||0),0),latestDate:filtered[0]?.reported_date||null}}}
