import crypto from 'node:crypto';
const creds=()=>({url:String(process.env.SUPABASE_URL||'').replace(/\/$/,''),key:String(process.env.SUPABASE_SERVICE_ROLE_KEY||'')});
async function rest(path,{method='GET',body,prefer}={}){const{url,key}=creds();if(!url||!key)throw Error('Supabase service credentials missing');const r=await fetch(url+'/rest/v1/'+path,{method,headers:{apikey:key,Authorization:'Bearer '+key,'Content-Type':'application/json',...(prefer?{Prefer:prefer}:{})},body:body?JSON.stringify(body):undefined});if(!r.ok)throw Error('Private Markets storage '+r.status+': '+(await r.text()).slice(0,200));const text=await r.text();return text?JSON.parse(text):[]}
const id=value=>{const h=crypto.createHash('sha256').update(value).digest('hex').slice(0,32);return h.slice(0,8)+'-'+h.slice(8,12)+'-'+h.slice(12,16)+'-'+h.slice(16,20)+'-'+h.slice(20)};
const clean=value=>value==null||String(value).trim()===''?null:String(value).trim();
const num=value=>{const n=Number(String(value??'').replace(/,/g,'').replace('%',''));return Number.isFinite(n)?n:null};
const lower=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const company=row=>clean(row.values['Company']||row.values['Company Name']);
function classify(payload){const out=[];for(const sheet of payload.sheets||[]){let kind=null;if(sheet.name==='Equity Deal Book')kind='deal';if(sheet.name==='Seeking to Sell or Divest')kind='sale_divestment';if(sheet.name==='LBO Targeting')kind='lbo';if(sheet.name==='Distressed Companies')kind='distressed';if(sheet.name==='Actice Financial Buyers'||sheet.name==='Active Financial Buyers')kind='investor';if(kind)for(const row of sheet.rows||[])out.push({...row,sheet:sheet.name,kind})}return out}
const keyOf=row=>row.kind==='deal'?[clean(row.values['Deal Date']),lower(company(row)),lower(row.values['Transaction Type'])].join('|'):row.kind==='investor'?lower(company(row)):[row.kind,lower(company(row))].join('|');
async function existingMaps(){const[deals,opps,investors]=await Promise.all([rest('private_market_deals?select=id,company_name,deal_date,transaction_type'),rest('private_market_opportunities?select=id,company_name,opportunity_type'),rest('private_market_investors?select=id,name')]);return{deal:new Map(deals.map(r=>[[clean(r.deal_date),lower(r.company_name),lower(r.transaction_type)].join('|'),r.id])),opportunity:new Map(opps.map(r=>[[r.opportunity_type,lower(r.company_name)].join('|'),r.id])),investor:new Map(investors.map(r=>[lower(r.name),r.id]))}}
export async function previewPrivateMarketsImport(payload){const rows=classify(payload),errors=[];rows.forEach(row=>{if(!company(row))errors.push({sourceRow:row.sourceRow,sheet:row.sheet,reason:'Company name is missing'})});const maps=await existingMaps();let inserted=0,updated=0;rows.filter(row=>company(row)).forEach(row=>{const map=row.kind==='deal'?maps.deal:row.kind==='investor'?maps.investor:maps.opportunity;(map.has(keyOf(row))?updated++:inserted++)});return{valid:rows.length>0&&!errors.length,dataset:rows.some(r=>r.kind==='deal')?'india_deal_market':'global_private_markets',counts:{inserted,updated,unchanged:0,rejected:errors.length,total:rows.length},errors}}
async function postBatches(table,rows){for(let i=0;i<rows.length;i+=100)await rest(table+'?on_conflict=id',{method:'POST',body:rows.slice(i,i+100),prefer:'resolution=merge-duplicates,return=minimal'})}
export async function approvePrivateMarketsImport(payload){const preview=await previewPrivateMarketsImport(payload);if(!preview.valid)throw Error('Workbook validation failed');const rows=classify(payload),maps=await existingMaps();const domains=[...new Set(rows.map(r=>r.kind==='deal'?'india_deal_market':r.kind==='investor'?'global_investor_network':'global_opportunity_intelligence'))];const result={runs:[],counts:preview.counts};
 for(const domain of domains){const selected=rows.filter(r=>(r.kind==='deal'?'india_deal_market':r.kind==='investor'?'global_investor_network':'global_opportunity_intelligence')===domain),runId=id(payload.fileHash+'|'+domain),effective=selected.map(r=>clean(r.values['Deal Date'])).filter(Boolean).sort().at(-1)||null;
  await rest('private_market_ingestion_runs?on_conflict=id',{method:'POST',body:[{id:runId,source_file:payload.filename,file_sha256:payload.fileHash,dataset_domain:domain,effective_date:effective,status:'processing',records_seen:selected.length,records_accepted:selected.length,records_rejected:0}],prefer:'resolution=merge-duplicates,return=minimal'});
  const sources=[],deals=[],opportunities=[],investors=[];
  for(const row of selected){const name=company(row);if(!name)continue;const sourceId=id(runId+'|'+row.sheet+'|'+row.sourceRow),natural=keyOf(row);sources.push({id:sourceId,ingestion_run_id:runId,source_file:payload.filename,source_sheet:row.sheet,source_row:row.sourceRow,effective_date:effective,original_values:row.values,normalized_values:{company:name,kind:row.kind,natural_key:natural}});
   if(row.kind==='deal'){const type=clean(row.values['Transaction Type'])||'Other',market=/ipo|bulk|block/i.test(type)?'public':'core';deals.push({id:maps.deal.get(natural)||id('deal|'+natural),company_name:name,deal_date:clean(row.values['Deal Date']),deal_size_inr_mn:num(row.values['Deal Size (₹ Mn)']),stake_percent:num(row.values['Total Stake %']),pre_money_valuation_inr_mn:num(row.values['Pre Money Valuation']),post_money_valuation_inr_mn:num(row.values['Post Money Valuation']),business_description:clean(row.values['Business Description']),location:clean(row.values['Location']),transaction_type:type,transaction_subcategory:clean(row.values['Transaction Subcategory']),deal_type:clean(row.values['Deal Type']),market_domain:market,source_id:sourceId,ingestion_run_id:runId,source_file:payload.filename,source_sheet:row.sheet,source_row:row.sourceRow,effective_date:effective,is_public:true})}
   else if(row.kind==='investor'){investors.push({id:maps.investor.get(natural)||id('investor|'+natural),name,normalized_name:natural,headquarters:clean(row.values['Geographic Locations']),source_id:sourceId,is_public:true})}
   else opportunities.push({id:maps.opportunity.get(natural)||id('opportunity|'+natural),company_name:name,opportunity_type:row.kind,geography_scope:'global',observed_metrics:Object.fromEntries(Object.entries(row.values).filter(([key])=>!['Company','Company Name'].includes(key))),screen_rules:{source:'licensed_workbook'},coverage:Object.values(row.values).filter(v=>v!==null&&v!=='').length/Math.max(1,Object.keys(row.values).length),source_id:sourceId,ingestion_run_id:runId,is_public:true});
  }
  await postBatches('private_market_sources',sources);if(deals.length)await postBatches('private_market_deals',deals);if(opportunities.length)await postBatches('private_market_opportunities',opportunities);if(investors.length)await postBatches('private_market_investors',investors);
  await rest('private_market_ingestion_runs?id=eq.'+runId,{method:'PATCH',body:{status:'completed',completed_at:new Date().toISOString()},prefer:'return=minimal'});result.runs.push({id:runId,domain,records:selected.length});
 }return{...preview,...result,approved:true}}
export async function getPrivateMarketsAdminOverview(){const[history,reviews,deals,opps,investors,transactions]=await Promise.all([rest('private_market_ingestion_runs?select=*&order=created_at.desc&limit=30'),rest('private_market_entity_review?select=*&status=eq.pending&order=created_at.desc&limit=50'),rest('private_market_deals?select=id'),rest('private_market_opportunities?select=id'),rest('private_market_investors?select=id'),rest('private_market_investor_transactions?select=id')]);return{history,reviews,counts:{deals:deals.length,opportunities:opps.length,investors:investors.length,transactions:transactions.length}}}
export async function resolvePrivateMarketsEntity(idValue,status){if(!['approved','rejected'].includes(status))throw Error('Invalid review status');await rest('private_market_entity_review?id=eq.'+encodeURIComponent(idValue),{method:'PATCH',body:{status,reviewed_at:new Date().toISOString()},prefer:'return=minimal'});return{ok:true}}
