create table if not exists public.institutional_managers (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  display_name text not null,
  legal_name text not null,
  cik text not null unique,
  strategy text,
  quality_weight numeric not null default 1 check (quality_weight between 0 and 2),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.institutional_filings (
  id uuid primary key default gen_random_uuid(),
  manager_id uuid not null references public.institutional_managers(id) on delete cascade,
  accession_number text not null unique,
  form_type text not null check (form_type in ('13F-HR', '13F-HR/A')),
  report_date date not null,
  filed_at timestamptz not null,
  primary_document text,
  amendment_type text not null default 'original',
  is_amendment boolean not null default false,
  is_active boolean not null default true,
  source_url text not null,
  holdings_count integer not null default 0,
  total_value_usd numeric not null default 0,
  ingested_at timestamptz not null default now()
);

create table if not exists public.security_identifier_history (
  id uuid primary key default gen_random_uuid(),
  cusip text not null,
  ticker text,
  issuer_name text,
  valid_from date not null default '1900-01-01',
  valid_to date,
  source text not null default 'manual',
  manually_verified boolean not null default false,
  updated_at timestamptz not null default now(),
  unique (cusip, valid_from)
);

create table if not exists public.institutional_holdings (
  id bigint generated by default as identity primary key,
  filing_id uuid not null references public.institutional_filings(id) on delete cascade,
  manager_id uuid not null references public.institutional_managers(id) on delete cascade,
  report_date date not null,
  cusip text not null,
  issuer_name text not null,
  title_of_class text,
  ticker text,
  value_usd numeric not null default 0,
  shares numeric not null default 0,
  share_type text,
  put_call text,
  investment_discretion text,
  other_manager text,
  voting_sole numeric,
  voting_shared numeric,
  voting_none numeric,
  portfolio_weight numeric not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists institutional_holdings_filing_security_uq
  on public.institutional_holdings
  (filing_id, cusip, coalesce(title_of_class, ''), coalesce(put_call, ''), coalesce(investment_discretion, ''));

create table if not exists public.holding_changes (
  id bigint generated by default as identity primary key,
  filing_id uuid not null references public.institutional_filings(id) on delete cascade,
  manager_id uuid not null references public.institutional_managers(id) on delete cascade,
  report_date date not null,
  cusip text not null,
  ticker text,
  issuer_name text not null,
  change_type text not null check (change_type in ('new', 'increased', 'reduced', 'exited')),
  current_shares numeric not null default 0,
  previous_shares numeric not null default 0,
  share_change numeric not null default 0,
  share_change_pct numeric,
  current_weight numeric not null default 0,
  previous_weight numeric not null default 0,
  weight_change numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.institutional_signals (
  id uuid primary key default gen_random_uuid(),
  scope_type text not null check (scope_type in ('fund', 'stock')),
  scope_id text not null,
  as_of date not null,
  signal_type text not null check (signal_type in ('conviction', 'accumulation', 'new_idea', 'exit_pressure', 'consensus')),
  score numeric not null check (score between 0 and 100),
  label text not null,
  components jsonb not null default '{}',
  explanation text not null,
  calculated_at timestamptz not null default now(),
  unique (scope_type, scope_id, as_of, signal_type)
);

create table if not exists public.institutional_filing_alerts (
  id uuid primary key default gen_random_uuid(),
  filing_id uuid not null references public.institutional_filings(id) on delete cascade,
  manager_id uuid not null references public.institutional_managers(id) on delete cascade,
  alert_type text not null,
  severity text not null default 'info' check (severity in ('info', 'notable', 'high')),
  title text not null,
  body text not null,
  security_key text,
  is_read boolean not null default false,
  created_at timestamptz not null default now(),
  unique (filing_id, alert_type, title)
);

create table if not exists public.institutional_corrections (
  id uuid primary key default gen_random_uuid(),
  entity_type text not null check (entity_type in ('manager', 'security')),
  entity_key text not null,
  field_name text not null,
  old_value text,
  new_value text,
  reason text,
  actor text not null default 'admin',
  created_at timestamptz not null default now()
);

create index if not exists institutional_filings_manager_period_idx on public.institutional_filings(manager_id, report_date desc, filed_at desc);
create index if not exists institutional_holdings_filing_weight_idx on public.institutional_holdings(filing_id, portfolio_weight desc);
create index if not exists institutional_holdings_cusip_idx on public.institutional_holdings(cusip, report_date desc);
create index if not exists institutional_holdings_ticker_idx on public.institutional_holdings(ticker, report_date desc);
create index if not exists holding_changes_filing_type_idx on public.holding_changes(filing_id, change_type);
create index if not exists institutional_alerts_created_idx on public.institutional_filing_alerts(created_at desc);

alter table public.institutional_managers enable row level security;
alter table public.institutional_filings enable row level security;
alter table public.security_identifier_history enable row level security;
alter table public.institutional_holdings enable row level security;
alter table public.holding_changes enable row level security;
alter table public.institutional_signals enable row level security;
alter table public.institutional_filing_alerts enable row level security;
alter table public.institutional_corrections enable row level security;

insert into public.institutional_managers (slug, display_name, legal_name, cik, strategy, quality_weight)
values
  ('berkshire-hathaway', 'Berkshire Hathaway', 'BERKSHIRE HATHAWAY INC', '0001067983', 'Concentrated quality and value', 1.20),
  ('pershing-square', 'Pershing Square', 'PERSHING SQUARE CAPITAL MANAGEMENT, L.P.', '0001336528', 'Concentrated activist', 1.15),
  ('appaloosa-management', 'Appaloosa Management', 'APPALOOSA LP', '0001656456', 'Opportunistic value', 1.05),
  ('baupost-group', 'Baupost Group', 'BAUPOST GROUP LLC/MA', '0001061768', 'Deep value and special situations', 1.15),
  ('third-point', 'Third Point', 'THIRD POINT LLC', '0001040273', 'Event-driven and activist', 1.05),
  ('greenlight-capital', 'Greenlight Capital', 'GREENLIGHT CAPITAL INC', '0001079114', 'Value-oriented long/short', 1.00),
  ('coatue-management', 'Coatue Management', 'COATUE MANAGEMENT LLC', '0001135730', 'Technology and growth', 1.00),
  ('viking-global', 'Viking Global', 'VIKING GLOBAL INVESTORS LP', '0001103804', 'Fundamental growth', 1.05),
  ('lone-pine-capital', 'Lone Pine Capital', 'LONE PINE CAPITAL LLC', '0001061165', 'Fundamental growth', 1.00),
  ('tiger-global', 'Tiger Global Management', 'TIGER GLOBAL MANAGEMENT LLC', '0001167483', 'Technology and growth', 0.95)
on conflict (cik) do nothing;

comment on table public.institutional_filings is 'Point-in-time SEC 13F filing versions. filed_at is the public knowable timestamp.';
comment on table public.institutional_signals is 'Transparent AGI 13F-derived scores with formula inputs stored in components.';

revoke all on table public.institutional_managers from anon, authenticated;
revoke all on table public.institutional_filings from anon, authenticated;
revoke all on table public.security_identifier_history from anon, authenticated;
revoke all on table public.institutional_holdings from anon, authenticated;
revoke all on table public.holding_changes from anon, authenticated;
revoke all on table public.institutional_signals from anon, authenticated;
revoke all on table public.institutional_filing_alerts from anon, authenticated;
revoke all on table public.institutional_corrections from anon, authenticated;

grant select, insert, update, delete on table public.institutional_managers to service_role;
grant select, insert, update, delete on table public.institutional_filings to service_role;
grant select, insert, update, delete on table public.security_identifier_history to service_role;
grant select, insert, update, delete on table public.institutional_holdings to service_role;
grant select, insert, update, delete on table public.holding_changes to service_role;
grant select, insert, update, delete on table public.institutional_signals to service_role;
grant select, insert, update, delete on table public.institutional_filing_alerts to service_role;
grant select, insert, update, delete on table public.institutional_corrections to service_role;
grant usage, select on sequence public.institutional_holdings_id_seq to service_role;
grant usage, select on sequence public.holding_changes_id_seq to service_role;
