import React, { useEffect, useState } from 'react';
import { toolsRequest } from '@/pages/FinanceToolsPage';
export default function FinanceToolsAdmin() {
  const [rows, setRows] = useState([]), [error, setError] = useState(''), [loading, setLoading] = useState(true), [busy, setBusy] = useState('');
  async function load() { setLoading(true); setError(''); try { setRows((await toolsRequest('/admin')).applications); } catch(e) { setError(e.message); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  async function review(id, status) { setBusy(id); setError(''); try { await toolsRequest(`/admin/${id}`, { method: 'PATCH', body: JSON.stringify({ status }) }); await load(); } catch(e) { setError(e.message); } finally { setBusy(''); } }
  return <main className="mx-auto max-w-5xl p-6"><h1 className="font-serif text-3xl">Finance Tools applications</h1><p className="my-4 text-slate-600">Private launch queue. Marking an application reviewed does not publish it, accept money or reserve a rank.</p><button className="border px-4 py-2" onClick={load}>Refresh</button>{error && <p role="alert" className="my-4 text-red-700">{error}</p>}{loading ? <p role="status">Loading…</p> : !rows.length ? <p className="my-8">No applications yet.</p> : rows.map(r => <article key={r.id} className="my-5 border bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><h2 className="text-xl font-semibold">{r.name}</h2><span>{r.status}</span></div><p className="my-2">{r.description}</p><a href={r.url} target="_blank" rel="noopener noreferrer" className="break-all underline">{r.url}</a><p className="my-3 text-sm">{r.category} · Budget ₹{r.budget.toLocaleString('en-IN')} (non-binding)</p><p className="text-sm">{r.email} · {new Date(r.created).toLocaleString('en-IN')}</p><div className="mt-4 flex flex-wrap gap-3">{['reviewed', 'rejected', 'pending'].map(status => <button key={status} disabled={busy === r.id} onClick={() => review(r.id, status)} className="border px-3 py-2 text-sm disabled:opacity-50">Mark {status}</button>)}</div></article>)}</main>;
}
