import { useEffect, useMemo, useState } from 'react';
import { AlertTriangle, CheckCircle2, Database, ExternalLink, FileClock, Landmark, Loader2, RefreshCw, Save, Search, ShieldCheck } from 'lucide-react';
import { getInstitutionalAdmin, markInstitutionalAlert, refreshInstitutionalFilings, saveInstitutionalSecurityMapping, updateInstitutionalManager } from '@/lib/institutionalHoldingsApi';

function Pill({ children, tone = 'slate' }) {
  const styles = { slate: 'bg-slate-100 text-slate-600', green: 'bg-emerald-50 text-emerald-700', amber: 'bg-amber-50 text-amber-700', red: 'bg-rose-50 text-rose-700' };
  return <span className={`rounded-full px-2.5 py-1 text-[10px] font-bold uppercase tracking-[.1em] ${styles[tone]}`}>{children}</span>;
}

export default function InstitutionalHoldingsAdmin() {
  const [data, setData] = useState(null);
  const [selectedId, setSelectedId] = useState('');
  const [managerDraft, setManagerDraft] = useState({});
  const [refreshTarget, setRefreshTarget] = useState('');
  const [quarters, setQuarters] = useState(4);
  const [mapping, setMapping] = useState({ cusip: '', ticker: '', issuer_name: '', reason: '' });
  const [query, setQuery] = useState('');
  const [working, setWorking] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');

  const load = async () => {
    setError('');
    try {
      const result = await getInstitutionalAdmin();
      setData(result);
      const first = selectedId || result.managers?.[0]?.id || '';
      setSelectedId(first);
      setRefreshTarget((value) => value || result.managers?.[0]?.slug || '');
    } catch (err) { setError(err.message); }
  };
  useEffect(() => { void load(); }, []);
  const selected = useMemo(() => data?.managers?.find((row) => row.id === selectedId), [data, selectedId]);
  useEffect(() => { if (selected) setManagerDraft({ display_name: selected.display_name, legal_name: selected.legal_name, cik: selected.cik, strategy: selected.strategy || '', quality_weight: selected.quality_weight, active: selected.active, reason: '' }); }, [selected]);
  const unresolved = useMemo(() => (data?.unresolved || []).filter((row) => `${row.issuer_name} ${row.cusip}`.toLowerCase().includes(query.toLowerCase())), [data, query]);

  const run = async (key, operation, success) => {
    setWorking(key); setError(''); setMessage('');
    try { const result = await operation(); setMessage(typeof success === 'function' ? success(result) : success); await load(); }
    catch (err) { setError(err.message); }
    finally { setWorking(''); }
  };

  if (!data && !error) return <div className="flex min-h-[70vh] items-center justify-center bg-slate-50"><Loader2 className="h-8 w-8 animate-spin text-slate-400" /></div>;
  return <div className="min-h-full bg-[#f5f6f7] p-5 text-slate-900 sm:p-8"><div className="mx-auto max-w-[1500px]"><header className="flex flex-col gap-5 border-b border-slate-200 pb-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.2em] text-amber-700">SEC disclosure operations</p><h1 className="mt-2 font-serif text-4xl font-bold text-[#102b3a]">Institutional Holdings CMS</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Refresh 13F filings, verify legal filer identities, resolve CUSIPs and review every generated client alert.</p></div><a href="/institutional-holdings" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-[#123b4b] px-4 py-3 text-xs font-bold text-white">Open client page <ExternalLink className="h-4 w-4" /></a></header>{error ? <div className="mt-5 flex items-center gap-3 rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-700"><AlertTriangle className="h-5 w-5" />{error}</div> : null}{message ? <div className="mt-5 flex items-center gap-3 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-700"><CheckCircle2 className="h-5 w-5" />{message}</div> : null}

      <section className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['Managers', data?.managers?.length || 0, Landmark], ['Filing versions', data?.filings?.length || 0, FileClock], ['Unresolved CUSIPs', data?.unresolved?.length || 0, Database], ['Unread alerts', data?.alerts?.filter((row) => !row.is_read).length || 0, ShieldCheck]].map(([label, value, Icon]) => <div key={label} className="rounded-xl border border-slate-200 bg-white p-5"><Icon className="h-5 w-5 text-amber-700" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[.14em] text-slate-400">{label}</p><p className="mt-2 font-serif text-3xl font-bold text-[#102b3a]">{value}</p></div>)}</section>

      <section className="mt-7 rounded-xl border border-slate-200 bg-white p-6"><div className="grid gap-5 lg:grid-cols-[1fr_180px_160px_auto] lg:items-end"><label className="text-xs font-bold text-slate-600">SEC manager<select value={refreshTarget} onChange={(event) => setRefreshTarget(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 bg-white px-3 py-3 text-sm"><option value="all">All tracked managers</option>{data?.managers?.map((row) => <option key={row.id} value={row.slug}>{row.display_name}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Historical quarters<input type="number" min="1" max="16" value={quarters} onChange={(event) => setQuarters(event.target.value)} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-3 text-sm" /></label><div><p className="text-xs font-bold text-slate-600">SEC identity header</p><Pill tone={data?.sec_user_agent_configured ? 'green' : 'amber'}>{data?.sec_user_agent_configured ? 'Configured' : 'Using default'}</Pill></div><button disabled={Boolean(working)} onClick={() => run('refresh', () => refreshInstitutionalFilings({ managerSlug: refreshTarget, quarters: Number(quarters) }), (result) => `${result.results?.filter((row) => row.ok).length || 0} manager refreshes completed.`)} className="inline-flex items-center justify-center gap-2 rounded-lg bg-amber-700 px-5 py-3 text-sm font-bold text-white disabled:opacity-50">{working === 'refresh' ? <Loader2 className="h-4 w-4 animate-spin" /> : <RefreshCw className="h-4 w-4" />} Refresh SEC filings</button></div><p className="mt-4 text-xs leading-5 text-slate-500">Start with one manager and four quarters. Amendments remain separate filing versions, while the latest accepted version becomes the active portfolio.</p></section>

      <section className="mt-7 grid gap-7 xl:grid-cols-[.8fr_1.2fr]"><div className="overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="border-b border-slate-200 p-5"><h2 className="font-serif text-2xl font-bold text-[#102b3a]">Tracked managers</h2><p className="mt-1 text-xs text-slate-500">Confirm the legal SEC filer and CIK before refresh.</p></div><div className="max-h-[620px] overflow-y-auto">{data?.managers?.map((row) => <button key={row.id} onClick={() => setSelectedId(row.id)} className={`block w-full border-b border-slate-100 p-4 text-left ${selectedId === row.id ? 'bg-amber-50' : 'hover:bg-slate-50'}`}><div className="flex items-center justify-between gap-3"><strong className="text-sm">{row.display_name}</strong><Pill tone={row.active ? 'green' : 'slate'}>{row.active ? 'Active' : 'Paused'}</Pill></div><p className="mt-1 truncate text-xs text-slate-500">{row.legal_name}</p><p className="mt-1 font-mono text-[10px] text-slate-400">CIK {row.cik}</p></button>)}</div></div><div className="rounded-xl border border-slate-200 bg-white p-6"><h2 className="font-serif text-2xl font-bold text-[#102b3a]">Manager identity</h2>{selected ? <div className="mt-6 grid gap-4 md:grid-cols-2">{[['Display name', 'display_name'], ['Legal filer name', 'legal_name'], ['SEC CIK', 'cik'], ['Strategy label', 'strategy'], ['Quality weight', 'quality_weight']].map(([label, key]) => <label key={key} className={`text-xs font-bold text-slate-600 ${key === 'legal_name' || key === 'strategy' ? 'md:col-span-2' : ''}`}>{label}<input value={managerDraft[key] ?? ''} onChange={(event) => setManagerDraft((value) => ({ ...value, [key]: event.target.value }))} className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-3 text-sm" /></label>)}<label className="md:col-span-2 text-xs font-bold text-slate-600">Reason for correction<input value={managerDraft.reason || ''} onChange={(event) => setManagerDraft((value) => ({ ...value, reason: event.target.value }))} placeholder="Required context for the audit trail" className="mt-2 w-full rounded-lg border border-slate-200 px-3 py-3 text-sm" /></label><label className="flex items-center gap-3 text-sm"><input type="checkbox" checked={Boolean(managerDraft.active)} onChange={(event) => setManagerDraft((value) => ({ ...value, active: event.target.checked }))} /> Track this manager</label><div className="flex justify-end"><button disabled={Boolean(working)} onClick={() => run('manager', () => updateInstitutionalManager(selected.id, managerDraft), 'Manager identity saved and audited.')} className="inline-flex items-center gap-2 rounded-lg bg-[#123b4b] px-4 py-2.5 text-xs font-bold text-white"><Save className="h-4 w-4" /> Save manager</button></div></div> : null}</div></section>

      <section className="mt-7 overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="flex flex-col gap-4 border-b border-slate-200 p-5 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-serif text-2xl font-bold text-[#102b3a]">Unresolved security identifiers</h2><p className="mt-1 text-xs text-slate-500">Assign only verified tickers. Existing holdings and change records update together.</p></div><label className="flex items-center gap-2 rounded-lg border border-slate-200 px-3"><Search className="h-4 w-4 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search issuer or CUSIP" className="py-2.5 text-sm outline-none" /></label></div><div className="grid gap-px bg-slate-200 lg:grid-cols-[1fr_1fr]"><div className="max-h-[420px] overflow-y-auto bg-white">{unresolved.map((row) => <button key={row.cusip} onClick={() => setMapping({ cusip: row.cusip, ticker: '', issuer_name: row.issuer_name, reason: '' })} className={`block w-full border-b border-slate-100 p-4 text-left hover:bg-slate-50 ${mapping.cusip === row.cusip ? 'bg-amber-50' : ''}`}><div className="flex justify-between gap-3"><strong className="text-sm">{row.issuer_name}</strong><span className="text-xs text-slate-400">{row.observations} rows</span></div><p className="mt-1 font-mono text-xs text-slate-500">{row.cusip}</p></button>)}{!unresolved.length ? <p className="p-8 text-center text-sm text-slate-500">No unresolved identifiers match the search.</p> : null}</div><div className="bg-white p-6"><h3 className="font-serif text-xl font-bold">Map CUSIP to ticker</h3><div className="mt-5 space-y-4">{[['CUSIP', 'cusip'], ['Issuer', 'issuer_name'], ['Verified ticker', 'ticker'], ['Reason or source', 'reason']].map(([label, key]) => <label key={key} className="block text-xs font-bold text-slate-600">{label}<input value={mapping[key]} readOnly={key === 'cusip' || key === 'issuer_name'} onChange={(event) => setMapping((value) => ({ ...value, [key]: event.target.value }))} className={`mt-2 w-full rounded-lg border border-slate-200 px-3 py-3 text-sm ${key === 'cusip' || key === 'issuer_name' ? 'bg-slate-50' : ''}`} /></label>)}<button disabled={!mapping.cusip || !mapping.ticker || Boolean(working)} onClick={() => run('mapping', () => saveInstitutionalSecurityMapping(mapping), `Mapped ${mapping.cusip} to ${mapping.ticker.toUpperCase()}.`)} className="inline-flex w-full items-center justify-center gap-2 rounded-lg bg-amber-700 px-4 py-3 text-sm font-bold text-white disabled:opacity-40"><Save className="h-4 w-4" /> Save verified mapping</button></div></div></div></section>

      <section className="mt-7 grid gap-7 xl:grid-cols-2"><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-serif text-2xl font-bold text-[#102b3a]">Filing alerts</h2><div className="mt-5 space-y-3">{data?.alerts?.slice(0, 15).map((alert) => <div key={alert.id} className={`rounded-lg border p-4 ${alert.is_read ? 'border-slate-100 bg-slate-50' : 'border-amber-200 bg-amber-50'}`}><div className="flex items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.12em] text-amber-700">{alert.severity} · {alert.institutional_managers?.display_name}</p><p className="mt-2 text-sm font-bold">{alert.title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{alert.body}</p></div>{!alert.is_read ? <button onClick={() => run(`alert-${alert.id}`, () => markInstitutionalAlert(alert.id), 'Alert marked as reviewed.')} className="shrink-0 text-xs font-bold text-[#123b4b]">Mark read</button> : null}</div></div>)}</div></div><div className="rounded-xl border border-slate-200 bg-white p-5"><h2 className="font-serif text-2xl font-bold text-[#102b3a]">Correction audit</h2><div className="mt-5 space-y-3">{data?.corrections?.slice(0, 15).map((row) => <div key={row.id} className="border-b border-slate-100 pb-3"><div className="flex justify-between gap-3"><strong className="text-xs">{row.entity_type}: {row.entity_key}</strong><span className="text-[10px] text-slate-400">{new Date(row.created_at).toLocaleString()}</span></div><p className="mt-1 text-xs text-slate-500">{row.field_name}: <span className="line-through">{row.old_value || 'blank'}</span> → <strong>{row.new_value}</strong></p><p className="mt-1 text-[10px] text-slate-400">{row.actor}{row.reason ? ` · ${row.reason}` : ''}</p></div>)}</div></div></section>
    </div></div>;
}
