import {useEffect,useState} from 'react';
import {useSearchParams,Link} from 'react-router-dom';
import {API_ORIGIN} from '@/config';
import {supabase} from '@/lib/supabaseClient';
async function request(path,body){const {data}=await supabase.auth.getSession();if(!data.session)throw Error('Admin sign-in required');const r=await fetch(`${API_ORIGIN||''}/api/portfolios/${path}`,{method:body?'POST':'GET',headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
export default function PortfolioRebalances(){
 const [params]=useSearchParams(),[rows,setRows]=useState([]),[selected,setSelected]=useState(null),[target,setTarget]=useState(null),[date,setDate]=useState(''),[reason,setReason]=useState(''),[cost,setCost]=useState('0'),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 function choose(row){setSelected(row);setTarget(structuredClone(row.portfolio));setDate('');setReason('');setMessage('');}
 useEffect(()=>{request('admin/ledger-catalog').then(d=>{setRows(d.portfolios);const r=d.portfolios.find(p=>p.id===params.get('edit'))||d.portfolios[0];if(r)choose(r);}).catch(e=>setMessage(e.message));},[]);
 function edit(category,index,key,value){setTarget(t=>{const n=structuredClone(t),holdings=category==null?n.holdings:n.categories[category].holdings;holdings[index][key]=value;return n;});}
 function remove(category,index){setTarget(t=>{const n=structuredClone(t);if(category==null)n.holdings.splice(index,1);else n.categories[category].holdings.splice(index,1);return n;});}
 function add(category){setTarget(t=>{const n=structuredClone(t);(category==null?n.holdings:n.categories[category].holdings).push({name:'',symbol:'',weight:0});return n;});}
 async function submit(e){e.preventDefault();setBusy(true);try{const d=await request(`${selected.id}/rebalance`,{ledgerRevision:selected.ledgerRevision,target,effectiveDate:date,reason,feeBps:Number(cost)});setRows(r=>r.map(x=>x.id===d.id?d:x));setSelected(d);setMessage('Scheduled. Existing holdings and past returns are unchanged until execution.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 async function cancel(){setBusy(true);try{const d=await request(`${selected.id}/rebalance/cancel`,{ledgerRevision:selected.ledgerRevision});setSelected(d);setRows(r=>r.map(x=>x.id===d.id?d:x));setMessage('Pending rebalance cancelled; audit record preserved.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 const renderHoldings=(holdings,category)=> <><table><thead><tr><th>Company</th><th>Symbol</th><th>Target %</th><th/></tr></thead><tbody>{holdings.map((h,i)=><tr key={i}><td><input required value={h.name} onChange={e=>edit(category,i,'name',e.target.value)}/></td><td><input required value={h.symbol} onChange={e=>edit(category,i,'symbol',e.target.value.toUpperCase())}/></td><td><input required type="number" min="0.01" max="100" step="any" value={h.weight} onChange={e=>edit(category,i,'weight',Number(e.target.value))}/></td><td><button type="button" onClick={()=>remove(category,i)}>Remove</button></td></tr>)}</tbody></table><button type="button" onClick={()=>add(category)}>Add stock</button><p>Total stocks: {holdings.reduce((s,h)=>s+Number(h.weight),0).toFixed(4)}%</p></>;
 return <main className="agi-portfolios pf-editor"><h1>Dated portfolio rebalances</h1><p>Schedule a future market close. Existing returns remain frozen. Model costs are basis points per traded value, not a brokerage quote. 0 means gross of trading costs.</p><Link to="/admin/portfolios">Portfolio editor</Link>{message&&<p role="status" className="pf-warning">{message}</p>}<select aria-label="Portfolio" value={selected?.id||''} disabled={busy} onChange={e=>choose(rows.find(r=>r.id===e.target.value))}>{rows.map(r=><option key={r.id} value={r.id}>{r.portfolio.market} · {r.portfolio.name}</option>)}</select>{selected?.pending?<section><h2>Pending for {selected.pending.effectiveDate}</h2><p>{selected.pending.reason}</p><button disabled={busy} onClick={cancel}>Cancel pending rebalance</button></section>:target&&<form onSubmit={submit}><fieldset disabled={busy}><h2>{target.name}</h2><label>Future effective date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><label>Reason<textarea required minLength={8} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label><label>Trading cost (basis points)<input type="number" required min="0" max="100" step="0.1" value={cost} onChange={e=>setCost(e.target.value)}/></label>{target.conviction?target.categories.map((c,i)=><section key={c.name}><h3>{c.name} · existing category sleeve</h3>{renderHoldings(c.holdings,i)}</section>):<>{renderHoldings(target.holdings,null)}<label>Cash weight %<input type="number" min="0" max="99.99" step="any" value={target.cashWeight||0} onChange={e=>setTarget(t=>({...t,cashWeight:Number(e.target.value)}))}/></label></>}<p>This records a model rebalance, not an order. The private combined portfolio is independently scheduled; edits to its parent portfolios do not rebalance it.</p><button className="pf-button" type="submit">{busy?'Saving…':'Schedule rebalance'}</button></fieldset></form>}</main>;
}
