"""Phase 4 Industrial, Manufacturing and Real Assets curriculum."""
from __future__ import annotations
from financials_valuation.schema import KPIKnowledge,SectorValuationModel,ValuationMethodRule

VERSION="industrial-valuation-v4.0.0"; PARENT_SECTOR="INDUSTRIALS_MANUFACTURING_REAL_ASSETS"

def k(key,name,why,chain): return KPIKnowledge(key,name,why,"reported or AFE-calculated from cited inputs","context_specific","Quarterly/Annual",("Audited filing","NSE/BSE","Official results","Investor presentation"),why,(chain,),"Changes sustainable earnings, FCF, ROCE and valuation.","Scope and cycle position require reconciliation.",( "VALIDATED","TRUSTED"))
def m(method,tier,reason,req): return ValuationMethodRule(method,tier,reason,req,(reason,),("Requires normalized PIT inputs.",),("Missing/stale inputs","Peak-cycle denominator","Unsuitable business model"))
COMMON=(k("revenue","Revenue","Output requiring order/volume-price decomposition.","demand -> orders/volume -> revenue"),k("ebitda_margin","EBITDA Margin","Measures spread and fixed-cost absorption.","pricing - input cost + utilization -> margin"),k("working_capital_days","Working Capital Days","Separates EBITDA from cash conversion.","receivables + inventory - payables -> FCF"),k("capex","Capex","Separates maintenance, expansion and replacement investment.","capex -> capacity -> utilization -> returns"),k("fcf","Free Cash Flow","Tests cash available after working capital and capex.","EBITDA -> working capital -> capex -> FCF"),k("roce","ROCE","Tests value creation across the cycle.","normalized NOPAT / capital -> ROCE"))
ORDER=(k("order_inflow","Order Inflow","Measures new demand converted to signed orders.","demand -> signed orders"),k("order_book","Order Book","Conditional revenue visibility, not revenue.","signed executable orders -> execution"),k("book_to_bill","Book-to-bill","Compares inflow with current revenue scale.","inflow / revenue -> backlog direction"),k("execution_rate","Execution Rate","Measures backlog conversion.","executable order -> execution -> revenue"))
CAP=(k("capacity","Capacity","Sets potential output, not actual revenue.","commissioned capacity -> available output"),k("utilization","Utilization","Measures demand against available capacity.","production / capacity -> absorption"),k("realization","Realization","Captures price and mix per unit.","price + mix -> revenue/unit"))
COM=(k("commodity_spread","Commodity Spread","Separates realization from input cost.","price - cash cost -> spread"),k("ebitda_per_unit","EBITDA per Unit","Normalizes unit economics.","spread x volume -> EBITDA"),k("normalized_margin","Normalized Margin","Prevents peak-cycle extrapolation.","mid-cycle spread -> normalized earnings"))

CFG={
"CAPITAL_GOODS":("Capital Goods / Industrial Machinery",ORDER+CAP,("Industrial capex","Aftermarket","Exports"),("PRICE_TO_EARNINGS","EV_EBITDA","GORDON_DCF")),
"ENGINEERING_EPC":("Engineering & EPC",ORDER+(k("receivable_days","Receivable Days","Flags cash-conversion and client risk.","execution -> billing -> collection"),),("Project execution","Bidding discipline","Retention money"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF","SOTP_3_SEGMENT")),
"INFRASTRUCTURE":("Infrastructure",ORDER+(k("concession_life","Concession Life","Bounds project cash-flow duration.","concession term -> cash-flow duration"),),("Traffic/tariffs","Government capex","Interest rates"),("GORDON_DCF","NAV","EV_EBITDA","SOTP_3_SEGMENT")),
"CONSTRUCTION":("Construction",ORDER+(k("order_quality","Order Quality","Conditions backlog on counterparty, margin and cancellation risk.","client + margin + timeline -> executable value"),),("Construction activity","Labour","Steel/cement","Financing"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF")),
"CEMENT":("Cement",CAP+COM,("Volume","Cement price","Fuel/power/freight","Regional demand"),("EV_EBITDA","INDUSTRIAL_EV_PER_CAPACITY","PRICE_TO_EARNINGS","GORDON_DCF")),
"STEEL":("Steel",CAP+COM,("Steel price","Iron ore/coking coal","Imports/exports","Infrastructure demand"),("EV_EBITDA","INDUSTRIAL_EV_PER_CAPACITY","GORDON_DCF","NAV")),
"METALS_MINING":("Metals & Mining",CAP+COM+(k("mine_life","Mine Life","Bounds reserve-based cash flows.","reserves / production -> mine life"),),("Commodity price","Grade/recovery","Royalties","Sustaining capex"),("NAV","GORDON_DCF","EV_EBITDA")),
"CHEMICALS":("Chemicals",CAP+COM,("Volume","Raw materials","Energy","China supply","Product mix"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF")),
"SPECIALTY_CHEMICALS":("Specialty Chemicals",CAP+(k("customer_concentration","Customer Concentration","Measures qualification and bargaining exposure.","customer loss -> utilization"),k("molecule_pipeline","Molecule Pipeline","Conditional future revenue after qualification.","qualification -> scale-up -> revenue")),("Custom synthesis","China+1","Qualification","Restocking risk"),("PRICE_TO_EARNINGS","EV_EBITDA","GORDON_DCF")),
"AUTO_AUTO_COMPONENTS":("Auto & Auto Components",CAP+(k("content_per_vehicle","Content per Vehicle","Links vehicle output to component revenue.","vehicle production x content -> revenue"),),("Vehicle volumes","ASP/mix","Financing","EV penetration","Exports"),("PRICE_TO_EARNINGS","EV_EBITDA","GORDON_DCF","SOTP_3_SEGMENT")),
"DEFENCE_AEROSPACE":("Defence & Aerospace",ORDER+(k("order_state","Order State","Preserves announced, signed, executable, revenue and cash states.","announcement != signed != executable != cash"),),("Procurement","Localization","Exports","Program lifecycle"),("PRICE_TO_EARNINGS","EV_EBITDA","GORDON_DCF","SOTP_3_SEGMENT")),
"RAIL_TRANSPORT_EQUIPMENT":("Railways & Transportation Equipment",ORDER+CAP,("Rail capex","Wagon/locomotive demand","Execution"),("PRICE_TO_EARNINGS","EV_EBITDA","GORDON_DCF")),
"ELECTRICAL_EQUIPMENT":("Electrical Equipment",ORDER+CAP,("Power/transmission capex","Renewable integration","Copper/aluminium"),("PRICE_TO_EARNINGS","EV_EBITDA","GORDON_DCF")),
"RENEWABLE_EQUIPMENT":("Renewable Energy Equipment",ORDER+CAP+(k("commissioned_capacity","Commissioned Capacity","Separates announced from operating capacity.","announced -> commissioned -> utilized -> revenue"),),("Renewable additions","Technology","Policy/imports","Module prices"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF")),
"PACKAGING":("Packaging",CAP+COM,("Volume","Resin/paper/aluminium","Customer concentration","Exports"),("EV_EBITDA","PRICE_TO_EARNINGS","GORDON_DCF")),
"PAPER_PULP":("Paper & Pulp",CAP+COM,("Paper/pulp price","Wood/waste paper","Energy","Exports"),("EV_EBITDA","INDUSTRIAL_EV_PER_CAPACITY","GORDON_DCF")),
}
METHOD_REASON={"PRICE_TO_EARNINGS":"Normalized profitable equity earnings.","EV_EBITDA":"Cross-cycle operating-value comparison.","GORDON_DCF":"Explicit cash flow, reinvestment and cost of capital.","NAV":"Asset/reserve/concession value.","SOTP_3_SEGMENT":"Distinct segment economics.","INDUSTRIAL_EV_PER_CAPACITY":"Replacement/capacity cross-check only."}
def build(f,c):
 name,kpis,drivers,methods=c
 return SectorValuationModel(f"INDUSTRIALS.{f}",name,f,(name,),"Demand transmits through orders or volume, execution, capacity utilization, spread, working capital and capex into FCF and ROCE.",drivers,("Raw materials","Energy","Labour","Freight","Fixed cost"),"Capital intensity, working-capital funding and cycle-adjusted leverage are central.",( "Environmental","Safety","Procurement","Trade","Land and permits"),COMMON+kpis,tuple(m(x,"PRIMARY" if i==0 else "CROSS_CHECK",METHOD_REASON[x],()) for i,x in enumerate(methods)),drivers,("Cycle","Execution","Overcapacity","Working capital","Debt"),("orders/volume","utilization","spread/margin","working capital","capex"),tuple(x.name for x in kpis)+("FCF","ROCE","Net debt"),("Order book is not revenue","Reported EBITDA may be peak-cycle","EBITDA growth is not cash-flow growth"),("Audited filings","Official disclosures","Licensed commodity/industry data"),"2026-08-16",.80,"IMPLEMENTED_NOT_RESEARCH_VALIDATED",VERSION)
MODELS={f:build(f,c) for f,c in CFG.items()}
CAUSAL={f:(("demand","orders_or_volume","execution","revenue","utilization","ebitda","working_capital","fcf","roce","valuation"),("capacity_addition","supply","utilization","pricing","margin","roce")) for f in MODELS}
